# Vilnius TECH

[.text-center]
## Elektronikos fakultetas

### Kompiuterijos ir ryšių technologijų katedra

{nbsp}

{nbsp}

{nbsp}

{nbsp}

### Telekomunikacijų paslaugų kokybės valdymas
Modulis ELKRM17205

#### Pratybų užduotis nr. 6, +
`1520080923.pcap.gz`

{nbsp}

{nbsp}

{nbsp}

{nbsp}

[.text-right]
**Atliko:** TETfm-20 grupės magistrantas +
                       Saulius Krasuckas +
**Tikrino:** doc. dr. Lukas Pavilanskas

{nbsp}

{nbsp}

{nbsp}

{nbsp}

VILNIUS, 2021

<<<
---

[.text-left]
## Ataskaita

### 1. Darbo tikslas

Ištirti, įsisavinti ir išmokti analizuoti paketinių duomenų srautus ir jų charakteristikas.

Savarankiškai išanalizuoti, įvertinti jų tipus ir matematinius modelius.

Gebėti įvertinti paslaugų, susijusių su šių srautų charakteristikomis, kokybės rodiklius.


### 2. Bendra _Capture_ failo statistika

[source,C]
----
[p@h ~]$ capinfos /rpool/VGTU-studijos/1520080923.pcap.gz 
File name:           /rpool/VGTU-studijos/1520080923.pcap.gz
File type:           Wireshark/tcpdump/... - pcap (gzip compressed)
File encapsulation:  Ethernet
File timestamp precision:  microseconds (6)
Packet size limit:   file hdr: 65535 bytes
Packet size limit:   inferred: 68 bytes
Number of packets:   42k
File size:           2,548kB
Data size:           32MB
Capture duration:    313.451723 seconds
First packet time:   2008-09-21 21:00:00.000132
Last packet time:    2008-09-21 21:05:13.451855
Data byte rate:      104kBps
Data bit rate:       833kbps
Average packet size: 761.65 bytes
Average packet rate: 136 packets/s
SHA256:              a980de740f93624e935d70dafe42a9a6f2e8059d2ec0d1c2b7f9aabd167fc271
RIPEMD160:           32115718d9119aba53bd051cca00e09c6e4e9410
SHA1:                558060efa6af7189c445278fae88f79c24446d5a
Strict time order:   True
Number of interfaces in file: 1
Interface #0 info:
                     Encapsulation = Ethernet (1 - ether)
                     Capture length = 65535
                     Time precision = microseconds (6)
                     Time ticks per second = 1000000
                     Number of stat entries = 0
                     Number of packets = 42858

----

<<<
---

.Suapvalinta pagrindinė statistika
|===
| Paketų skaičius           | 42858
| Duomenų apimtis           | 32 MiB
| Įrašymo trukmė            | 313.451723 s
| Vidutinė sparta           | 833 kbps
| Vidutinis paketo dydis    | 761.65 B
| Vidutinė paketinė sparta  | 136 pps
|===


### 3. Išsamūs rezultatai

1.{nbsp}

 * Šaltinio ir paskirties mazgai:
[source,C]
----
[p@h VGTU-studijos]$ tshark -Qnz endpoints,eth -r 1520080923.pcap.gz 2>/dev/null | awk '!/^Filter/ {print} /^[0-9a-f]/ && !/^ff:ff:ff:ff:ff:ff/ {L2++} END {print "\nIš viso aptikta L2 mazgų: "L2}'
================================================================================
Ethernet Endpoints
                       |  Packets  | |  Bytes  | | Tx Packets | | Tx Bytes | | Rx Packets | | Rx Bytes |
00:15:58:84:23:d8          42843      32641100      18519         2198543       24324        30442557   
00:19:5b:30:95:99          34312      27475781      19851        25832172       14461         1643609   
00:19:5b:30:95:66           8546       5166906       4488         4611972        4058          554934   
ff:ff:ff:ff:ff:ff             14          1426          0               0          14            1426   
01:00:5e:40:98:8f              1           161          0               0           1             161   
================================================================================

Iš viso aptikta L2 mazgų: 4
----

[source,C]
----
[p@h VGTU-studijos]$ tshark -Qnz endpoints,ip -r 1520080923.pcap.gz 2>/dev/null | awk '!/^Filter/ {print} /^[0-9]/ {L3++} END {print "\nIš viso aptikta L3 mazgų: "L3}'
================================================================================
IPv4 Endpoints
                       |  Packets  | |  Bytes  | | Tx Packets | | Tx Bytes | | Rx Packets | | Rx Bytes |
172.31.187.11              34922      30223617      13091         1044418       21831        29179199   
172.31.187.1               34300      27475169      19845        25831812       14455         1643357   
172.31.187.31               7895       2416193       5413         1153495        2482         1262698   
81.16.232.111               1895       1179476        972         1043010         923          136466   
213.197.165.226             1690       1611199       1076         1544662         614           66537   
81.16.232.110                998        717125        514          673023         484           44102   
81.16.232.59                 967        536458        462          482265         505           54193   
8.12.211.126                 580        266629        307          211142         273           55487   
205.128.69.125               441        217683        236          180757         205           36926   
81.16.232.58                 325         52830        132           19662         193           33168   
172.31.187.126               282         34820        141           23542         141           11278   
81.16.232.72                 240         37431        118           19473         122           17958   
88.196.219.234               121         76557         58           71040          63            5517   
213.155.158.59               101         78870         57           71803          44            7067   
92.122.213.112                97         63546         46           58201          51            5345   
193.88.71.111                 80         14106         32            5938          48            8168   
130.132.51.8                  76         36975         36           32631          40            4344   
209.132.176.122               75         41628         37           37680          38            3948   
81.16.232.80                  72         11007         35            4621          37            6386   
72.21.206.5                   64         43021         31           39706          33            3315   
193.88.71.170                 60         10662         24            4371          36            6291   
92.61.33.93                   48         18958         21           15727          27            3231   
209.85.135.99                 47         27105         21           22028          26            5077   
80.48.15.22                   41          7186         16            2580          25            4606   
66.35.62.162                  37         12940         18           10152          19            2788   
80.48.15.29                   31          5551         12            1969          19            3582   
74.125.43.100                 29         20552         16            5282          13           15270   
74.125.43.113                 28          9197         10            3682          18            5515   
62.146.27.166                 27         14656         13           13289          14            1367   
74.125.99.153                 19          9134          9            7764          10            1370   
216.73.86.52                  15          4140          6            2394           9            1746   
74.125.39.127                 12          2738          5             667           7            2071   
84.32.127.187                 10          1186         10            1186           0               0   
172.31.187.127                10          1186          0               0          10            1186   
86.64.162.35                  10          1112          4             569           6             543   
217.212.252.86                10          1510          4             616           6             894   
239.192.152.143                1           161          0               0           1             161   
================================================================================

Iš viso aptikta L3 mazgų: 37
----

 * Juos sugrupuoti pagal srautus.
[source,C]
----
[p@h VGTU-studijos]$ tshark -Qnz conv,eth -r 1520080923.pcap.gz 2>/dev/null
================================================================================
Ethernet Conversations
Filter:<No Filter>
                                               |       <-      | |       ->      | |     Total     |    Relative    |   Duration   |
                                               | Frames  Bytes | | Frames  Bytes | | Frames  Bytes |      Start     |              |
00:15:58:84:23:d8    <-> 00:19:5b:30:95:99      19849 25MB        14461 1,643kB     34310 27MB          0.234336000       313.2174
00:15:58:84:23:d8    <-> 00:19:5b:30:95:66       4475 4,610kB      4058 554kB        8533 5,165kB       0.000000000       290.1015
00:19:5b:30:95:66    <-> ff:ff:ff:ff:ff:ff          0 0bytes         13 1,366bytes      13 1,366bytes     0.249072000       293.2485
00:19:5b:30:95:99    <-> ff:ff:ff:ff:ff:ff          0 0bytes          1 60bytes         1 60bytes       0.234316000         0.0000
00:19:5b:30:95:99    <-> 01:00:5e:40:98:8f          0 0bytes          1 161bytes        1 161bytes     36.159141000         0.0000
================================================================================
----

 * Gautas mazgų grupes (ir srautus) charakterizuoti ir palyginti.
