Script started on 2022-02-03 19:36:13+02:00 [TERM="xterm" TTY="/dev/pty0" COLUMNS="-1" LINES="-1"]

Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
/dev/sda1: clean, 165781/14458880 files, 2862145/57829632 blocks
[[0;32m  OK  [0m] Mounted [0;1;39mMount unit for core18, revision 2284[0m.
snap-core18-2284.mount
[[0;32m  OK  [0m] Started [0;1;39mShow Plymouth Boot Screen[0m.
plymouth-start.service
[[0;32m  OK  [0m] Started [0;1;39mForward Password R…s to Plymouth Directory Watch[0m.
[[0;32m  OK  [0m] Reached target [0;1;39mLocal Encrypted Volumes[0m.
[[0;32m  OK  [0m] Mounted [0;1;39mMount unit for core20, revision 1328[0m.
snap-core20-1328.mount
[[0;32m  OK  [0m] Mounted [0;1;39mMount unit for bare, revision 5[0m.
snap-bare-5.mount
[[0;32m  OK  [0m] Mounted [0;1;39mMount unit for core18, revision 2128[0m.
snap-core18-2128.mount
[[0;32m  OK  [0m] Mounted [0;1;39mMount unit for gnome-3-34-1804, revision 72[0m.
snap-gnome\x2d3\x2d34\x2d1804-72.mount
[[0;32m  OK  [0m] Mounted [0;1;39mMount unit for gnome-3-34-1804, revision 77[0m.
snap-gnome\x2d3\x2d34\x2d1804-77.mount
[[0;32m  OK  [0m] Mounted [0;1;39mMount unit for gtk-common-themes, revision 1515[0m.
snap-gtk\x2dcommon\x2dthemes-1515.mount
snap-gtk\x2dcommon\x2dthemes-1519.mount
[[0;32m  OK  [0m] Mounted [0;1;39mMount unit for gtk-common-themes, revision 1519[0m.
[[0;32m  OK  [0m] Mounted [0;1;39mMount unit for snapd, revision 12704[0m.
snap-snapd-12704.mount
snap-snap\x2dstore-558.mount
[[0;32m  OK  [0m] Mounted [0;1;39mMount unit for snap-store, revision 558[0m.
[[0;32m  OK  [0m] Mounted [0;1;39mMount unit for snapd, revision 14549[0m.
snap-snapd-14549.mount
[[0;32m  OK  [0m] Mounted [0;1;39mMount unit for snap-store, revision 547[0m.
snap-snap\x2dstore-547.mount
[[0;32m  OK  [0m] Found device [0;1;39m/dev/ttyS0[0m.
[[0;32m  OK  [0m] Listening on [0;1;39mLoad/Save RF …itch Status /dev/rfkill Watch[0m.
[[0;32m  OK  [0m] Found device [0;1;39mVBOX_HARDDISK 3[0m.
         Starting [0;1;39mFile System Check…b2a7-41c1-86cb-9ada240ff9ed[0m...
[[0;32m  OK  [0m] Started [0;1;39mFile System Check Daemon to report status[0m.
systemd-fsckd.service
[[0;32m  OK  [0m] Found device [0;1;39mVBOX_HARDDISK 2[0m.
         Activating swap [0;1;39m/dev/disk/…b4d0-408a-a959-dbce0dfb0bb9[0m...
dev-disk-by\x2did-ata\x2dVBOX_HARDDISK_VBb6ebcaaa\x2d6f3f2eb2\x2dpart2.swap
dev-disk-by\x2dpartuuid-38d010a9\x2d02.swap
dev-disk-by\x2dpath-pci\x2d0000:00:0d.0\x2data\x2d1\x2dpart2.swap
dev-sda2.swap
dev-disk-by\x2duuid-64f755b6\x2db4d0\x2d408a\x2da959\x2ddbce0dfb0bb9.swap
[[0;32m  OK  [0m] Activated swap [0;1;39m/dev/disk/b…6-b4d0-408a-a959-dbce0dfb0bb9[0m.
[[0;32m  OK  [0m] Reached target [0;1;39mSwap[0m.
[[0;32m  OK  [0m] Finished [0;1;39mFile System Check…0-b2a7-41c1-86cb-9ada240ff9ed[0m.
systemd-fsck@dev-disk-by\x2duuid-38279fa0\x2db2a7\x2d41c1\x2d86cb\x2d9ada240ff9ed.service
         Mounting [0;1;39m/home[0m...
[[0;32m  OK  [0m] Mounted [0;1;39m/home[0m.
home.mount
[[0;32m  OK  [0m] Reached target [0;1;39mLocal File Systems[0m.
         Starting [0;1;39mLoad AppArmor profiles[0m...
         Starting [0;1;39mSet console font and keymap[0m...
         Starting [0;1;39mTell Plymouth To Write Out Runtime Data[0m...
         Starting [0;1;39mCreate Volatile Files and Directories[0m...
console-setup.service
[[0;32m  OK  [0m] Finished [0;1;39mSet console font and keymap[0m.
[[0;32m  OK  [0m] Finished [0;1;39mTell Plymouth To Write Out Runtime Data[0m.
[[0;32m  OK  [0m] Finished [0;1;39mCreate Volatile Files and Directories[0m.
systemd-tmpfiles-setup.service
         Starting [0;1;39mNetwork Name Resolution[0m...
         Starting [0;1;39mNetwork Time Synchronization[0m...
         Starting [0;1;39mUpdate UTMP about System Boot/Shutdown[0m...
systemd-update-utmp.service
[[0;32m  OK  [0m] Finished [0;1;39mUpdate UTMP about System Boot/Shutdown[0m.
[[0;32m  OK  [0m] Started [0;1;39mNetwork Time Synchronization[0m.
[[0;32m  OK  [0m] Reached target [0;1;39mSystem Time Set[0m.
[[0;32m  OK  [0m] Reached target [0;1;39mSystem Time Synchronized[0m.
systemd-timesyncd.service
[[0;32m  OK  [0m] Started [0;1;39mNetwork Name Resolution[0m.
[[0;32m  OK  [0m] Reached target [0;1;39mHost and Network Name Lookups[0m.
systemd-resolved.service
[[0;32m  OK  [0m] Finished [0;1;39mLoad AppArmor profiles[0m.
apparmor.service
         Starting [0;1;39mLoad AppArmor pro…managed internally by snapd[0m...
[[0;32m  OK  [0m] Finished [0;1;39mLoad AppArmor pro…s managed internally by snapd[0m.
snapd.apparmor.service
[[0;32m  OK  [0m] Reached target [0;1;39mSystem Initialization[0m.
[[0;32m  OK  [0m] Started [0;1;39mACPI Events Check[0m.
[[0;32m  OK  [0m] Started [0;1;39mCUPS Scheduler[0m.
[[0;32m  OK  [0m] Started [0;1;39mTrigger anacron every hour[0m.
[[0;32m  OK  [0m] Started [0;1;39mDaily apt download activities[0m.
[[0;32m  OK  [0m] Started [0;1;39mDaily apt upgrade and clean activities[0m.
[[0;32m  OK  [0m] Started [0;1;39mPeriodic ext4 Onli…ata Check for All Filesystems[0m.
[[0;32m  OK  [0m] Started [0;1;39mDiscard unused blocks once a week[0m.
[[0;32m  OK  [0m] Started [0;1;39mRefresh fwupd metadata regularly[0m.
[[0;32m  OK  [0m] Started [0;1;39mDaily rotation of log files[0m.
[[0;32m  OK  [0m] Started [0;1;39mDaily man-db regeneration[0m.
[[0;32m  OK  [0m] Started [0;1;39mMessage of the Day[0m.
[[0;32m  OK  [0m] Started [0;1;39mDaily Cleanup of Temporary Directories[0m.
[[0;32m  OK  [0m] Started [0;1;39mUbuntu Advantage update messaging[0m.
[[0;32m  OK  [0m] Reached target [0;1;39mPaths[0m.
[[0;32m  OK  [0m] Reached target [0;1;39mTimers[0m.
[[0;32m  OK  [0m] Listening on [0;1;39mACPID Listen Socket[0m.
[[0;32m  OK  [0m] Listening on [0;1;39mAvahi mDNS/DNS-SD Stack Activation Socket[0m.
[[0;32m  OK  [0m] Listening on [0;1;39mCUPS Scheduler[0m.
[[0;32m  OK  [0m] Listening on [0;1;39mD-Bus System Message Bus Socket[0m.
         Starting [0;1;39mSocket activation for snappy daemon[0m.
[[0;32m  OK  [0m] Listening on [0;1;39mUUID daemon activation socket[0m.
[[0;32m  OK  [0m] Listening on [0;1;39mSocket activation for snappy daemon[0m.
[[0;32m  OK  [0m] Reached target [0;1;39mSockets[0m.
[[0;32m  OK  [0m] Reached target [0;1;39mBasic System[0m.
         Starting [0;1;39mAccounts Service[0m...
[[0;32m  OK  [0m] Started [0;1;39mACPI event daemon[0m.
acpid.service
[[0;32m  OK  [0m] Started [0;1;39mRun anacron jobs[0m.
anacron.service
         Starting [0;1;39mLSB: automatic crash report generation[0m...
         Starting [0;1;39mAvahi mDNS/DNS-SD Stack[0m...
[[0;32m  OK  [0m] Started [0;1;39mRegular background program processing daemon[0m.
cron.service
[[0;32m  OK  [0m] Started [0;1;39mCUPS Scheduler[0m.
cups.service
[[0;32m  OK  [0m] Started [0;1;39mD-Bus System Message Bus[0m.
dbus.service
         Starting [0;1;39mNetwork Manager[0m...
[[0;32m  OK  [0m] Started [0;1;39mSave initial kernel messages after boot[0m.
dmesg.service
         Starting [0;1;39mRemove Stale Onli…t4 Metadata Check Snapshots[0m...
         Starting [0;1;39mDetect the availa…eal with any system changes[0m...
         Starting [0;1;39mRecord successful boot for GRUB[0m...
[[0;32m  OK  [0m] Started [0;1;39mirqbalance daemon[0m.
irqbalance.service
         Starting [0;1;39mDispatcher daemon for systemd-networkd[0m...
         Starting [0;1;39mAuthorization Manager[0m...
         Starting [0;1;39mRestore /etc/reso… the ppp link was shut down[0m...
         Starting [0;1;39mSystem Logging Service[0m...
         Starting [0;1;39mSnap Daemon[0m...
         Starting [0;1;39mSwitcheroo Control Proxy service[0m...
         Starting [0;1;39mLogin Service[0m...
         Starting [0;1;39mDisk Manager[0m...
         Starting [0;1;39mWPA supplicant[0m...
[[0;32m  OK  [0m] Finished [0;1;39mRestore /etc/reso…re the ppp link was shut down[0m.
[[0;32m  OK  [0m] Finished [0;1;39mDetect the availa… deal with any system changes[0m.
[[0;32m  OK  [0m] Finished [0;1;39mRecord successful boot for GRUB[0m.
[[0;32m  OK  [0m] Finished [0;1;39mRemove Stale Onli…ext4 Metadata Check Snapshots[0m.
[[0;32m  OK  [0m] Started [0;1;39mSystem Logging Service[0m.
rsyslog.service
         Starting [0;1;39mGRUB failed boot detection[0m...
[[0;32m  OK  [0m] Started [0;1;39mLSB: automatic crash report generation[0m.
apport.service
[[0;32m  OK  [0m] Finished [0;1;39mGRUB failed boot detection[0m.
[[0;32m  OK  [0m] Started [0;1;39mLogin Service[0m.
systemd-logind.service
[[0;32m  OK  [0m] Started [0;1;39mWPA supplicant[0m.
wpa_supplicant.service
[[0;32m  OK  [0m] Started [0;1;39mAvahi mDNS/DNS-SD Stack[0m.
avahi-daemon.service
[[0;32m  OK  [0m] Started [0;1;39mMake remote CUPS printers available locally[0m.
cups-browsed.service
[[0;32m  OK  [0m] Started [0;1;39mSwitcheroo Control Proxy service[0m.
switcheroo-control.service
         Starting [0;1;39mSave/Restore Sound Card State[0m...
[[0;32m  OK  [0m] Started [0;1;39mNetwork Manager[0m.
NetworkManager.service
[[0;32m  OK  [0m] Started [0;1;39mAuthorization Manager[0m.
polkit.service
[[0;32m  OK  [0m] Reached target [0;1;39mNetwork[0m.
         Starting [0;1;39mModem Manager[0m...
         Starting [0;1;39mNetwork Manager Wait Online[0m...
         Starting [0;1;39mOpenVPN service[0m...
         Starting [0;1;39mOpenBSD Secure Shell server[0m...
         Starting [0;1;39mHostname Service[0m...
         Starting [0;1;39mPermit User Sessions[0m...
[[0;32m  OK  [0m] Started [0;1;39mUnattended Upgrades Shutdown[0m.
unattended-upgrades.service
[[0;32m  OK  [0m] Finished [0;1;39mSave/Restore Sound Card State[0m.
alsa-restore.service
[[0;32m  OK  [0m] Finished [0;1;39mOpenVPN service[0m.
openvpn.service
[[0;32m  OK  [0m] Finished [0;1;39mPermit User Sessions[0m.
systemd-user-sessions.service
[[0;32m  OK  [0m] Started [0;1;39mAccounts Service[0m.
accounts-daemon.service
[[0;32m  OK  [0m] Reached target [0;1;39mSound Card[0m.
         Starting [0;1;39mGNOME Display Manager[0m...
         Starting [0;1;39mHold until boot process finishes up[0m...
ssh.service
[[0;32m  OK  [0m] Started [0;1;39mOpenBSD Secure Shell server[0m.
udisks2.service
[[0;32m  OK  [0m] Started [0;1;39mDisk Manager[0m.
[[0;32m  OK  [0m] Started [0;1;39mGNOME Display Manager[0m.
gdm.service
networkd-dispatcher.service
[[0;32m  OK  [0m] Started [0;1;39mDispatcher daemon for systemd-networkd[0m.
[[0;32m  OK  [0m] Started [0;1;39mModem Manager[0m.
ModemManager.service
systemd-hostnamed.service
NetworkManager-dispatcher.service
NetworkManager-wait-online.service
whoopsie.service
run-user-125.mount
user-runtime-dir@125.service
kerneloops.service
user@125.service
rtkit-daemon.service
run-user-125-gvfs.mount
tmp-sanity\x2dmountpoint\x2d722000216.mount
snapd.service
upower.service
systemd-timedated.service
snapd.seeded.service
systemd-localed.service
geoclue.service
packagekit.service
fprintd.service
colord.service

Ubuntu 20.04.3 LTS osboxes ttyS0

osboxes login: osboxes.org
osboxes.org
Password: os


Login incorrect
osboxes login: osboxes
osboxes

Password: osbox. es.org

Welcome to Ubuntu 20.04.3 LTS (GNU/Linux 5.11.0-27-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

213 updates can be applied immediately.
130 of these updates are standard security updates.
To see these additional updates run: apt list --upgradable

Your Hardware Enablement Stack (HWE) is supported until April 2025.
Last login: Thu Feb  3 12:27:49 EST 2022 from 192.168.56.1 on pts/0
osboxes@osboxes:~$ 
osboxes@osboxes:~$ w
w
 14:36:45 up 0 min,  1 user,  load average: 0.53, 0.14, 0.05
USER     TTY      FROM             LOGIN@   IDLE   JCPU   PCPU WHAT
osboxes  ttyS0    -                14:36    2.00s  0.09s  0.01s w
osboxes@osboxes:~$ 
osboxes@osboxes:~$ p ip 
ip 
aUsage: ip [ OPTIONS ] OBJECT { COMMAND | help }
       ip [ -force ] -batch filename
where  OBJECT := { link | address | addrlabel | route | rule | neigh | ntable |
                   tunnel | tuntap | maddress | mroute | mrule | monitor | xfrm |
                   netns | l2tp | fou | macsec | tcp_metrics | token | netconf | ila |
                   vrf | sr | nexthop }
       OPTIONS := { -V[ersion] | -s[tatistics] | -d[etails] | -r[esolve] |
                    -h[uman-readable] | -iec | -j[son] | -p[retty] |
                    -f[amily] { inet | inet6 | mpls | bridge | link } |
                    -4 | -6 | -I | -D | -M | -B | -0 |
                    -l[oops] { maximum-addr-flush-attempts } | -br[ief] |
                    -o[neline] | -t[imestamp] | -ts[hort] | -b[atch] [filename] |
                    -rc[vbuf] [size] | -n[etns] name | -N[umeric] | -a[ll] |
                    -c[olor]}
osboxes@osboxes:~$ 
osboxes@osboxes:~$ ip a
aip a

Command 'aip' not found, did you mean:

  command 'wip' from snap wip (1.5.0)
  command 'asp' from deb asp (1.8-8build1)
  command 'gip' from deb gip (1.7.0-1-4build1)
  command 'ip' from deb iproute2 (5.5.0-1ubuntu1)
  command 'arp' from deb net-tools (1.60+git20180626.aebd88e-1ubuntu1)
  command 'zip' from deb zip (3.0-11build1)
  command 'pip' from deb python3-pip (20.0.2-5ubuntu1.6)
  command 'bip' from deb bip (0.9.0~rc3-1)
  command 'aid' from deb id-utils (4.6+git20120811-4ubuntu2)
  command 'sip' from deb sip-dev (4.19.21+dfsg-1build1)

See 'snap info <snapname>' for additional versions.

osboxes@osboxes:~$ 
osboxes@osboxes:~$ ip a
ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp0s3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 08:00:27:e8:e6:15 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global dynamic noprefixroute enp0s3
       valid_lft 86368sec preferred_lft 86368sec
    inet6 fe80::b53f:2342:dc39:4f65/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
3: enp0s8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 08:00:27:27:61:e8 brd ff:ff:ff:ff:ff:ff
    inet 192.168.56.113/24 brd 192.168.56.255 scope global dynamic noprefixroute enp0s8
       valid_lft 569sec preferred_lft 569sec
    inet6 fe80::9036:4eb4:16f8:19ac/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
osboxes@osboxes:~$ 
osboxes@osboxes:~$ 
telnet> 
Connection closed.

Script done on 2022-02-03 19:37:07+02:00 [COMMAND_EXIT_CODE="0"]
