= {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}Vilniaus Gedimino technikos universitetas

[.text-center]
== Elektronikos fakultetas

=== Kompiuterijos ir ryšių technologijų katedra

{nbsp}

{nbsp}

{nbsp}

{nbsp}

{nbsp}

{nbsp}

=== Debesų kompiuterija
Modulis ELKRM17304

[.text-center]
== _Docker Swarm_ klasterio įdiegimas ir tyrimas

Kursinis darbas

{nbsp}

{nbsp}

{nbsp}

{nbsp}

{nbsp}

{nbsp}

[.text-right]
**Atliko:** TETfm-20 grupės magistrantas +
                       Saulius Krasuckas +
**Tikrino:** lekt. dr. Liudas Duoba

{nbsp}

{nbsp}

{nbsp}

{nbsp}

{nbsp}

{nbsp}

{nbsp}

VILNIUS, 2022

<<<



{nbsp}

[.text-center]
==== Kursinis darbas

[.text-center]
== _Docker Swarm_ klasterio įdiegimas ir tyrimas


{nbsp}

=== 1. Kursinio darbo užduotis

[.text-left]
* Savarankiškai išstudijuoti _Docker Swarm_ veikimo principus, juos aprašyti
* Sukonfigūruoti _Docker Swarm_ klasterį,
  kurį sudaro ne mažiau trijų kompiuterių / virtualių mašinų (VM)
* Atvaizduoti klasterio konfigūraciją grafiškai (pateikti schemas)
* Klasteryje paleisti _Web_-servisą, veikiantį konteinerių pagrindu.
  Servisas turi būti pasiekiamas.
* Sukurti ne mažiau kaip 3 serviso kopijas (replikas).
  Parodyti, kaip servisai pasiskirsto klasteryje.
* Imituoti vieno iš klasterio elementų gedimą;
  aprašyti / parodyti poveikį servisams.
* Parodyti / atvaizduoti _Web_-serviso pasiekiamumą visuose etapuose.
* Pateikti naudojamas komandas


{nbsp}

=== 2. Pagrindinė dalis

{nbsp}

[.text-left]
==== _Docker Swarm_ veikimo principai

* Savarankiškai išstudijuoti _Docker Swarm_ veikimo principus, juos aprašyti


{nbsp}

[.text-left]
==== _Docker Swarm_ klasterio konfigūravimas

. Infrastruktūrai kuri pasirinkau namie turimą nešiojamąjį kompiuterį su Windows OS.

. Jame įsidiegiau VirtualBox VMM (arba hipervizorių).

. Kaip _Guest OS_ pasirinkau 64-bit **Ubuntu 20.04.3 LTS** Linux distribuciją.

. Pasinaudojau `OSboxes.org` projekto teikiamu įdiegtos OS atvaizdžiu.  <<1>>

. VM kūrimui ir valdymui pasirinkau VirtualBox CLI `VBoxManage` ir MSYS2 įrankį, kuris Windows OS suteikia _*nix_ tipo aplinką.

. Čia susikūriau kelis _Bash_ skriptus:

 - https://github.com/VGTU-ELF/TETfm-20/tree/main/Semestras-3/2-Debes%C5%B3-kompiuterija/kursinis-darbas/Saulius-Krasuckas#:~:text=build%2Dinfra.sh,ubuntu%2Dhostnames.sh[`build-infra.sh`] (_Golden image_ ir atskirų VM formavimui)
 - https://github.com/VGTU-ELF/TETfm-20/blob/main/Semestras-3/2-Debes%C5%B3-kompiuterija/kursinis-darbas/Saulius-Krasuckas/setup-osboxes-ubuntu-20.04.sh[`setup-osboxes-ubuntu-20.04.sh`] (VM tvarkymo eiga)
 - https://github.com/VGTU-ELF/TETfm-20/blob/main/Semestras-3/2-Debes%C5%B3-kompiuterija/kursinis-darbas/Saulius-Krasuckas/osboxes-ubuntu-20.04-changes.sh[`osboxes-ubuntu-20.04-changes.sh`] (pagrindiniai Guest OS tvarkymo veiksmai)
 - https://github.com/VGTU-ELF/TETfm-20/blob/main/Semestras-3/2-Debes%C5%B3-kompiuterija/kursinis-darbas/Saulius-Krasuckas/setup-ubuntu-docker.sh[`setup-ubuntu-docker.sh`] (_Docker_ įdiegimas)
 - https://github.com/VGTU-ELF/TETfm-20/blob/main/Semestras-3/2-Debes%C5%B3-kompiuterija/kursinis-darbas/Saulius-Krasuckas/setup-ubuntu-hostnames.sh[`setup-ubuntu-hostnames.sh`] (individualizuotų mazgo vardų tvarkymas)
 - Skriptų naudojimo privalumas -- lengva turėti kad ir 20 identiškų virtualių mašinų.
   +
  O padarius konfigūravimo klaidą, lengva ją pataisyti ir visą infrastruktūrą susikurti iš naujo.

. Startavus `build-infra.sh`:

 - Parsisiunčiamas `Ubuntu 20.04.3 (64bit).vdi` atvaizdis.
 - Jo pagrindu sukuriama etaloninė VM.
 - Ji startuojama, ir atliekami pagrindiniai OS tvarkymo veiksmai (SSH raktų tvarkymas, `sudo` perkonfigūravimas, naujinimai, paketų diegimas, perkrovimas, Docker diegimas).
 - VM išjungiama, o disko atvaizdis paruošiamas jungimui prie keleto mašinų (angl. _Multi-attach_).
 - Sukuriamos trys VM pagal bendrą šabloną:

  * 1 GiB RAM, 2 CPU.
  * 1 NIC išėjimui į internetą (angl. _Default route_);
  * 1 NIC Docker klasterio ryšiui (_App_);
  * 1 NIC OAM ryšiui (angl. _Operation, Administration, Maintenance_).
  * Visi NIC gauna adresus iš VBox integruoto DHCP serviso.
  * Kiekvienai VM nustatomas OAM IP adresas.
  * Prie jo prisijungiama automatiškai.
  * `/etc/hosts` faile užregistruojami suteikti IP adresai ir mazgo vardai.
  * Tuomet šie duomenys surenkami į bendrą failą ir padalinimi į visus Guest OS iš eilės.
  * Taip pat patvirtinami SSH ECDSA raktai tarp skirtingų mazgų.

 - Trys VM paruoštos darbui.
 - Išskyrus atvaizdžio siuntimo laiką, paruošimas trunka apie 65 min.

. Rankiniu būdu konfigūruoju _Docker Swarm mode_ klasterį:
+
Patikrinimas:
+
----
$ ssh swarm-n01-oam sudo docker info | grep --color -e Swarm: -e CPUs: -e Total.Memory:
 Swarm: inactive
 CPUs: 2
 Total Memory: 971.2MiB
----
+
Pirmas bandymas startuoti _Swarm_ klasterį:
+
----
$ ssh swarm-n01-oam sudo docker swarm init
Error response from daemon: could not choose an IP address to advertise since this system has multiple addresses on different interfaces (10.0.2.15 on enp0s3 and 10.1.1.24 on enp0s8) - specify one with --advertise-addr
----
+
Bandau nurodyti klasterio ryšio adresą kaip mazgo vardą:
+
----
$ ssh swarm-n01-oam sudo docker swarm init --advertise-addr swarm-n01
Error response from daemon: advertise address must be a non-zero IP address or network interface (with optional port number)
----
+
Netiko. Pateikus interfeiso vardą tiko:
+
----
$ ssh swarm-n01-oam sudo docker swarm init --advertise-addr enp0s8
Swarm initialized: current node (l6wnnbsgv2th6nq05e9j02srj) is now a manager.

To add a worker to this swarm, run the following command:

    docker swarm join --token SWMTKN-1-40jfoeoj9kgwtcqbtc9klrwaeoh8ogfebxoa8r1euzxnzfe7ha-ee278x6iuxb6ny7g4v34z9phw 10.1.1.24:2377

To add a manager to this swarm, run 'docker swarm join-token manager' and follow the instructions.
----
+
Tikrinu būseną:
+
----
$ ssh swarm-n01-oam sudo docker info | grep --color -e ^ -e Swarm
  ...
 Swarm: active
  NodeID: l6wnnbsgv2th6nq05e9j02srj
  Is Manager: true
  ClusterID: tbmszwsuuyydpgzw90lsblvjd
  Managers: 1
  Nodes: 1
  Default Address Pool: 10.0.0.0/8
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 10.1.1.24
  Manager Addresses:
   10.1.1.24:2377
  ...
----
+
Sutikrinu su interfeisų IP adresais:
+
----
$ ssh swarm-n01-oam ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: enp0s3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 08:00:27:7e:2a:d2 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global dynamic noprefixroute enp0s3
       valid_lft 85952sec preferred_lft 85952sec
    inet6 fe80::72a6:ed0b:5033:2f37/64 scope link noprefixroute
       valid_lft forever preferred_lft forever
3: enp0s8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 08:00:27:f0:5c:76 brd ff:ff:ff:ff:ff:ff
    inet 10.1.1.24/24 brd 10.1.1.255 scope global dynamic noprefixroute enp0s8
       valid_lft 453sec preferred_lft 453sec
    inet6 fe80::1d12:9739:5544:643a/64 scope link noprefixroute
       valid_lft forever preferred_lft forever
4: enp0s9: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 08:00:27:57:72:bd brd ff:ff:ff:ff:ff:ff
    inet 192.168.56.101/24 brd 192.168.56.255 scope global dynamic noprefixroute enp0s9
       valid_lft 453sec preferred_lft 453sec
    inet6 fe80::e076:cc40:af50:5f45/64 scope link noprefixroute
       valid_lft forever preferred_lft forever
5: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:2f:74:cc:6f brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
10: docker_gwbridge: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 02:42:2c:42:48:68 brd ff:ff:ff:ff:ff:ff
    inet 172.18.0.1/16 brd 172.18.255.255 scope global docker_gwbridge
       valid_lft forever preferred_lft forever
    inet6 fe80::42:2cff:fe42:4868/64 scope link
       valid_lft forever preferred_lft forever
12: vethb5ec981@if11: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker_gwbridge state UP group default
    link/ether 06:3e:2a:e4:2c:55 brd ff:ff:ff:ff:ff:ff link-netnsid 1
    inet6 fe80::43e:2aff:fee4:2c55/64 scope link
       valid_lft forever preferred_lft forever
----
+
Atitinka `enp0s8`. Tikrinu mazgų sąrašą:
+
----
$ ssh swarm-n01-oam sudo docker node ls
ID                            HOSTNAME    STATUS    AVAILABILITY   MANAGER STATUS   ENGINE VERSION
l6wnnbsgv2th6nq05e9j02srj *   swarm-n01   Ready     Active         Leader           20.10.12
----
+
Prijungiu antrą mazgą:
+
----
$ ssh swarm-n02-oam sudo docker swarm join --token SWMTKN-1-40jfoeoj9kgwtcqbtc9klrwaeoh8ogfebxoa8r1euzxnzfe7ha-ee278x6iuxb6ny7g4v34z9phw 10.1.1.24:2377
This node joined a swarm as a worker.
----
+
Tikrinu mazgų sąrašą:
+
----
$ ssh swarm-n01-oam sudo docker node ls
ID                            HOSTNAME    STATUS    AVAILABILITY   MANAGER STATUS   ENGINE VERSION
l6wnnbsgv2th6nq05e9j02srj *   swarm-n01   Ready     Active         Leader           20.10.12
a50ddvlva40nzzvtxu1hpsus7     swarm-n02   Ready     Active                          20.10.12
----
+
Prijungiu trečią narį:
+
----
$ ssh swarm-n03-oam sudo docker swarm join --token SWMTKN-1-40jfoeoj9kgwtcqbtc9klrwaeoh8ogfebxoa8r1euzxnzfe7ha-ee278x6iuxb6ny7g4v34z9phw 10.1.1.24:2377
This node joined a swarm as a worker.
----
+
Patikrinu, jau visi trys klasteryje:
+
----
$ ssh swarm-n01-oam sudo docker node ls
ID                            HOSTNAME    STATUS    AVAILABILITY   MANAGER STATUS   ENGINE VERSION
l6wnnbsgv2th6nq05e9j02srj *   swarm-n01   Ready     Active         Leader           20.10.12
a50ddvlva40nzzvtxu1hpsus7     swarm-n02   Ready     Active                          20.10.12
6qeivl6aatpwxb50vi8hpr4bh     swarm-n03   Ready     Active                          20.10.12
----


{nbsp}

[.text-left]
==== Klasterio konfigūracija

.(1 pav.) Klasterio mazgų konfigūracija tarpusavyje ir Host OS atžvilgiu.
image::https://raw.githubusercontent.com/VGTU-ELF/TETfm-20/main/Semestras-3/2-Debes%C5%B3-kompiuterija/kursinis-darbas/Saulius-Krasuckas/img/Docker-Swarm-klasterio-konfig%C5%ABracija.svg[width=100%]


{nbsp}

[.text-left]
==== _Web_-serviso startavimas ir tikrinimas

. Iš visos galybės pasirenku _Web_-servisą, matytą _KataCoda_ puslapio treniruotėse: `katacoda/docker-http-server`.  +
Ir startuoju pavienį konteinerį su juo:
+
----
$ ssh swarm-n01-oam sudo docker run -d --name http-band -p 80:80 katacoda/docker-http-server
Unable to find image 'katacoda/docker-http-server:latest' locally
latest: Pulling from katacoda/docker-http-server
f139eb4721ae: Pulling fs layer
f139eb4721ae: Verifying Checksum
f139eb4721ae: Download complete
f139eb4721ae: Pull complete
Digest: sha256:76dc8a47fd019f80f2a3163aba789faf55b41b2fb06397653610c754cb12d3ee
Status: Downloaded newer image for katacoda/docker-http-server:latest
84f32317148cac3ea8dfffb6587258f905d8563064302b7fc457d35156dd4240
----

. Tikrinu, konteineris veikia:
+
----
$ ssh swarm-n01-oam sudo docker ps
CONTAINER ID   IMAGE                         COMMAND   CREATED          STATUS          PORTS                               NAMES
84f32317148c   katacoda/docker-http-server   "/app"    20 seconds ago   Up 19 seconds   0.0.0.0:80->80/tcp, :::80->80/tcp   http-band
----

. Tikrinu su lokaliu http-klientu, veikia:
+
----
$ ssh swarm-n01-oam curl -s localhost
<h1>This request was processed by host: 84f32317148c</h1>
----

. Ištrinu bandomąjį konteinerį:
+
----
$ ssh swarm-n01-oam sudo docker stop http-band
http-band

$ ssh swarm-n01-oam sudo docker rm http-band
http-band
----

. Pagal jo atvaizdį kuriu jau ne pavienį, o klasterinį _Web_-servisą `kursinis-web-service`:
+
----
$ ssh swarm-n01-oam sudo docker service create --name kursinis-web-service -p 80:80 katacoda/docker-http-server
p7imsxwi9midpu5b378srq54w
overall progress: 0 out of 1 tasks
1/1:
overall progress: 0 out of 1 tasks
overall progress: 0 out of 1 tasks
overall progress: 0 out of 1 tasks
overall progress: 0 out of 1 tasks
overall progress: 0 out of 1 tasks
overall progress: 0 out of 1 tasks
overall progress: 0 out of 1 tasks
overall progress: 0 out of 1 tasks
overall progress: 1 out of 1 tasks
verify: Waiting 5 seconds to verify that tasks are stable...
verify: Waiting 5 seconds to verify that tasks are stable...
verify: Waiting 5 seconds to verify that tasks are stable...
verify: Waiting 5 seconds to verify that tasks are stable...
verify: Waiting 5 seconds to verify that tasks are stable...
verify: Waiting 4 seconds to verify that tasks are stable...
verify: Waiting 4 seconds to verify that tasks are stable...
verify: Waiting 4 seconds to verify that tasks are stable...
verify: Waiting 4 seconds to verify that tasks are stable...
verify: Waiting 3 seconds to verify that tasks are stable...
verify: Waiting 3 seconds to verify that tasks are stable...
verify: Waiting 3 seconds to verify that tasks are stable...
verify: Waiting 3 seconds to verify that tasks are stable...
verify: Waiting 3 seconds to verify that tasks are stable...
verify: Waiting 2 seconds to verify that tasks are stable...
verify: Waiting 2 seconds to verify that tasks are stable...
verify: Waiting 2 seconds to verify that tasks are stable...
verify: Waiting 2 seconds to verify that tasks are stable...
verify: Waiting 1 seconds to verify that tasks are stable...
verify: Waiting 1 seconds to verify that tasks are stable...
verify: Waiting 1 seconds to verify that tasks are stable...
verify: Waiting 1 seconds to verify that tasks are stable...
verify: Service converged
----

. Klasterinių servisų sąrašas:
+
----
$ ssh swarm-n01-oam sudo docker service ls
ID             NAME                   MODE         REPLICAS   IMAGE                                PORTS
p7imsxwi9mid   kursinis-web-service   replicated   1/1        katacoda/docker-http-server:latest   *:80->80/tcp
----
+
Veikia, naudoja tik 1 repliką (pagal nutylėjimą).

. Tikrinu servisą lokaliai:
+
----
$ ssh swarm-n01-oam curl -s localhost
<h1>This request was processed by host: 9c2d26cbff9e</h1>
----

. Patikrinu lokalių konteinerių būseną pirmame mazge, veikia lygiai vienas:
+
----
$ ssh swarm-n01-oam sudo docker ps
CONTAINER ID   IMAGE                                COMMAND   CREATED          STATUS          PORTS     NAMES
9c2d26cbff9e   katacoda/docker-http-server:latest   "/app"    34 seconds ago   Up 32 seconds   80/tcp    kursinis-web-service.1.vekfptu7x3egid5me161x4gbj
----

. Serviso pasiekiamumas mazguose:
+
----
$ ssh swarm-n01-oam sudo docker service ps kursinis-web-service
ID             NAME                     IMAGE                                NODE        DESIRED STATE   CURRENT STATE                ERROR     PORTS
vekfptu7x3eg   kursinis-web-service.1   katacoda/docker-http-server:latest   swarm-n01   Running         Running about a minute ago
----
+
Kol kas veikia tik viename mazge.

. Detalus serviso inspektavimas:
+
----
$ ssh swarm-n01-oam sudo docker service inspect kursinis-web-service
[
    {
        "ID": "p7imsxwi9midpu5b378srq54w",
        "Version": {
            "Index": 23
        },
        "CreatedAt": "2022-02-09T09:48:19.22071502Z",
        "UpdatedAt": "2022-02-09T09:48:19.226648699Z",
        "Spec": {
            "Name": "kursinis-web-service",
            "Labels": {},
            "TaskTemplate": {
                "ContainerSpec": {
                    "Image": "katacoda/docker-http-server:latest@sha256:76dc8a47fd019f80f2a3163aba789faf55b41b2fb06397653610c754cb12d3ee",
                    "Init": false,
                    "StopGracePeriod": 10000000000,
                    "DNSConfig": {},
                    "Isolation": "default"
                },
                "Resources": {
                    "Limits": {},
                    "Reservations": {}
                },
                "RestartPolicy": {
                    "Condition": "any",
                    "Delay": 5000000000,
                    "MaxAttempts": 0
                },
                "Placement": {
                    "Platforms": [
                        {
                            "Architecture": "amd64",
                            "OS": "linux"
                        }
                    ]
                },
                "ForceUpdate": 0,
                "Runtime": "container"
            },
            "Mode": {
                "Replicated": {
                    "Replicas": 1
                }
            },
            "UpdateConfig": {
                "Parallelism": 1,
                "FailureAction": "pause",
                "Monitor": 5000000000,
                "MaxFailureRatio": 0,
                "Order": "stop-first"
            },
            "RollbackConfig": {
                "Parallelism": 1,
                "FailureAction": "pause",
                "Monitor": 5000000000,
                "MaxFailureRatio": 0,
                "Order": "stop-first"
            },
            "EndpointSpec": {
                "Mode": "vip",
                "Ports": [
                    {
                        "Protocol": "tcp",
                        "TargetPort": 80,
                        "PublishedPort": 80,
                        "PublishMode": "ingress"
                    }
                ]
            }
        },
        "Endpoint": {
            "Spec": {
                "Mode": "vip",
                "Ports": [
                    {
                        "Protocol": "tcp",
                        "TargetPort": 80,
                        "PublishedPort": 80,
                        "PublishMode": "ingress"
                    }
                ]
            },
            "Ports": [
                {
                    "Protocol": "tcp",
                    "TargetPort": 80,
                    "PublishedPort": 80,
                    "PublishMode": "ingress"
                }
            ],
            "VirtualIPs": [
                {
                    "NetworkID": "vpyp1hp7w63i40yltmydhwl8o",
                    "Addr": "10.0.0.5/24"
                }
            ]
        }
    }
]
----

. Malonesnis skaitymui serviso būsenos pavidalas:
+
----
$ ssh swarm-n01-oam sudo docker service inspect --pretty kursinis-web-service

ID:             p7imsxwi9midpu5b378srq54w
Name:           kursinis-web-service
Service Mode:   Replicated
 Replicas:      1
Placement:
UpdateConfig:
 Parallelism:   1
 On failure:    pause
 Monitoring Period: 5s
 Max failure ratio: 0
 Update order:      stop-first
RollbackConfig:
 Parallelism:   1
 On failure:    pause
 Monitoring Period: 5s
 Max failure ratio: 0
 Rollback order:    stop-first
ContainerSpec:
 Image:         katacoda/docker-http-server:latest@sha256:76dc8a47fd019f80f2a3163aba789faf55b41b2fb06397653610c754cb12d3ee
 Init:          false
Resources:
Endpoint Mode:  vip
Ports:
 PublishedPort = 80
  Protocol = tcp
  TargetPort = 80
  PublishMode = ingress
----

. Servisas lyg veikia.  Tačiau tarp įprastų _Listening_ TCP soketų `80/TCP` nesimato:
+
----
$ ssh swarm-n01-oam ss -4nl
Netid  State   Recv-Q  Send-Q   Local Address:Port    Peer Address:Port Process
udp    UNCONN  0       0        127.0.0.53%lo:53           0.0.0.0:*
udp    UNCONN  0       0              0.0.0.0:631          0.0.0.0:*
udp    UNCONN  0       0              0.0.0.0:4789         0.0.0.0:*
udp    UNCONN  0       0              0.0.0.0:5353         0.0.0.0:*
udp    UNCONN  0       0              0.0.0.0:59148        0.0.0.0:*
tcp    LISTEN  0       4096     127.0.0.53%lo:53           0.0.0.0:*
tcp    LISTEN  0       128            0.0.0.0:22           0.0.0.0:*
tcp    LISTEN  0       5            127.0.0.1:631          0.0.0.0:*
----

. Nuimu _tik_ IPv4 rodymą ir tikrinu iš naujo:
+
----
$ ssh swarm-n02-oam sudo ss -nlp | grep :80
tcp    LISTEN  0        4096                                                  *:80                                                     *:*                       users:(("dockerd",pid=693,fd=25))                
----
+
=> Matyti, jog mano serviso TCP soketą aptarnauja procesas `docker`.

. Peržiūriu tinklo interfeisų sąrašą:
+
----
$ ssh swarm-n01-oam ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: enp0s3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 08:00:27:7e:2a:d2 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global dynamic noprefixroute enp0s3
       valid_lft 82807sec preferred_lft 82807sec
    inet6 fe80::72a6:ed0b:5033:2f37/64 scope link noprefixroute
       valid_lft forever preferred_lft forever
3: enp0s8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 08:00:27:f0:5c:76 brd ff:ff:ff:ff:ff:ff
    inet 10.1.1.24/24 brd 10.1.1.255 scope global dynamic noprefixroute enp0s8
       valid_lft 307sec preferred_lft 307sec
    inet6 fe80::1d12:9739:5544:643a/64 scope link noprefixroute
       valid_lft forever preferred_lft forever
4: enp0s9: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 08:00:27:57:72:bd brd ff:ff:ff:ff:ff:ff
    inet 192.168.56.101/24 brd 192.168.56.255 scope global dynamic noprefixroute enp0s9
       valid_lft 307sec preferred_lft 307sec
    inet6 fe80::e076:cc40:af50:5f45/64 scope link noprefixroute
       valid_lft forever preferred_lft forever
5: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:2f:74:cc:6f brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:2fff:fe74:cc6f/64 scope link
       valid_lft forever preferred_lft forever
10: docker_gwbridge: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 02:42:2c:42:48:68 brd ff:ff:ff:ff:ff:ff
    inet 172.18.0.1/16 brd 172.18.255.255 scope global docker_gwbridge
       valid_lft forever preferred_lft forever
    inet6 fe80::42:2cff:fe42:4868/64 scope link
       valid_lft forever preferred_lft forever
12: vethb5ec981@if11: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker_gwbridge state UP group default
    link/ether 06:3e:2a:e4:2c:55 brd ff:ff:ff:ff:ff:ff link-netnsid 1
    inet6 fe80::43e:2aff:fee4:2c55/64 scope link
       valid_lft forever preferred_lft forever
24: veth3505fba@if23: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker_gwbridge state UP group default
    link/ether 86:1b:0d:15:e5:7b brd ff:ff:ff:ff:ff:ff link-netnsid 2
    inet6 fe80::841b:dff:fe15:e57b/64 scope link
       valid_lft forever preferred_lft forever
----
+
Dabar jis pasipildė dar vienu: `veth*@if23`  +

. Patikrinu serviso pasiekiamumą lokaliai kreipiantis ne į Docker skirtą sisteminį tinklo interfeisą `enp0s8`, bet į OAM dedikuotą interfeisą `enp0s9` su visai kitu IP adresu:
+
----
$ ssh swarm-n01-oam ping 192.168.56.101
PING 192.168.56.101 (192.168.56.101) 56(84) bytes of data.
64 bytes from 192.168.56.101: icmp_seq=1 ttl=64 time=0.051 ms
64 bytes from 192.168.56.101: icmp_seq=2 ttl=64 time=0.083 ms

$ ssh swarm-n01-oam curl -s 192.168.56.101
<h1>This request was processed by host: 9c2d26cbff9e</h1>
----
+
Atsakymą iš serviso vis tiek gaunu.  Kiek netikėta ir malonu.

. Taip pat tikrinu serviso pasiekiamumą OAM interfeisu ir išorėje, ne tik lokaliai:
+
----
$ curl -s 192.168.56.101
<h1>This request was processed by host: 9c2d26cbff9e</h1>

$ curl -s 192.168.56.101
<h1>This request was processed by host: 9c2d26cbff9e</h1>

$ curl -s 192.168.56.101
<h1>This request was processed by host: 9c2d26cbff9e</h1>
----
+
=> Servisas atsiliepia ir Host OSe veikiančiam http-klientui.  Puiku.


{nbsp}

[.text-left]
==== Serviso didinimas (plėtimas)

. Padidinu (išplečiu) servisą iki trijų replikų:
+
----
$ ssh swarm-n01-oam sudo docker service scale kursinis-web-service=3
kursinis-web-service scaled to 3
overall progress: 0 out of 3 tasks
1/3:
2/3:
3/3:
overall progress: 1 out of 3 tasks
overall progress: 1 out of 3 tasks
overall progress: 1 out of 3 tasks
overall progress: 1 out of 3 tasks
overall progress: 1 out of 3 tasks
overall progress: 1 out of 3 tasks
overall progress: 1 out of 3 tasks
overall progress: 1 out of 3 tasks
overall progress: 1 out of 3 tasks
overall progress: 1 out of 3 tasks
overall progress: 1 out of 3 tasks
overall progress: 1 out of 3 tasks
overall progress: 1 out of 3 tasks
overall progress: 1 out of 3 tasks
overall progress: 1 out of 3 tasks
overall progress: 1 out of 3 tasks
overall progress: 1 out of 3 tasks
overall progress: 1 out of 3 tasks
overall progress: 1 out of 3 tasks
overall progress: 1 out of 3 tasks
overall progress: 1 out of 3 tasks
overall progress: 1 out of 3 tasks
overall progress: 1 out of 3 tasks
overall progress: 1 out of 3 tasks
overall progress: 1 out of 3 tasks
overall progress: 1 out of 3 tasks
overall progress: 1 out of 3 tasks
overall progress: 1 out of 3 tasks
overall progress: 1 out of 3 tasks
overall progress: 1 out of 3 tasks
overall progress: 1 out of 3 tasks
overall progress: 1 out of 3 tasks
overall progress: 1 out of 3 tasks
overall progress: 1 out of 3 tasks
overall progress: 1 out of 3 tasks
overall progress: 1 out of 3 tasks
overall progress: 1 out of 3 tasks
overall progress: 1 out of 3 tasks
overall progress: 1 out of 3 tasks
overall progress: 1 out of 3 tasks
overall progress: 1 out of 3 tasks
overall progress: 1 out of 3 tasks
overall progress: 1 out of 3 tasks
overall progress: 1 out of 3 tasks
overall progress: 2 out of 3 tasks
overall progress: 2 out of 3 tasks
overall progress: 2 out of 3 tasks
overall progress: 2 out of 3 tasks
overall progress: 3 out of 3 tasks
verify: Waiting 5 seconds to verify that tasks are stable...
verify: Waiting 5 seconds to verify that tasks are stable...
verify: Waiting 5 seconds to verify that tasks are stable...
verify: Waiting 5 seconds to verify that tasks are stable...
verify: Waiting 5 seconds to verify that tasks are stable...
verify: Waiting 4 seconds to verify that tasks are stable...
verify: Waiting 4 seconds to verify that tasks are stable...
verify: Waiting 4 seconds to verify that tasks are stable...
verify: Waiting 4 seconds to verify that tasks are stable...
verify: Waiting 4 seconds to verify that tasks are stable...
verify: Waiting 3 seconds to verify that tasks are stable...
verify: Waiting 3 seconds to verify that tasks are stable...
verify: Waiting 3 seconds to verify that tasks are stable...
verify: Waiting 3 seconds to verify that tasks are stable...
verify: Waiting 2 seconds to verify that tasks are stable...
verify: Waiting 2 seconds to verify that tasks are stable...
verify: Waiting 2 seconds to verify that tasks are stable...
verify: Waiting 2 seconds to verify that tasks are stable...
verify: Waiting 1 seconds to verify that tasks are stable...
verify: Waiting 1 seconds to verify that tasks are stable...
verify: Waiting 1 seconds to verify that tasks are stable...
verify: Waiting 1 seconds to verify that tasks are stable...
verify: Waiting 1 seconds to verify that tasks are stable...
verify: Service converged
----

. Ir tikrinu serviso pasiekiamumą iš naujo:
+
----
$ curl -s 192.168.56.101
<h1>This request was processed by host: 04bce300bcc1</h1>

$ curl -s 192.168.56.101
<h1>This request was processed by host: 3d80ed3126b6</h1>

$ curl -s 192.168.56.101
<h1>This request was processed by host: 9c2d26cbff9e</h1>

$ curl -s 192.168.56.101
<h1>This request was processed by host: 04bce300bcc1</h1>

$ curl -s 192.168.56.101
<h1>This request was processed by host: 3d80ed3126b6</h1>

$ curl -s 192.168.56.101
<h1>This request was processed by host: 9c2d26cbff9e</h1>

$ curl -s 192.168.56.101
<h1>This request was processed by host: 04bce300bcc1</h1>

$ curl -s 192.168.56.101
<h1>This request was processed by host: 3d80ed3126b6</h1>

$ curl -s 192.168.56.101
<h1>This request was processed by host: 9c2d26cbff9e</h1>
----
+
=> Atsakymuose matyti trys skirtingi Host-id.

. Tikrinu serviso būsenos detales:
+
----
$ ssh swarm-n01-oam sudo docker service inspect --pretty kursinis-web-service

ID:             p7imsxwi9midpu5b378srq54w
Name:           kursinis-web-service
Service Mode:   Replicated
 Replicas:      3
Placement:
UpdateConfig:
 Parallelism:   1
 On failure:    pause
 Monitoring Period: 5s
 Max failure ratio: 0
 Update order:      stop-first
RollbackConfig:
 Parallelism:   1
 On failure:    pause
 Monitoring Period: 5s
 Max failure ratio: 0
 Rollback order:    stop-first
ContainerSpec:
 Image:         katacoda/docker-http-server:latest@sha256:76dc8a47fd019f80f2a3163aba789faf55b41b2fb06397653610c754cb12d3ee
 Init:          false
Resources:
Endpoint Mode:  vip
Ports:
 PublishedPort = 80
  Protocol = tcp
  TargetPort = 80
  PublishMode = ingress

$ ssh swarm-n01-oam sudo docker service ls
ID             NAME                   MODE         REPLICAS   IMAGE                                PORTS
p7imsxwi9mid   kursinis-web-service   replicated   3/3        katacoda/docker-http-server:latest   *:80->80/tcp
----
+
Rodo tris replikas, kaip ir nurodžiau plėsdamas.

. Tikrinu pavienius konteinerius:
+
----
$ ssh swarm-n01-oam sudo docker ps
CONTAINER ID   IMAGE                                COMMAND   CREATED         STATUS         PORTS     NAMES
9c2d26cbff9e   katacoda/docker-http-server:latest   "/app"    7 minutes ago   Up 7 minutes   80/tcp    kursinis-web-service.1.vekfptu7x3egid5me161x4gbj

$ ssh swarm-n02-oam sudo docker ps
CONTAINER ID   IMAGE                                COMMAND   CREATED              STATUS              PORTS     NAMES
04bce300bcc1   katacoda/docker-http-server:latest   "/app"    About a minute ago   Up About a minute   80/tcp    kursinis-web-service.2.y8zkkc2pgpj6q0rijb372wooo

$ ssh swarm-n03-oam sudo docker ps
CONTAINER ID   IMAGE                                COMMAND   CREATED              STATUS              PORTS     NAMES
3d80ed3126b6   katacoda/docker-http-server:latest   "/app"    About a minute ago   Up About a minute   80/tcp    kursinis-web-service.3.f7aekzcbukx3c8bjojsl2v4i1
----
+
=> Konteinerių ID atitinka http-atsakymuose matomus Hostų id.

. Dabartinis paslaugos pasiekiamumas klasteryje pagal _Manager_:
+
----
$ ssh swarm-n01-oam sudo docker service ps kursinis-web-service
ID             NAME                     IMAGE                                NODE        DESIRED STATE   CURRENT STATE            ERROR     PORTS
vekfptu7x3eg   kursinis-web-service.1   katacoda/docker-http-server:latest   swarm-n01   Running         Running 21 minutes ago
y8zkkc2pgpj6   kursinis-web-service.2   katacoda/docker-http-server:latest   swarm-n02   Running         Running 14 minutes ago
f7aekzcbukx3   kursinis-web-service.3   katacoda/docker-http-server:latest   swarm-n03   Running         Running 14 minutes ago
----
+
=> Kiekvienam klasterio mazge veikia po vieną serviso egzempliorių (kopiją, repliką).

. Išorės užklausų siuntimas į pirmą mazgą:
+
----
$ curl -s swarm-n01-oam
<h1>This request was processed by host: 04bce300bcc1</h1>

$ curl -s swarm-n01-oam
<h1>This request was processed by host: 3d80ed3126b6</h1>

$ curl -s swarm-n01-oam
<h1>This request was processed by host: 9c2d26cbff9e</h1>

$ curl -s swarm-n01-oam
<h1>This request was processed by host: 04bce300bcc1</h1>
----
+
Atsako trys skirtingi konteineriai.

. Išorės užklausų siuntimas į antrą mazgą:
+
----
$ curl -s swarm-n02-oam
<h1>This request was processed by host: 04bce300bcc1</h1>

$ curl -s swarm-n02-oam
<h1>This request was processed by host: 3d80ed3126b6</h1>

$ curl -s swarm-n02-oam
<h1>This request was processed by host: 9c2d26cbff9e</h1>

$ curl -s swarm-n02-oam
<h1>This request was processed by host: 04bce300bcc1</h1>

$ curl -s swarm-n02-oam
<h1>This request was processed by host: 3d80ed3126b6</h1>
----
+
Atsako trys tie patys skirtingi konteineriai.

. Išorės užklausų siuntimas į trečią mazgą:
+
----
$ curl -s swarm-n03-oam
<h1>This request was processed by host: 04bce300bcc1</h1>

$ curl -s swarm-n03-oam
<h1>This request was processed by host: 3d80ed3126b6</h1>

$ curl -s swarm-n03-oam
<h1>This request was processed by host: 9c2d26cbff9e</h1>

$ curl -s swarm-n03-oam
<h1>This request was processed by host: 04bce300bcc1</h1>

$ curl -s swarm-n03-oam
<h1>This request was processed by host: 3d80ed3126b6</h1>

$ curl -s swarm-n03-oam
<h1>This request was processed by host: 9c2d26cbff9e</h1>

$ curl -s swarm-n03-oam
<h1>This request was processed by host: 04bce300bcc1</h1>

$ curl -s swarm-n03-oam
<h1>This request was processed by host: 3d80ed3126b6</h1>

$ curl -s swarm-n03-oam
<h1>This request was processed by host: 9c2d26cbff9e</h1>

$ curl -s swarm-n03-oam
<h1>This request was processed by host: 04bce300bcc1</h1>

$ curl -s swarm-n03-oam
<h1>This request was processed by host: 3d80ed3126b6</h1>

$ curl -s swarm-n03-oam
<h1>This request was processed by host: 9c2d26cbff9e</h1>
----
+
Atsako vėl tie patys trys konteineriai.
+
=> Paslauga veikia trijuose mazguose, visame klasteryje.


{nbsp}

[.text-left]
==== Klasterio elemento gedimas ir įtaka

* Imituoti vieno iš klasterio elementų gedimą;
  aprašyti / parodyti poveikį servisams.


{nbsp}

[.text-left]
==== _Web_-serviso pasiekiamumas įvairiuose etapuose

* Parodyti / atvaizduoti _Web_-serviso pasiekiamumą visuose etapuose.


{nbsp}

=== 3. Rezultatų apibendrinimas
[.text-left]
==== {nbsp}

Susikonstravau VM infrastruktūrą VirtuaBox hipervizoriaus (Type II) pagrindu.
Kiekvienai VM skyriau po tris tinklo interfeisus:

. prisijungimui prie interneto (atnaujinimų siuntimams ir kt.)
. aplikacijai / klasterio mazgų ryšiui;
. OS valdymui (OAM).

Sukūriau tris VM, jose pasinaudojau _Docker Swarm Mode_ technologija ir startavau trijų mazgų klasterį:

. _Manager + Worker_;
. _Worker_;
. _Worker_.

Klasteryje _Docker_ konteinerių pagrindu paleidau savo pasirinktą _Web_-servisą `katacoda/docker-http-server`.  Patikrinau jį iš savo kompiuterio: pasiekiamas.

Sukūriau tris serviso replikas.  Patikrinau ir užfiksavau jų pasiskirstymą klasteryje.

Imitavau klasterio elemento gedimą: atjungiau pirmojo mazgo `swarm-n01` klasterinį tinklo interfeisą.

_Manager_ nustojo matyti likusius du mazgus ir perkūrė du jų konteinerius pas save.  Bėda, kad jis pats būtų tapęs nepasiekiamu produkciniam tinklui (NLB ar maršrutizatoriui).  Tačiau per OAM interfeisą visi trys konteineriai buvo pasiekiami.

Tuo tarpu mazgai `swarm-n02` ir `swarm-n03` iškart nustojo atsiliepti į užklausas `80/TCP` portu iš viso, nors jų klasteriniai interfeisai ir tebeveikė.

Po <20 s. jų atsakymai į užklausas atsistatė -- jie jas pradėjo balansuoti tarpusavyje ir grąžindavo jau du skirtingus _Host-id_.

Iš esmės, situacija mano vertinimu atitinka klasterinį _Split-brain_ scenarijų, kai abi klasterio dalys nusprendžia, kad kita pusė nebeveikia, ir bando veikti abi nepriklausomai.

* => Darau išvadą, kad klasteriui paskyrus tiek nedaug mazgų, vertėtų padidinti ne tik _Worker_ skaičių, bet ir _Manager_ skaičių.
+
Priešingu atveju įmanomas pavojus duomenų vientisumui, kai dvi grupės vienu metu keis tuos pačius duomenis, bet kiekviena laikys, kad keičia tik ji pati, tik viena grupė.

Toliau atstačiau tinklo veikimą, ir stebėjau konteinerių būsenas tiek _Worker_ mazguose, tiek _Manager_ mazge.
Netrukus jie pradėjo atsakymuose grąžinti naujus _Host-id_.

Patikrinus pasirodė, kad visi šie _Host-id_ priklauso `swarm-n01` mazge veikiantiems dviems naujiems konteineriams, sukurtiems splito metu.
Ir dabar šiaip paslaugai visos trys replikos veikė būtent šiame mazge.
Konteineriai _Worker_ mazguose išsijungė netrukus po _Manager_ tinklo atstatymo.

Po šito paskirsčiau replikas vėl po lygiai -- po vieną kiekvienam mazgui: `... scale kursinis-web-service=1` ir  `... scale kursinis-web-service=3`.

Ir kai tuo tarpu pilnai išjungiau antrą mazgą, `swarm-n02`, jo replika buvo pakeista nauja replika pirmajame mazge, `swarm-n01`.

Į užklausas abu tebeveikiantys mazgai atsakydavo sėkmingai (`swarm-n01` ir `swarm-n03`).

Mazgą `swarm-n02` vėl įjungus, jis pats sugrįžo į klasterį, tačiau veikiančios replikos pasiliko savo dabartiniuose mazguose (dvi `swarm-n01` ir viena `swarm-n03`).

O štai užklausos į servisą pradėjo veikti jau ir per antrąjį mazgą -- sugrįžęs į klasterį jis įsitraukė į _Routing mesh_ ir _Load-balancing_ mechanizmą.

* => Jei gedimas įvyksta _Worker_ mazge, o ne _Manager_, įtaka paslaugai beveik nejuntama.
+
Paslaugos replikų skaičius atstatomas (sukuriamos trūkstamosios) ilgiausiai po ~ 5 s.


{nbsp}

=== 4. Naudota literatūra
[.text-left]
==== {nbsp}

**[[[1]]]** https://www.osboxes.org/ubuntu/#ubuntu-20-04-3-info[OSboxes > VirtualBox Images > Ubuntu > Ubuntu 20.04.3 Focal Fossa]


https://docs.docker.com/engine/swarm/swarm-tutorial/[Docker docs {nbsp} > {nbsp} Run your app in production {nbsp} > {nbsp} Getting started with swarm mode (tutorial)]

https://www.katacoda.com/courses/docker-orchestration[Learn Docker Orchestration / Swarm Mode using Interactive Browser-Based Scenarios]

https://www.katacoda.com/courses/docker-orchestration/getting-started-with-swarm-mode[Getting Started With Swarm Mode]

https://www.katacoda.com/courses/docker-orchestration/create-overlay-networks[Create Overlay Network]

https://www.katacoda.com/courses/docker-orchestration/load-balance-service-discovery-swarm-mode[Load Balance and Service Discover in Swarm Mode]

https://www.katacoda.com/courses/docker-orchestration/rolling-updates-services-swarm-cluster[Apply Rolling Updates Across Swarm Cluster]

https://www.katacoda.com/courses/docker-orchestration/healthcheck[Add Healthcheck for Containers]

https://www.katacoda.com/courses/docker-orchestration/deploy-swarm-services-with-compose[Deploy Swarm Services with Compose v3]

https://www.katacoda.com/courses/docker-orchestration/maintenance-mode-for-swarm[Enable Maintenance Mode for a Swarm Node]

https://blog.jayway.com/2015/11/25/simple-clustering-with-docker-swarm-and-nginx/[Simple Clustering with Docker Swarm and Nginx]


{nbsp}

<<<

=== 5. Priedai
[.text-left]

(Schemos, kodas)

