= {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}Vilniaus Gedimino technikos universitetas

[.text-center]
== Elektronikos fakultetas

=== Kompiuterijos ir ryšių technologijų katedra

{nbsp}

{nbsp}

{nbsp}

{nbsp}

{nbsp}

{nbsp}

=== Debesų kompiuterija
Modulis ELKRM17304

[.text-center]
== Automatizavimas Ansible pagalba

Laboratorinio darbo nr. 4 ataskaita

{nbsp}

{nbsp}

{nbsp}

{nbsp}

{nbsp}

{nbsp}

[.text-right]
**Atliko:** TETfm-20 grupės magistrantas +
                       Saulius Krasuckas +
**Tikrino:** lekt. dr. Liudas Duoba

{nbsp}

{nbsp}

{nbsp}

{nbsp}

{nbsp}

{nbsp}

{nbsp}

VILNIUS, 2022

<<<



{nbsp}

[.text-center]
===== Laboratorinis darbas nr. 4

[.text-center]
== Automatizavimas `Ansible` pagalba


{nbsp}

[.text-center]
== Darbo tikslas

[.text-left]
* Išbandyti `Ansible` įrankį.


[.text-center]
== Darbo eiga


[.text-left]
=== Infrastruktūros paruošimas

Šiuo metu KDV naudoju _Windows 10_.
Darbui atlikti pasirinkau terminalo emuliatorių _MinTTY_ ir CLI įrankių sistemą _MSYS2_.  +
Pastaroji Windows OS emuliuoja *nix aplinką.  <<1>>


===== Prisijungimas prie savo **serverio nr. 1**

Kol laukiau SSH paslaugos pasiekiamumo, tikrinau nurodytą TCP prievadą.
Prisiminiau ir išmėginau kelis būdus:

----
$ ssh 158.129.200.236 45522
ssh: connect to host 158.129.200.236 port 22: Connection timed out
$ 
----


----
$ telnet 158.129.200.236 45522
Trying 158.129.200.236...
^C
$ 
----


----
$ ssh ssh://stud@158.129.200.236:45522
^C
$ 
----

Išskyrus tikrinimą `netcat` įrankiu, kurį savo klientinėje OS spėjau _tik įsidiegti_:

----
$ pacman -S openbsd-netcat
resolving dependencies...
looking for conflicting packages...
Packages (1) openbsd-netcat-1.217_2-1
Total Download Size:   0.03 MiB
Total Installed Size:  0.12 MiB

:: Proceed with installation? [Y/n]
:: Retrieving packages...
 openbsd-netcat-1.217_2-1-x86_64                                             35.4 KiB  37.8 KiB/s 00:01 [#############################################################] 100% 
(1/1) checking keys in keyring                                                                          [#############################################################] 100% 
(1/1) checking package integrity                                                                        [#############################################################] 100% 
(1/1) loading package files                                                                             [#############################################################] 100% 
(1/1) checking for file conflicts                                                                       [#############################################################] 100% 
(1/1) checking available disk space                                                                     [#############################################################] 100% 
:: Processing package changes...                                                                                                                                             
(1/1) installing openbsd-netcat                                                                         [#############################################################] 100%
$ 
----

Tuomet laboratorinė SSH paslauga tapo jau pasiekiama..:

----
$ telnet 158.129.200.236 45522
Trying 158.129.200.236...
Connected to 158.129.200.236.
Escape character is '^]'.
SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.3
^]

Connection closed by foreign host.
$ 
----

{nbsp}... ir pagaliau prisijungiau prie serverio nr.1:

----
$ ssh ssh://stud@158.129.200.236:45522
stud@158.129.200.236's password:
Welcome to Ubuntu 20.04.3 LTS (GNU/Linux 5.4.0-90-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Tue 07 Dec 2021 04:31:42 PM UTC

  System load:  0.0                Processes:                229
  Usage of /:   41.0% of 19.56GB   Users logged in:          0
  Memory usage: 9%                 IPv4 address for docker0: 172.17.0.1
  Swap usage:   0%                 IPv4 address for ens160:  10.128.67.8

 * Super-optimized for small spaces - read how we shrank the memory
   footprint of MicroK8s to make it the smallest full K8s around.

   https://ubuntu.com/blog/microk8s-memory-optimisation

41 updates can be applied immediately.
To see these additional updates run: apt list --upgradable


The list of available updates is more than a week old.
To check for new updates run: sudo apt update

Last login: Tue Oct 19 19:27:21 2021 from 81.29.22.28
stud@cc-lab:~$ 
----


===== Gauto OS atnaujinimas:

----
stud@cc-lab:~$ id
uid=1001(stud) gid=1001(stud) groups=1001(stud),27(sudo)

stud@cc-lab:~$ sudo apt update
[sudo] password for stud:
Hit:1 http://lt.archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://lt.archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:3 http://lt.archive.ubuntu.com/ubuntu focal-backports InRelease
Hit:4 http://lt.archive.ubuntu.com/ubuntu focal-security InRelease
Reading package lists... Done
Building dependency tree
Reading state information... Done
43 packages can be upgraded. Run 'apt list --upgradable' to see them.
stud@cc-lab:~$ 
----


===== _Ansible_ įdiegimas:

----
stud@cc-lab:~$ sudo apt install ansible
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  ieee-data python3-argcomplete python3-crypto python3-dnspython python3-jmespath python3-kerberos python3-libcloud python3-lockfile python3-netaddr python3-ntlm-auth
  python3-requests-kerberos python3-requests-ntlm python3-selinux python3-winrm python3-xmltodict
Suggested packages:
  cowsay sshpass python-lockfile-doc ipython3 python-netaddr-docs
The following NEW packages will be installed:
  ansible ieee-data python3-argcomplete python3-crypto python3-dnspython python3-jmespath python3-kerberos python3-libcloud python3-lockfile python3-netaddr
  python3-ntlm-auth python3-requests-kerberos python3-requests-ntlm python3-selinux python3-winrm python3-xmltodict
0 upgraded, 16 newly installed, 0 to remove and 43 not upgraded.
Need to get 9,644 kB of archives.
After this operation, 90.2 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://lt.archive.ubuntu.com/ubuntu focal/main amd64 python3-crypto amd64 2.6.1-13ubuntu2 [237 kB]
Get:2 http://lt.archive.ubuntu.com/ubuntu focal/main amd64 python3-dnspython all 1.16.0-1build1 [89.1 kB]
Get:3 http://lt.archive.ubuntu.com/ubuntu focal/main amd64 ieee-data all 20180805.1 [1,589 kB]
Get:4 http://lt.archive.ubuntu.com/ubuntu focal-updates/main amd64 python3-netaddr all 0.7.19-3ubuntu1 [236 kB]
Get:5 http://lt.archive.ubuntu.com/ubuntu focal/universe amd64 ansible all 2.9.6+dfsg-1 [5,794 kB]
Get:6 http://lt.archive.ubuntu.com/ubuntu focal/universe amd64 python3-argcomplete all 1.8.1-1.3ubuntu1 [27.2 kB]
Get:7 http://lt.archive.ubuntu.com/ubuntu focal-updates/main amd64 python3-jmespath all 0.9.4-2ubuntu1 [21.5 kB]
Get:8 http://lt.archive.ubuntu.com/ubuntu focal/universe amd64 python3-kerberos amd64 1.1.14-3.1build1 [22.6 kB]
Get:9 http://lt.archive.ubuntu.com/ubuntu focal/main amd64 python3-lockfile all 1:0.12.2-2ubuntu2 [14.6 kB]
Get:10 http://lt.archive.ubuntu.com/ubuntu focal/universe amd64 python3-libcloud all 2.8.0-1 [1,403 kB]
Get:11 http://lt.archive.ubuntu.com/ubuntu focal/universe amd64 python3-ntlm-auth all 1.1.0-1 [19.6 kB]
Get:12 http://lt.archive.ubuntu.com/ubuntu focal/universe amd64 python3-requests-kerberos all 0.12.0-2 [11.9 kB]
Get:13 http://lt.archive.ubuntu.com/ubuntu focal/universe amd64 python3-requests-ntlm all 1.1.0-1 [6,004 B]
Get:14 http://lt.archive.ubuntu.com/ubuntu focal/universe amd64 python3-selinux amd64 3.0-1build2 [139 kB]
Get:15 http://lt.archive.ubuntu.com/ubuntu focal/universe amd64 python3-xmltodict all 0.12.0-1 [12.6 kB]
Get:16 http://lt.archive.ubuntu.com/ubuntu focal/universe amd64 python3-winrm all 0.3.0-2 [21.7 kB]
Fetched 9,644 kB in 1s (10.9 MB/s)
Selecting previously unselected package python3-crypto.
(Reading database ... 107888 files and directories currently installed.)
Preparing to unpack .../00-python3-crypto_2.6.1-13ubuntu2_amd64.deb ...
Unpacking python3-crypto (2.6.1-13ubuntu2) ...
Selecting previously unselected package python3-dnspython.
Preparing to unpack .../01-python3-dnspython_1.16.0-1build1_all.deb ...
Unpacking python3-dnspython (1.16.0-1build1) ...
Selecting previously unselected package ieee-data.
Preparing to unpack .../02-ieee-data_20180805.1_all.deb ...
Unpacking ieee-data (20180805.1) ...

Progress: [  8%] [###########............................................................................................................................................]

Selecting previously unselected package python3-netaddr.
Preparing to unpack .../03-python3-netaddr_0.7.19-3ubuntu1_all.deb ...
Unpacking python3-netaddr (0.7.19-3ubuntu1) ...
Selecting previously unselected package ansible.
Preparing to unpack .../04-ansible_2.9.6+dfsg-1_all.deb ...
Unpacking ansible (2.9.6+dfsg-1) ...
Selecting previously unselected package python3-argcomplete.
Preparing to unpack .../05-python3-argcomplete_1.8.1-1.3ubuntu1_all.deb ...
Unpacking python3-argcomplete (1.8.1-1.3ubuntu1) ...
Selecting previously unselected package python3-jmespath.
Preparing to unpack .../06-python3-jmespath_0.9.4-2ubuntu1_all.deb ...
Unpacking python3-jmespath (0.9.4-2ubuntu1) ...
Selecting previously unselected package python3-kerberos.
Preparing to unpack .../07-python3-kerberos_1.1.14-3.1build1_amd64.deb ...
Unpacking python3-kerberos (1.1.14-3.1build1) ...
Selecting previously unselected package python3-lockfile.
Preparing to unpack .../08-python3-lockfile_1%3a0.12.2-2ubuntu2_all.deb ...
Unpacking python3-lockfile (1:0.12.2-2ubuntu2) ...
Selecting previously unselected package python3-libcloud.
Preparing to unpack .../09-python3-libcloud_2.8.0-1_all.deb ...
Unpacking python3-libcloud (2.8.0-1) ...
Selecting previously unselected package python3-ntlm-auth.
Preparing to unpack .../10-python3-ntlm-auth_1.1.0-1_all.deb ...
Unpacking python3-ntlm-auth (1.1.0-1) ...
Selecting previously unselected package python3-requests-kerberos.
Preparing to unpack .../11-python3-requests-kerberos_0.12.0-2_all.deb ...
Unpacking python3-requests-kerberos (0.12.0-2) ...
Selecting previously unselected package python3-requests-ntlm.
Preparing to unpack .../12-python3-requests-ntlm_1.1.0-1_all.deb ...
Unpacking python3-requests-ntlm (1.1.0-1) ...
Selecting previously unselected package python3-selinux.
Preparing to unpack .../13-python3-selinux_3.0-1build2_amd64.deb ...
Unpacking python3-selinux (3.0-1build2) ...
Selecting previously unselected package python3-xmltodict.
Preparing to unpack .../14-python3-xmltodict_0.12.0-1_all.deb ...
Unpacking python3-xmltodict (0.12.0-1) ...
Selecting previously unselected package python3-winrm.
Preparing to unpack .../15-python3-winrm_0.3.0-2_all.deb ...
Unpacking python3-winrm (0.3.0-2) ...
Setting up python3-lockfile (1:0.12.2-2ubuntu2) ...
Setting up python3-ntlm-auth (1.1.0-1) ...
Setting up python3-kerberos (1.1.14-3.1build1) ...
Setting up python3-xmltodict (0.12.0-1) ...
Setting up python3-jmespath (0.9.4-2ubuntu1) ...
Setting up python3-requests-kerberos (0.12.0-2) ...
Setting up ieee-data (20180805.1) ...
Setting up python3-dnspython (1.16.0-1build1) ...
Setting up python3-selinux (3.0-1build2) ...
Setting up python3-crypto (2.6.1-13ubuntu2) ...
Setting up python3-argcomplete (1.8.1-1.3ubuntu1) ...
Setting up python3-requests-ntlm (1.1.0-1) ...
Setting up python3-libcloud (2.8.0-1) ...
Setting up python3-netaddr (0.7.19-3ubuntu1) ...
Setting up python3-winrm (0.3.0-2) ...
Setting up ansible (2.9.6+dfsg-1) ...
Processing triggers for man-db (2.9.1-1) ...
stud@cc-lab:~$ 
----

Tikrinu _Ansible_ versiją:

----
stud@cc-lab:~$ ansible --version
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/stud/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Sep 28 2021, 16:10:42) [GCC 9.3.0]
stud@cc-lab:~$ 
----

* => _Ansible_ įdiegtas.


===== Ryšio tarp serverių tikrinimas ir pradinis aprašymas

Patikrinu kai kuriuos serverio nr. 1 IP nustatymus:

----
stud@cc-lab:~$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: ens160: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:50:56:9a:28:de brd ff:ff:ff:ff:ff:ff
    inet 10.128.67.8/24 brd 10.128.67.255 scope global ens160
       valid_lft forever preferred_lft forever
    inet6 fe80::250:56ff:fe9a:28de/64 scope link
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:5b:81:0f:4a brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever

stud@cc-lab:~$ ip r
default via 10.128.67.254 dev ens160 proto dhcp src 10.128.67.8 metric 100
10.128.67.0/24 dev ens160 proto kernel scope link src 10.128.67.8
10.128.67.254 dev ens160 proto dhcp scope link src 10.128.67.8 metric 100
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown
stud@cc-lab:~$ 
----

Ieškau „kaimynų“ (serverio nr. 2) su sniferiu:

----
stud@cc-lab:~$ sudo tcpdump -tni ens160 not tcp port 22
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on ens160, link-type EN10MB (Ethernet), capture size 262144 bytes

ARP, Request who-has 10.128.67.14 tell 10.128.67.6, length 46
ARP, Request who-has 10.128.67.14 tell 10.128.67.6, length 46
ARP, Request who-has 10.128.67.14 tell 10.128.67.6, length 46
ARP, Request who-has 10.128.67.14 tell 10.128.67.6, length 46
ARP, Request who-has 10.128.67.14 tell 10.128.67.6, length 46
ARP, Request who-has 10.128.67.14 tell 10.128.67.6, length 46
ARP, Request who-has 10.128.67.14 tell 10.128.67.6, length 46
ARP, Request who-has 10.128.67.14 tell 10.128.67.6, length 46
ARP, Request who-has 10.128.67.14 tell 10.128.67.6, length 46
LLDP, length 338: sw-rlab-301-top
ARP, Request who-has 10.128.67.14 tell 10.128.67.6, length 46
ARP, Request who-has 10.128.67.14 tell 10.128.67.6, length 46
ARP, Request who-has 10.128.67.14 tell 10.128.67.6, length 46
ARP, Request who-has 10.128.67.14 tell 10.128.67.6, length 46
ARP, Request who-has 10.128.67.14 tell 10.128.67.6, length 46
ARP, Request who-has 10.128.67.14 tell 10.128.67.6, length 46
ARP, Request who-has 10.128.67.14 tell 10.128.67.6, length 46
ARP, Request who-has 10.128.67.14 tell 10.128.67.6, length 46
ARP, Request who-has 10.128.67.14 tell 10.128.67.6, length 46
ARP, Request who-has 10.128.67.14 tell 10.128.67.6, length 46
ARP, Request who-has 10.128.67.14 tell 10.128.67.6, length 46
ARP, Request who-has 10.128.67.14 tell 10.128.67.6, length 46
ARP, Request who-has 10.128.67.14 tell 10.128.67.6, length 46
ARP, Request who-has 10.128.67.14 tell 10.128.67.6, length 46
ARP, Request who-has 10.128.67.14 tell 10.128.67.6, length 46
ARP, Request who-has 10.128.67.14 tell 10.128.67.6, length 46
ARP, Request who-has 10.128.67.14 tell 10.128.67.6, length 46
ARP, Request who-has 10.128.67.14 tell 10.128.67.6, length 46
ARP, Request who-has 10.128.67.13 tell 10.128.67.5, length 46
ARP, Request who-has 10.128.67.14 tell 10.128.67.6, length 46
ARP, Request who-has 10.128.67.13 tell 10.128.67.5, length 46
ARP, Request who-has 10.128.67.14 tell 10.128.67.6, length 46
ARP, Request who-has 10.128.67.13 tell 10.128.67.5, length 46
ARP, Request who-has 10.128.67.14 tell 10.128.67.6, length 46
ARP, Request who-has 10.128.67.13 tell 10.128.67.5, length 46
ARP, Request who-has 10.128.67.14 tell 10.128.67.6, length 46
ARP, Request who-has 10.128.67.13 tell 10.128.67.5, length 46
ARP, Request who-has 10.128.67.14 tell 10.128.67.6, length 46
ARP, Request who-has 10.128.67.13 tell 10.128.67.5, length 46
ARP, Request who-has 10.128.67.14 tell 10.128.67.6, length 46
ARP, Request who-has 10.128.67.14 tell 10.128.67.6, length 46
ARP, Request who-has 10.128.67.12 tell 10.128.67.5, length 46
ARP, Request who-has 10.128.67.14 tell 10.128.67.6, length 46
ARP, Request who-has 10.128.67.14 tell 10.128.67.6, length 46
ARP, Request who-has 10.128.67.14 tell 10.128.67.6, length 46
LLDP, length 338: sw-rlab-301-top
ARP, Request who-has 10.128.67.14 tell 10.128.67.6, length 46
ARP, Request who-has 10.128.67.14 tell 10.128.67.6, length 46
ARP, Request who-has 10.128.67.14 tell 10.128.67.6, length 46
ARP, Request who-has 10.128.67.14 tell 10.128.67.6, length 46
ARP, Request who-has 10.128.67.14 tell 10.128.67.6, length 46
ARP, Request who-has 10.128.67.14 tell 10.128.67.6, length 46
^C
52 packets captured
52 packets received by filter
0 packets dropped by kernel
stud@cc-lab:~$ 
----

* => „Kaimynai“ tyli.

Diegiu tinklo skenerį:

----
stud@cc-lab:~$ sudo apt install nmap
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  libblas3 liblinear4 liblua5.3-0 lua-lpeg nmap-common
Suggested packages:
  liblinear-tools liblinear-dev ncat ndiff zenmap
The following NEW packages will be installed:
  libblas3 liblinear4 liblua5.3-0 lua-lpeg nmap nmap-common
0 upgraded, 6 newly installed, 0 to remove and 43 not upgraded.
Need to get 5,669 kB of archives.
After this operation, 26.8 MB of additional disk space will be used.
Do you want to continue? [Y/n]
Get:1 http://lt.archive.ubuntu.com/ubuntu focal/main amd64 libblas3 amd64 3.9.0-1build1 [142 kB]
Get:2 http://lt.archive.ubuntu.com/ubuntu focal/universe amd64 liblinear4 amd64 2.3.0+dfsg-3build1 [41.7 kB]
Get:3 http://lt.archive.ubuntu.com/ubuntu focal/main amd64 liblua5.3-0 amd64 5.3.3-1.1ubuntu2 [116 kB]
Get:4 http://lt.archive.ubuntu.com/ubuntu focal/universe amd64 lua-lpeg amd64 1.0.2-1 [31.4 kB]
Get:5 http://lt.archive.ubuntu.com/ubuntu focal/universe amd64 nmap-common all 7.80+dfsg1-2build1 [3,676 kB]
Get:6 http://lt.archive.ubuntu.com/ubuntu focal/universe amd64 nmap amd64 7.80+dfsg1-2build1 [1,662 kB]
Fetched 5,669 kB in 3s (1,860 kB/s)
Selecting previously unselected package libblas3:amd64.
(Reading database ... 117331 files and directories currently installed.)
Preparing to unpack .../0-libblas3_3.9.0-1build1_amd64.deb ...
Unpacking libblas3:amd64 (3.9.0-1build1) ...
Selecting previously unselected package liblinear4:amd64.
Preparing to unpack .../1-liblinear4_2.3.0+dfsg-3build1_amd64.deb ...
Unpacking liblinear4:amd64 (2.3.0+dfsg-3build1) ...
Selecting previously unselected package liblua5.3-0:amd64.
Preparing to unpack .../2-liblua5.3-0_5.3.3-1.1ubuntu2_amd64.deb ...
Unpacking liblua5.3-0:amd64 (5.3.3-1.1ubuntu2) ...
Selecting previously unselected package lua-lpeg:amd64.
Preparing to unpack .../3-lua-lpeg_1.0.2-1_amd64.deb ...
Unpacking lua-lpeg:amd64 (1.0.2-1) ...
Selecting previously unselected package nmap-common.
Preparing to unpack .../4-nmap-common_7.80+dfsg1-2build1_all.deb ...
Unpacking nmap-common (7.80+dfsg1-2build1) ...
Selecting previously unselected package nmap.
Preparing to unpack .../5-nmap_7.80+dfsg1-2build1_amd64.deb ...
Unpacking nmap (7.80+dfsg1-2build1) ...
Setting up lua-lpeg:amd64 (1.0.2-1) ...
Setting up libblas3:amd64 (3.9.0-1build1) ...
update-alternatives: using /usr/lib/x86_64-linux-gnu/blas/libblas.so.3 to provide /usr/lib/x86_64-linux-gnu/libblas.so.3 (libblas.so.3-x86_64-linux-gnu) in auto mode
Setting up nmap-common (7.80+dfsg1-2build1) ...
Setting up liblua5.3-0:amd64 (5.3.3-1.1ubuntu2) ...
Setting up liblinear4:amd64 (2.3.0+dfsg-3build1) ...
Setting up nmap (7.80+dfsg1-2build1) ...

Progress: [ 88%] [####################################################################################################################################...................]

Processing triggers for man-db (2.9.1-1) ...
Processing triggers for libc-bin (2.31-0ubuntu9.2) ...
stud@cc-lab:~$ 
----

Ir ieškau jų skenuodamas duotą vidinį potinklį:

----
stud@cc-lab:~$ ip a | awk '/inet/'
    inet 127.0.0.1/8 scope host lo
    inet 10.128.67.8/24 brd 10.128.67.255 scope global ens160
    inet6 fe80::250:56ff:fe9a:28de/64 scope link
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0

stud@cc-lab:~$ sudo nmap -sP 10.128.67.8/24
Starting Nmap 7.80 ( https://nmap.org ) at 2021-12-07 16:44 UTC
Nmap scan report for 10.128.67.3
Host is up (0.00025s latency).
MAC Address: 00:50:56:9A:2F:79 (VMware)
Nmap scan report for 10.128.67.4
Host is up (0.00017s latency).
MAC Address: 00:50:56:9A:D3:7C (VMware)
Nmap scan report for 10.128.67.5
Host is up (0.00016s latency).
MAC Address: 00:50:56:9A:FD:C6 (VMware)
Nmap scan report for 10.128.67.6
Host is up (0.00016s latency).
MAC Address: 00:50:56:9A:04:4E (VMware)
Nmap scan report for 10.128.67.9
Host is up (0.00023s latency).
MAC Address: 00:50:56:9A:B7:C7 (VMware)
Nmap scan report for 10.128.67.10
Host is up (0.00017s latency).
MAC Address: 00:50:56:9A:2A:F0 (VMware)
Nmap scan report for 10.128.67.11
Host is up (0.00016s latency).
MAC Address: 00:50:56:9A:BD:36 (VMware)
Nmap scan report for 10.128.67.12
Host is up (0.00011s latency).
MAC Address: 00:50:56:9A:5A:91 (VMware)
Nmap scan report for cc-lab (10.128.67.8)
Host is up.
Nmap done: 256 IP addresses (9 hosts up) scanned in 1.82 seconds
stud@cc-lab:~$ 
----

* => Radau aštuonis kaimynus, turbūt grupiokų serverius nr. 1.

* => Kol neaišku, kuris IP kam priklauso, treniruosiuosi su savo serveriu `10.128.67.8` kaip pagrindiniu taikiniu.

Tikrinu `/etc/hosts` failo formatą ir turinį:

----
stud@cc-lab:~$ tail /etc/hosts
127.0.0.1 localhost
127.0.1.1 cc-lab

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
stud@cc-lab:~$ 
----

Aprašau jame savo serverį nr. 1, tik vardu `serveris2`:

----
stud@cc-lab:~$ echo '10.128.67.8    serveris2' >> /etc/hosts
-bash: /etc/hosts: Permission denied

stud@cc-lab:~$ echo '10.128.67.8    serveris2' | sudo tee -a /etc/hosts
10.128.67.8    serveris2

stud@cc-lab:~$ tail /etc/hosts
127.0.0.1 localhost
127.0.1.1 cc-lab

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
10.128.67.8    serveris2
stud@cc-lab:~$ 
----

Patikrinu vardo išsprendimą:

----
stud@cc-lab:~$ ping serveris2
PING serveris2 (10.128.67.8) 56(84) bytes of data.
64 bytes from serveris2 (10.128.67.8): icmp_seq=1 ttl=64 time=0.084 ms
64 bytes from serveris2 (10.128.67.8): icmp_seq=2 ttl=64 time=0.053 ms
^C
--- serveris2 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1016ms
rtt min/avg/max/mdev = 0.053/0.068/0.084/0.015 ms
stud@cc-lab:~$ 
----

* => Laikinas vardas veikia.


===== SSH ryšio ir rakto paruošimas

Darbo su SSH raktais prisiminimui pasinaudoju straipsneliu:  <<2>>  +
Sukuriu `stud` paskyrai naują SSH raktą:

----
stud@cc-lab:~$ ssh-keygen
Generating public/private rsa key pair.
Enter file in which to save the key (/home/stud/.ssh/id_rsa):
Created directory '/home/stud/.ssh'.
Enter passphrase (empty for no passphrase):
Enter same passphrase again:
Your identification has been saved in /home/stud/.ssh/id_rsa
Your public key has been saved in /home/stud/.ssh/id_rsa.pub
The key fingerprint is:
SHA256:eRmPaDqOuSZ8j+MXGe9DMROb9ewfCVJqK/OIjWWDH4g stud@cc-lab
The key's randomart image is:
+---[RSA 3072]----+
|                 |
|        . . .    |
|         =.=     |
|      . *o+=+    |
|     . *S=++.. . |
|    E =oX.. . o  |
| .    o@ B   . . |
|  o +=+.* .   .  |
|   =*=o  .       |
+----[SHA256]-----+
stud@cc-lab:~$ 
----

* => Dėl patogumo ir nereikalaujamo padidinto saugumo, _Passphrase_ neįjungiau (nurodžiau tuščią).

* => Kadangi pradžiai išmėginsiu raktą savo paties serveryje, viešas jo raktas išsisaugos jame pačiame kaip atskiras SSH mazgų įrašas.

* => Kadangi šiame įraše telpa ne vien IP adresas, bet ir serverio vardas, dėl tvarkos reiktų jungtis vardu (tuomet išspręstasis IP adresas išsisaugo kartu).

* => O tam, kad šio įrašo apie SSH mazgą vėliau netektų keisti / taisyti, reiktų prisijungimui naudoti jau galutinį mazgo vardą, nebe testinį `serveris2`.


Pašalinu pradinį, testinį mazgo vardą (dvi eilutes) iš sisteminės lentelės ir įrašau adekvatų vardą:

----
stud@cc-lab:~$ sudo vim /etc/hosts
  ...

stud@cc-lab:~$ echo -e '# 2021-12-07 saukrs: pradedu laborą nr. 4,\n10.128.67.8    serveris1' | sudo tee -a /etc/hosts
# 2021-12-07 saukrs: pradedu laborą nr. 4,
10.128.67.8    serveris1
stud@cc-lab:~$ 
----

Įsitikinu, kad failą sukonfigūravau teisingai:

----
stud@cc-lab:~$ tail /etc/hosts
127.0.1.1 cc-lab

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
# 2021-12-07 saukrs: pradedu laborą nr. 4,
10.128.67.8    serveris1
stud@cc-lab:~$ 
----

Tikrinu vardą `serveris1`, išsisprendžia:

----
stud@cc-lab:~$ ping serveris1
PING serveris1 (10.128.67.8) 56(84) bytes of data.
64 bytes from serveris1 (10.128.67.8): icmp_seq=1 ttl=64 time=0.060 ms
64 bytes from serveris1 (10.128.67.8): icmp_seq=2 ttl=64 time=0.055 ms
^C
--- serveris1 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1002ms
rtt min/avg/max/mdev = 0.055/0.057/0.060/0.002 ms
stud@cc-lab:~$ 
----

Jungiuosi prie savo serverio su slaptažodžiu, patvirtinu rakto eliptinį pėdsaką ir iškart atsijungiu su `^D` kombinacija:

----
stud@cc-lab:~$ ssh serveris1
The authenticity of host 'serveris1 (10.128.67.8)' can't be established.
ECDSA key fingerprint is SHA256:53taBSfMAMqEJLYWDEYZqm5IOYHYeEiBNK6eUve1agE.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'serveris1,10.128.67.8' (ECDSA) to the list of known hosts.
stud@serveris1's password:

stud@cc-lab:~$ ^D
stud@cc-lab:~$ 
----

* => Prieš viešojo SSH rakto kopijavimą į serverį verta patikslinti,
     ar serverio ECDSA (eliptinis) rakto pėdsakas yra autentiškas.
+
Visiškai nesuprantu, kaip tinkamai tai padaryti + atpažinti galimą „pasiklausymą“ / MITM ataką.  <<3>>
+
Todėl tiesiog įvedžiau `yes`.

* => `serveris1` jau pilnai paruoštas jungimuisi per SSH (su slaptažodžiu).


===== Serverio nr. 1 savęs pasiekimas (testinis) naudojantis SSH raktu

Kopijuoju SSH raktą į savo paties (tą patį) serverį:

----
stud@cc-lab:~$ ssh-copy-id serveris1
/usr/bin/ssh-copy-id: INFO: Source of key(s) to be installed: "/home/stud/.ssh/id_rsa.pub"
/usr/bin/ssh-copy-id: INFO: attempting to log in with the new key(s), to filter out any that are already installed
/usr/bin/ssh-copy-id: INFO: 1 key(s) remain to be installed -- if you are prompted now it is to install the new keys
stud@serveris1's password:

Number of key(s) added: 1

Now try logging into the machine, with:   "ssh 'serveris1'"
and check to make sure that only the key(s) you wanted were added.

stud@cc-lab:~$ 
----

Ir tikrinu SSH prisijungimą tuo raktu:

----
stud@cc-lab:~$ ssh serveris1
Welcome to Ubuntu 20.04.3 LTS (GNU/Linux 5.4.0-90-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Tue 07 Dec 2021 04:54:55 PM UTC

  System load:  0.02               Processes:                233
  Usage of /:   42.0% of 19.56GB   Users logged in:          1
  Memory usage: 11%                IPv4 address for docker0: 172.17.0.1
  Swap usage:   0%                 IPv4 address for ens160:  10.128.67.8

 * Super-optimized for small spaces - read how we shrank the memory
   footprint of MicroK8s to make it the smallest full K8s around.

   https://ubuntu.com/blog/microk8s-memory-optimisation

41 updates can be applied immediately.
To see these additional updates run: apt list --upgradable


Last login: Tue Dec  7 16:31:43 2021 from 86.38.73.194

stud@cc-lab:~$ w
 16:54:58 up 57 min,  2 users,  load average: 0.10, 0.04, 0.01
USER     TTY      FROM             LOGIN@   IDLE   JCPU   PCPU WHAT
stud     pts/0    86.38.73.194     16:31    1.00s  0.25s  0.02s ssh serveris1
stud     pts/1    10.128.67.8      16:54    2.00s  0.05s  0.00s w

stud@cc-lab:~$ logout
Connection to serveris1 closed.
stud@cc-lab:~$ 
----

* => Testinis SSH prisijungimas raktu į `serveris1` jau irgi veikia.


[.text-left]
=== _Inventory_ failo paruošimas


===== Testinė konfigūracija

Bandau `/etc/hosts` formatu įtraukti `serveris1` aprašymą ir į numatytąjį inventorinį failą `/etc/ansible/hosts`:  +
(pažvelgus į pastarojo turinį pasirodė, jog formatas toks pats)

----
stud@cc-lab:~$ echo -e '# 2021-12-07 saukrs: pradedu laborą nr. 4,\n[servers]\n10.128.67.8    serveris2' | sudo tee -a /etc/ansible/hosts
# 2021-12-07 saukrs: pradedu laborą nr. 4,
[servers]
10.128.67.8    serveris2
stud@cc-lab:~$ 
----

* => Čia apibrėžiau serverių grupę `servers`.

Tikrinu inventoriaus failą:

----
stud@cc-lab:~$ ansible-inventory --list -y
[WARNING]:  * Failed to parse /etc/ansible/hosts with yaml plugin: Syntax Error while loading YAML.   did not find expected <document start>  The error appears to be in
'/etc/ansible/hosts': line 47, column 1, but may be elsewhere in the file depending on the exact syntax problem.  The offending line appears to be:  [servers] 10.128.67.8
serveris2 ^ here
[WARNING]:  * Failed to parse /etc/ansible/hosts with ini plugin: /etc/ansible/hosts:47: Expected key=value host variable assignment, got: serveris2
[WARNING]: Unable to parse /etc/ansible/hosts as an inventory source
[WARNING]: No inventory was parsed, only implicit localhost is available
all:
  children:
    ungrouped: {}
stud@cc-lab:~$ 
----

* => Bloga inventorinio failo struktūra.

* => Nors vietoj `serveris1` klaidingai įrašiau `serveris2`, kol kas situacijos tai nekeitė.


Šalinu tris savo įterptas eilutes (taisydamas failo turinį redaktoriuje):

----
stud@cc-lab:~$ sudo vim /etc/ansible/hosts
  ...
stud@cc-lab:~$ 
----

Kol rasiu klaidą, inventoriuje aprašau mazgą nenaudodamas vardo išvis -- tik IP adresą:

----
stud@cc-lab:~$ echo -e '# 2021-12-07 saukrs: pradedu laborą nr. 4,\n[servers]\n10.128.67.8' | sudo tee -a /etc/ansible/hosts
# 2021-12-07 saukrs: pradedu laborą nr. 4,
[servers]
10.128.67.8
----

Dabar _Ansible_ inventorius pradėjo veikti:

----
stud@cc-lab:~$ ansible-inventory --list -y
all:
  children:
    servers:
      hosts:
        10.128.67.8: {}
    ungrouped: {}
stud@cc-lab:~$ 
----


===== Pirmas _Inventory_ failo testas

Tikrinu _Ansible_ gebėjimą jungtis prie testinio inventorinio (t. y. savo paties) serverio:

----
stud@cc-lab:~$ ansible all -m ping -u stud
10.128.67.8 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "ping": "pong"
}
stud@cc-lab:~$ 
----

* => _Ansible_ mazgas jau prisijungia prie paties savęs (kol kas tik IP adresu).


===== _Inventory_ failo tikslinimas

LD aprašyme pagaliau atkreipiau dėmesį, kad _Ansible_ `hosts` failas naudoja _kiek kitokį_ formatą aprašyti mazgui.

* => Šis formatas yra lankstesnis -- skirtingose situacijose turi galimybę „šakotis“:  <<4>>
+
|===
   | Failas                                           | Pirmas stulpelis      | Antras stulpelis
   
   | `/etc/hosts`                                     | `**<IP adresas>**`    | vardas
   | `/etc/ansible/hosts`  IP adresams                | `**<IP adresas>**`    | --
   | `/etc/ansible/hosts`  registruotuotiems vardams  | vardas                | --
   | `/etc/ansible/hosts`  neregistruotiems vardams   | vardas                | `ansible_host=**<IP adresas>**`
|===

* => Jis turi ir kitų galimybių (pvz. nurodyti netipinį mazgo TCP prievadą SSH prisijungimui).

Taigi, ištrinu savo pradinę `/etc/ansible/hosts` konfigūraciją:

----
stud@cc-lab:~$ sudo vim /etc/ansible/hosts
  ...
stud@cc-lab:~$ 
----

Papildau ją kitu formatu:

----
stud@cc-lab:~$ echo -e '# 2021-12-07 saukrs: pradedu laborą nr. 4,\n[servers]\nserver1 ansible_host=10.128.67.8' | sudo tee -a /etc/ansible/hosts
# 2021-12-07 saukrs: pradedu laborą nr. 4,
[servers]
server1 ansible_host=10.128.67.8
stud@cc-lab:~$ 
----

Patikrinu šį formatą -- tinkamas:

----
stud@cc-lab:~$ ansible-inventory --list -y
all:
  children:
    servers:
      hosts:
        server1:
          ansible_host: 10.128.67.8
    ungrouped: {}
stud@cc-lab:~$ 
----

Patikrinu inventorinio failo veikimą -- veikia:

----
stud@cc-lab:~$ ansible all -m ping -u stud
server1 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "ping": "pong"
}
stud@cc-lab:~$ 
----

Nustoju naudoti CLI raktą `-u stud`, nes dabar virtualioje laboratorijoje magistrantai dirba vien su šia paskyra, kitų vardų nenaudojame:

----
stud@cc-lab:~$ ansible all -m ping
server1 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "ping": "pong"
}
stud@cc-lab:~$ 
----

* => susipažinta su `/etc/ansible/hosts` formatu, sukurta testinė konfigūracija.


===== Aprašau serverį nr. 2

LD aprašo susirandu mano serveriui nr. 2 priskirtą IP adresą: `10.128.67.20`.

Pirmiausia aprašau jį `/etc/hosts` faile:

----
stud@cc-lab:~$ echo '10.128.67.20   serveris2' | sudo tee -a /etc/hosts
10.128.67.20   serveris2

stud@cc-lab:~$ tail /etc/hosts

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
# 2021-12-07 saukrs: pradedu laborą nr. 4,
10.128.67.8    serveris1
10.128.67.20   serveris2
stud@cc-lab:~$ 
----

Paskui ir _Ansible_ inventoriuje:

----
stud@cc-lab:~$ echo 'serveris2 ansible_host=10.128.67.20' | sudo tee -a /etc/ansible/hosts
serveris2 ansible_host=10.128.67.20

stud@cc-lab:~$ tail /etc/ansible/hosts

# Here's another example of host ranges, this time there are no
# leading 0s:

#db-[99:101]-node.example.com

# 2021-12-07 saukrs: pradedu laborą nr. 4,
[servers]
server1 ansible_host=10.128.67.8
serveris2 ansible_host=10.128.67.20
stud@cc-lab:~$
----

* => Pastebiu netiksliai užrašytą serverio nr. 1 vardą.


[.text-left]
===== Konfigūracijos klaidų taisymas 

Pataisau serverio nr. 1 aprašymą redaktoriumi, rankiniu būdu:

----
stud@cc-lab:~$ sudo vim /etc/ansible/hosts
  ...
# 2021-12-07 saukrs: pradedu laborą nr. 4,
[servers]
serveris1 ansible_host=10.128.67.8
serveris2 ansible_host=10.128.67.20
                                                                                                                                                           47,8          All
stud@cc-lab:~$ 
----

Įsitikinu, kad _Inventory_ papildžiau teisingai:

----
stud@cc-lab:~$ ansible-inventory --list -y
all:
  children:
    servers:
      hosts:
        serveris1:
          ansible_host: 10.128.67.8
        serveris2:
          ansible_host: 10.128.67.20
    ungrouped: {}
stud@cc-lab:~$ 
----

* => Jei `/etc/ansible/hosts` faile naudotume tik vardus (be IP adresų), tokias klaidas varduose (tą patį vardą, keliose vietose aprašomą skirtingai) būtų pavykę pastebėti iškart.

* => Paruoštas ir patikrintas inventoriaus failas, jame aprašytas serveris nr. 2.


[.text-left]
=== _Ansible_ prisijungimų tikrinimas

_Ansible_ valdymo mazge startuoju komandą:

----
stud@cc-lab:~$ ansible all -m ping
The authenticity of host '10.128.67.20 (10.128.67.20)' can't be established.
ECDSA key fingerprint is SHA256:53taBSfMAMqEJLYWDEYZqm5IOYHYeEiBNK6eUve1agE.
Are you sure you want to continue connecting (yes/no/[fingerprint])? serveris1 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "ping": "pong"
}
yes^C
serveris2 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: Warning: Permanently added '10.128.67.20' (ECDSA) to the list of known hosts.\r\nstud@10.128.67.20: Permission denied (pub
lickey,password).",
    "unreachable": true
}
stud@cc-lab:~$ 
----

* => Vis dar neparuošiau SSH prisijungimo iš `serveris1` į `serveris2`.


===== Tolimesnis SSH prisijungimų tvarkymas

Kopijuoju serverio nr. 1 raktą į serverį nr. 2:

----
stud@cc-lab:~$ ssh-copy-id serveris2
/usr/bin/ssh-copy-id: INFO: Source of key(s) to be installed: "/home/stud/.ssh/id_rsa.pub"
The authenticity of host 'serveris2 (10.128.67.20)' can't be established.
ECDSA key fingerprint is SHA256:53taBSfMAMqEJLYWDEYZqm5IOYHYeEiBNK6eUve1agE.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
/usr/bin/ssh-copy-id: INFO: attempting to log in with the new key(s), to filter out any that are already installed
/usr/bin/ssh-copy-id: INFO: 1 key(s) remain to be installed -- if you are prompted now it is to install the new keys
stud@serveris2's password:

Number of key(s) added: 1

Now try logging into the machine, with:   "ssh 'serveris2'"
and check to make sure that only the key(s) you wanted were added.

stud@cc-lab:~$ 
----


===== Antras prisijungimų tikrinimas

----
stud@cc-lab:~$ ansible all -m ping
serveris1 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "ping": "pong"
}
serveris2 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "ping": "pong"
}
stud@cc-lab:~$
----

* => Galų gale abu serveriai atsiliepia tinkamai.
     Rezultatas panašus į pateiktąjį LD apraše.  +
     _Ansible_ valdymo mazgas palaiko ryšį su dviem serveriais (vienu testiniu ir vienu produkciniu).


[.text-left]
=== Nuotolinis komandų vykdymas


===== LD užduoties _Ad-hoc_ komandos

----
stud@cc-lab:~$ ansible all -a "df -h"
serveris1 | CHANGED | rc=0 >>
Filesystem                         Size  Used Avail Use% Mounted on
udev                               1.5G     0  1.5G   0% /dev
tmpfs                              300M  1.2M  299M   1% /run
/dev/mapper/ubuntu--vg-ubuntu--lv   20G  8.3G   11G  45% /
tmpfs                              1.5G  124K  1.5G   1% /dev/shm
tmpfs                              5.0M     0  5.0M   0% /run/lock
tmpfs                              1.5G     0  1.5G   0% /sys/fs/cgroup
/dev/loop0                          56M   56M     0 100% /snap/core18/2246
/dev/loop1                          56M   56M     0 100% /snap/core18/2253
/dev/loop3                          62M   62M     0 100% /snap/core20/1270
/dev/loop2                          62M   62M     0 100% /snap/core20/1242
/dev/loop4                          68M   68M     0 100% /snap/lxd/21835
/dev/loop5                          68M   68M     0 100% /snap/lxd/21803
/dev/loop7                          33M   33M     0 100% /snap/snapd/13640
/dev/loop6                         117M  117M     0 100% /snap/docker/1125
/dev/loop8                          43M   43M     0 100% /snap/snapd/14066
/dev/sda2                          976M  203M  707M  23% /boot
tmpfs                              300M     0  300M   0% /run/user/1001
serveris2 | CHANGED | rc=0 >>
Filesystem                         Size  Used Avail Use% Mounted on
udev                               1.5G     0  1.5G   0% /dev
tmpfs                              300M  1.2M  299M   1% /run
/dev/mapper/ubuntu--vg-ubuntu--lv   20G  7.7G   11G  42% /
tmpfs                              1.5G     0  1.5G   0% /dev/shm
tmpfs                              5.0M     0  5.0M   0% /run/lock
tmpfs                              1.5G     0  1.5G   0% /sys/fs/cgroup
/dev/loop1                          56M   56M     0 100% /snap/core18/2246
/dev/loop2                          62M   62M     0 100% /snap/core20/1169
/dev/loop0                          56M   56M     0 100% /snap/core18/2128
/dev/loop3                          68M   68M     0 100% /snap/lxd/21803
/dev/loop4                          68M   68M     0 100% /snap/lxd/21835
/dev/loop5                         117M  117M     0 100% /snap/docker/1125
/dev/loop6                          43M   43M     0 100% /snap/snapd/13831
/dev/loop7                          33M   33M     0 100% /snap/snapd/13640
/dev/sda2                          976M  203M  707M  23% /boot
tmpfs                              300M     0  300M   0% /run/user/1001
stud@cc-lab:~$ 
----

* => Gaunu serverių primontuotų failinių sistemų (FS) būsenas.

----
stud@cc-lab:~$ ansible all -a uptime
serveris1 | CHANGED | rc=0 >>
 17:08:48 up  1:10,  2 users,  load average: 0.07, 0.02, 0.00
serveris2 | CHANGED | rc=0 >>
 17:08:48 up 51 min,  1 user,  load average: 0.00, 0.00, 0.00
stud@cc-lab:~$ 
----

* => Gaunu serverių veikimo trukmes ir sistemines apkrovas (_System load_).

* => _Ansible_ abi LD komandas įvykdė abiejuose serveriuose sėkmingai.


===== Kitos (paprastos) _Ad-hoc_ komandas

----
stud@cc-lab:~$ ansible all -a "ip r"
serveris2 | CHANGED | rc=0 >>
default via 10.128.67.254 dev ens160 proto dhcp src 10.128.67.20 metric 100
10.128.67.0/24 dev ens160 proto kernel scope link src 10.128.67.20
10.128.67.254 dev ens160 proto dhcp scope link src 10.128.67.20 metric 100
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown
serveris1 | CHANGED | rc=0 >>
default via 10.128.67.254 dev ens160 proto dhcp src 10.128.67.8 metric 100
10.128.67.0/24 dev ens160 proto kernel scope link src 10.128.67.8
10.128.67.254 dev ens160 proto dhcp scope link src 10.128.67.8 metric 100
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown
stud@cc-lab:~$ 
----

* => Gavau maršrutų lenteles.

----
stud@cc-lab:~$ ansible all -a w
serveris2 | CHANGED | rc=0 >>
 17:19:21 up  1:01,  1 user,  load average: 0.00, 0.00, 0.00
USER     TTY      FROM             LOGIN@   IDLE   JCPU   PCPU WHAT
stud     pts/0    10.128.67.8      17:19    1.00s  0.19s  0.00s w
serveris1 | CHANGED | rc=0 >>
 17:19:21 up  1:21,  2 users,  load average: 0.00, 0.00, 0.00
USER     TTY      FROM             LOGIN@   IDLE   JCPU   PCPU WHAT
stud     pts/0    86.38.73.194     16:31    5.00s  1.64s  0.00s ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthenticat
ions=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/stud/.ansible/cp/62369c22bf -tt 10.128.67.8 /bin
/sh -c '/usr/bin/python3 /home/stud/.ansible/tmp/ansible-tmp-1638897559.5734017-231528218158292/AnsiballZ_command.py && sleep 0'
stud     pts/3    10.128.67.8      17:19    1.00s  0.21s  0.01s w
stud@cc-lab:~$ 
----

* => Gavau prisijungusių vartotojų skaičių ir aktyvias vykdomas programas.

* => Čia atsitiktinai pastebiu, kad _Ansible_ jungimuisi į serverius naudoja komandą `ssh` su gana ilga komandine eilute:
+
```
ssh \
  -C \
  -o ControlMaster=auto \
  -o ControlPersist=60s \
  -o KbdInteractiveAuthentication=no \
  -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey \
  -o PasswordAuthentication=no \
  -o ConnectTimeout=10 \
  -o ControlPath=/home/stud/.ansible/cp/62369c22bf \
  -tt \
  10.128.67.8 /bin/sh \
  -c '/usr/bin/python3 \
        /home/stud/.ansible/tmp/ansible-tmp-1638897559.5734017-231528218158292/AnsiballZ_command.py \
      && sleep 0'
```

* => ... ir nuotoliniame serveryje startuoja tokį _Python_ skriptą:
+
```
/usr/bin/python3 /home/stud/.ansible/tmp/ansible-tmp-1638897559.5734017-231528218158292/AnsiballZ_command.py
```

* => Panašu, kad skriptą `AnsiballZ_command.py` _Ansible_ į nuotolinį serverį sau nusikopijuoja prieš pat vykdymą.


Leidžiu paskutinę paprastą komandą:

----
stud@cc-lab:~$ ansible all -a "lsb_release -d"
serveris1 | CHANGED | rc=0 >>
Description:    Ubuntu 20.04.3 LTS
serveris2 | CHANGED | rc=0 >>
Description:    Ubuntu 20.04.3 LTS
stud@cc-lab:~$ 
----

* => Visos paprastos (pavienės) _Ad-hoc_ komandos veikia.


===== Kompozitinės _Ad-hoc_ komandos

Mėginu komandą `lscpu | awk '/^CPU/'` nustatyti mašinos CPU branduolių skaičiui:

----
stud@cc-lab:~$ ansible all -a "lscpu | awk '/^CPU/'"
serveris2 | FAILED | rc=1 >>
lscpu: bad usage
Try 'lscpu --help' for more information.non-zero return code
serveris1 | FAILED | rc=1 >>
lscpu: bad usage
Try 'lscpu --help' for more information.non-zero return code
stud@cc-lab:~$ 
----

* => Neveikia, ir neaišku, kokią komandinę eilutę `lscpu` gavo, kad „pyksta“.

Mėginu visą komandą įvykdyti _Bash_ pagalba:

----
stud@cc-lab:~$ ansible all -a bash -c "lscpu | awk '/^CPU/'"
serveris1 | FAILED | rc=-1 >>
the connection plugin 'lscpu | awk '/^CPU/'' was not found
serveris2 | FAILED | rc=-1 >>
the connection plugin 'lscpu | awk '/^CPU/'' was not found
stud@cc-lab:~$ 
----

* => Blogai: šitaip raktą `-c` _Ansible_ pasiima sau ir pasimeta.

Visą komandinę eilutę kartu su `bash` apgaubiu išorinėmis dvigubomis kabutėmis (kaip vientisą, vieną argumentą), o vidines dvigubąsias „eskeipinu“:

----
stud@cc-lab:~$ ansible all -a "bash -c \"lscpu | awk '/^CPU.s/'\""
serveris1 | CHANGED | rc=0 >>
CPU(s):                          2
serveris2 | CHANGED | rc=0 >>
CPU(s):                          2
stud@cc-lab:~$ 
----

* => Pagaliau veikia.  Beje, `awk` komandą šiek tiek papildžiau, kad grąžintų tik vieną eilutę per mazgą.

Pamėginu išsitraukti ir CPU taktinį dažnį:

----
stud@cc-lab:~$ ansible all -a "bash -c \"lscpu | awk '/^CPU.s|Hz/'\""
serveris1 | CHANGED | rc=0 >>
CPU(s):                          2
Model name:                      Intel(R) Xeon(R) CPU           E5645  @ 2.40GHz
CPU MHz:                         2400.085
serveris2 | CHANGED | rc=0 >>
CPU(s):                          2
Model name:                      Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz
CPU MHz:                         2400.085
stud@cc-lab:~$ 
----

* => _Ansible_ geba vykdyti ir _Bash_-kompozitines _Ad-hoc_ komandas.


* => Pamiršau patikrinti _Ansible_ hostų grupavimą, t.y. nurodyti serverių grupę `servers` vietoje `all`.  +
     Esu įsitikinęs, kad ji veiktų taip pat puikiai.


[.text-left]
=== ^(Bonus)^ _Ansible_ grojaraščių vykdymas

Pradedu kurti atskirą grojaraštį (_Playbook_):

----
stud@cc-lab:~$ ls -Al
total 52
drwxrwxr-x 4 stud stud 4096 Dec  7 16:57 .ansible
-rw------- 1 stud stud 1005 Dec  7 16:54 .bash_history
-rw-r--r-- 1 stud stud  220 Oct 19 14:14 .bash_logout
-rw-r--r-- 1 stud stud 3771 Oct 19 14:14 .bashrc
drwxrwxr-x 3 stud stud 4096 Oct 19 16:23 build
drwx------ 2 stud stud 4096 Oct 19 14:21 .cache
-rw------- 1 stud stud   39 Dec  7 16:41 .lesshst
drwxrwxr-x 3 stud stud 4096 Oct 19 16:08 .local
-rw-r--r-- 1 stud stud  807 Oct 19 14:14 .profile
drwxr-xr-x 3 stud stud 4096 Oct 19 15:40 snap
drwx------ 2 stud stud 4096 Dec  7 17:07 .ssh
-rw-r--r-- 1 stud stud    0 Oct 19 14:15 .sudo_as_admin_successful
drwxrwxr-x 2 stud stud 4096 Oct 19 15:40 test
-rw------- 1 stud stud 1162 Dec  7 16:38 .viminfo

stud@cc-lab:~$ mkdir src

stud@cc-lab:~$ cd src

stud@cc-lab:~/src$ vim saukrs-1.yml
  ...
----

Kopijuoju pavyzdį iš _Red Hat_ Blog-įrašo:  <<5>>

----
# 2021-12-07 saukrs: kopijuoju iš https://www.redhat.com/en/blog/ansible-101-ansible-beginners
#
- name: saukrs Playbook nr.1
  hosts: serveris2
  tasks:
    - name: diegiame nginx
        yum:
          name: nginx
          state: present
----

Bandau grojaraštį:

----
[1]+  Stopped                 vim saukrs-1.yml

stud@cc-lab:~/src$ ansible-playbook saukrs-1.yml
ERROR! Syntax Error while loading YAML.
  mapping values are not allowed in this context

The error appears to be in '/home/stud/src/saukrs-1.yml': line 7, column 12, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    - name: diegiame nginx
        yum:
           ^ here
stud@cc-lab:~/src$ 
----

* => Klaida.  Bet ne faktas, kad septintoje eilutėje.

Įterpiu YAML pradžios žymę `---`:

----
stud@cc-lab:~/src$ fg
----


----
---
# 2021-12-07 saukrs: kopijuoju iš https://www.redhat.com/en/blog/ansible-101-ansible-beginners
- name: saukrs Playbook nr.1
  hosts: serveris2
  tasks:
    - name: diegiame nginx
        yum:
          name: nginx
          state: present
----

* => Klaida išlieka tokia pati.

Įsikopijuoja kitą pavyzdį:  <<6>>

----
stud@cc-lab:~/src$ vim saukrs-2.yml
----


----
---
- hosts: all
  become: yes
  tasks:
  - name: Install packages
    apt:
      name:
      - ntpdate
      - nmap
      state: latest
      cache_valid_time: 3600

----

Bandau antrą grojaraštį:

----
[1]+  Stopped                 vim saukrs-2.yml
stud@cc-lab:~/src$ ansible-playbook saukrs-2.yml

PLAY [all] ******************************************************************************************************************************************************************

TASK [Gathering Facts] ******************************************************************************************************************************************************
fatal: [serveris1]: FAILED! => {"msg": "Missing sudo password"}
fatal: [serveris2]: FAILED! => {"msg": "Missing sudo password"}

PLAY RECAP ******************************************************************************************************************************************************************
serveris1                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
serveris2                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

stud@cc-lab:~/src$ 
----

* => Grojaraštis nr. 2 sintaksės klaidų nebeturi, tačiau praneša, kad trūksta `sudo` slaptažodžio.

* => Grąžina `ok=0` ir `failed=1`.


Suguglinu patarimą naudoti papildomą raktą `--ask-become-pass`:  <<7>>

----
stud@cc-lab:~/src$ ansible-playbook saukrs-2.yml --ask-become-pass
BECOME password:

PLAY [all] ******************************************************************************************************************************************************************

TASK [Gathering Facts] ******************************************************************************************************************************************************
ok: [serveris1]
ok: [serveris2]

TASK [Install packages] *****************************************************************************************************************************************************
changed: [serveris1]
changed: [serveris2]

PLAY RECAP ******************************************************************************************************************************************************************
serveris1                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
serveris2                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

stud@cc-lab:~/src$ 
----

* => _Ansible_ paprašė slaptažodžio -- spėjau, kad `stud` paskyros, ir pataikiau, regis.

* => Žingsnis `[Install packages]` užtruko ilgiausiai:

  - `serveris1` apie 10 s.
  - `serveris2` apie 20 s.

* => Grojaraštis grąžina `ok=2` ir `failed=0`.

* => Panašu, kad jis įdiegė / atnaujino abu nurodytus paketus: `ntpdate` ir `nmap`.
     Paketų būsenos tiesiogiai nepatikrinau.


Nutariau pasitikrinti, ką tiksliai vykdo _Ansible_ ir kuri komanda paprašo `sudo` slaptažodžio.  +
Dėstytojas pasiūlė naudoti `-v` ar net `-vvv`, mėginu:

----
stud@cc-lab:~/src$ ansible-playbook saukrs-2.yml -vvv
ansible-playbook 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/stud/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 3.8.10 (default, Sep 28 2021, 16:10:42) [GCC 9.3.0]
Using /etc/ansible/ansible.cfg as config file
host_list declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
script declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
auto declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Parsed /etc/ansible/hosts inventory source with ini plugin

PLAYBOOK: saukrs-2.yml ******************************************************************************************************************************************************
1 plays in saukrs-2.yml

PLAY [all] ******************************************************************************************************************************************************************

TASK [Gathering Facts] ******************************************************************************************************************************************************
task path: /home/stud/src/saukrs-2.yml:2
<10.128.67.8> ESTABLISH SSH CONNECTION FOR USER: None
<10.128.67.8> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/stud/.ansible/cp/62369c22bf 10.128.67.8 '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<10.128.67.20> ESTABLISH SSH CONNECTION FOR USER: None
<10.128.67.20> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/stud/.ansible/cp/b650e54a14 10.128.67.20 '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<10.128.67.8> (0, b'/home/stud\n', b'')
<10.128.67.8> ESTABLISH SSH CONNECTION FOR USER: None
<10.128.67.8> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/stud/.ansible/cp/62369c22bf 10.128.67.8 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/stud/.ansible/tmp/ansible-tmp-1638899019.7293622-253348797528778 `" && echo ansible-tmp-1638899019.7293622-253348797528778="` echo /home/stud/.ansible/tmp/ansible-tmp-1638899019.7293622-253348797528778 `" ) && sleep 0'"'"''
<10.128.67.8> (0, b'ansible-tmp-1638899019.7293622-253348797528778=/home/stud/.ansible/tmp/ansible-tmp-1638899019.7293622-253348797528778\n', b'')
<10.128.67.20> (0, b'/home/stud\n', b'')
<10.128.67.20> ESTABLISH SSH CONNECTION FOR USER: None
<10.128.67.20> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/stud/.ansible/cp/b650e54a14 10.128.67.20 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/stud/.ansible/tmp/ansible-tmp-1638899019.7481883-242494816437750 `" && echo ansible-tmp-1638899019.7481883-242494816437750="` echo /home/stud/.ansible/tmp/ansible-tmp-1638899019.7481883-242494816437750 `" ) && sleep 0'"'"''
<10.128.67.20> (0, b'ansible-tmp-1638899019.7481883-242494816437750=/home/stud/.ansible/tmp/ansible-tmp-1638899019.7481883-242494816437750\n', b'')
<serveris2> Attempting python interpreter discovery
<10.128.67.20> ESTABLISH SSH CONNECTION FOR USER: None
<serveris1> Attempting python interpreter discovery
<10.128.67.8> ESTABLISH SSH CONNECTION FOR USER: None
<10.128.67.20> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/stud/.ansible/cp/b650e54a14 10.128.67.20 '/bin/sh -c '"'"'echo PLATFORM; uname; echo FOUND; command -v '"'"'"'"'"'"'"'"'/usr/bin/python'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.7'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.6'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.5'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python2.7'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python2.6'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'/usr/libexec/platform-python'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'/usr/bin/python3'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python'"'"'"'"'"'"'"'"'; echo ENDFOUND && sleep 0'"'"''
<10.128.67.8> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/stud/.ansible/cp/62369c22bf 10.128.67.8 '/bin/sh -c '"'"'echo PLATFORM; uname; echo FOUND; command -v '"'"'"'"'"'"'"'"'/usr/bin/python'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.7'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.6'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.5'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python2.7'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python2.6'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'/usr/libexec/platform-python'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'/usr/bin/python3'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python'"'"'"'"'"'"'"'"'; echo ENDFOUND && sleep 0'"'"''
<10.128.67.20> (0, b'PLATFORM\nLinux\nFOUND\n/usr/bin/python3\nENDFOUND\n', b'')
<10.128.67.20> ESTABLISH SSH CONNECTION FOR USER: None
<10.128.67.20> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/stud/.ansible/cp/b650e54a14 10.128.67.20 '/bin/sh -c '"'"'/usr/bin/python3 && sleep 0'"'"''
<10.128.67.8> (0, b'PLATFORM\nLinux\nFOUND\n/usr/bin/python3\nENDFOUND\n', b'')
<10.128.67.8> ESTABLISH SSH CONNECTION FOR USER: None
<10.128.67.8> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/stud/.ansible/cp/62369c22bf 10.128.67.8 '/bin/sh -c '"'"'/usr/bin/python3 && sleep 0'"'"''
<10.128.67.20> (0, b'{"platform_dist_result": [], "osrelease_content": "NAME=\\"Ubuntu\\"\\nVERSION=\\"20.04.3 LTS (Focal Fossa)\\"\\nID=ubuntu\\nID_LIKE=debian\\nPRETTY_NAME=\\"Ubuntu 20.04.3 LTS\\"\\nVERSION_ID=\\"20.04\\"\\nHOME_URL=\\"https://www.ubuntu.com/\\"\\nSUPPORT_URL=\\"https://help.ubuntu.com/\\"\\nBUG_REPORT_URL=\\"https://bugs.launchpad.net/ubuntu/\\"\\nPRIVACY_POLICY_URL=\\"https://www.ubuntu.com/legal/terms-and-policies/privacy-policy\\"\\nVERSION_CODENAME=focal\\nUBUNTU_CODENAME=focal\\n"}\n', b'')
Using module file /usr/lib/python3/dist-packages/ansible/modules/system/setup.py
<10.128.67.20> PUT /home/stud/.ansible/tmp/ansible-local-8956eid90gyx/tmpmvv1n7vm TO /home/stud/.ansible/tmp/ansible-tmp-1638899019.7481883-242494816437750/AnsiballZ_setup.py
<10.128.67.20> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/stud/.ansible/cp/b650e54a14 '[10.128.67.20]'
<10.128.67.8> (0, b'{"platform_dist_result": [], "osrelease_content": "NAME=\\"Ubuntu\\"\\nVERSION=\\"20.04.3 LTS (Focal Fossa)\\"\\nID=ubuntu\\nID_LIKE=debian\\nPRETTY_NAME=\\"Ubuntu 20.04.3 LTS\\"\\nVERSION_ID=\\"20.04\\"\\nHOME_URL=\\"https://www.ubuntu.com/\\"\\nSUPPORT_URL=\\"https://help.ubuntu.com/\\"\\nBUG_REPORT_URL=\\"https://bugs.launchpad.net/ubuntu/\\"\\nPRIVACY_POLICY_URL=\\"https://www.ubuntu.com/legal/terms-and-policies/privacy-policy\\"\\nVERSION_CODENAME=focal\\nUBUNTU_CODENAME=focal\\n"}\n', b'')
Using module file /usr/lib/python3/dist-packages/ansible/modules/system/setup.py
<10.128.67.8> PUT /home/stud/.ansible/tmp/ansible-local-8956eid90gyx/tmp7h_h8icd TO /home/stud/.ansible/tmp/ansible-tmp-1638899019.7293622-253348797528778/AnsiballZ_setup.py
<10.128.67.8> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/stud/.ansible/cp/62369c22bf '[10.128.67.8]'
<10.128.67.20> (0, b'sftp> put /home/stud/.ansible/tmp/ansible-local-8956eid90gyx/tmpmvv1n7vm /home/stud/.ansible/tmp/ansible-tmp-1638899019.7481883-242494816437750/AnsiballZ_setup.py\n', b'')
<10.128.67.20> ESTABLISH SSH CONNECTION FOR USER: None
<10.128.67.20> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/stud/.ansible/cp/b650e54a14 10.128.67.20 '/bin/sh -c '"'"'chmod u+x /home/stud/.ansible/tmp/ansible-tmp-1638899019.7481883-242494816437750/ /home/stud/.ansible/tmp/ansible-tmp-1638899019.7481883-242494816437750/AnsiballZ_setup.py && sleep 0'"'"''
<10.128.67.8> (0, b'sftp> put /home/stud/.ansible/tmp/ansible-local-8956eid90gyx/tmp7h_h8icd /home/stud/.ansible/tmp/ansible-tmp-1638899019.7293622-253348797528778/AnsiballZ_setup.py\n', b'')
<10.128.67.8> ESTABLISH SSH CONNECTION FOR USER: None
<10.128.67.20> (0, b'', b'')
<10.128.67.20> ESTABLISH SSH CONNECTION FOR USER: None
<10.128.67.20> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/stud/.ansible/cp/b650e54a14 -tt 10.128.67.20 '/bin/sh -c '"'"'sudo -H -S -n  -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-uawkzdzxtwbuqhzyjbiocuqvsbhmallm ; /usr/bin/python3 /home/stud/.ansible/tmp/ansible-tmp-1638899019.7481883-242494816437750/AnsiballZ_setup.py'"'"'"'"'"'"'"'"' && sleep 0'"'"''
<10.128.67.8> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/stud/.ansible/cp/62369c22bf 10.128.67.8 '/bin/sh -c '"'"'chmod u+x /home/stud/.ansible/tmp/ansible-tmp-1638899019.7293622-253348797528778/ /home/stud/.ansible/tmp/ansible-tmp-1638899019.7293622-253348797528778/AnsiballZ_setup.py && sleep 0'"'"''
<10.128.67.8> (0, b'', b'')
<10.128.67.8> ESTABLISH SSH CONNECTION FOR USER: None
<10.128.67.8> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/stud/.ansible/cp/62369c22bf -tt 10.128.67.8 '/bin/sh -c '"'"'sudo -H -S -n  -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-xucyadvmmhrwwkflwsxapwvnhklmvrvo ; /usr/bin/python3 /home/stud/.ansible/tmp/ansible-tmp-1638899019.7293622-253348797528778/AnsiballZ_setup.py'"'"'"'"'"'"'"'"' && sleep 0'"'"''
Escalation requires password
<10.128.67.20> ESTABLISH SSH CONNECTION FOR USER: None
<10.128.67.20> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/stud/.ansible/cp/b650e54a14 10.128.67.20 '/bin/sh -c '"'"'rm -f -r /home/stud/.ansible/tmp/ansible-tmp-1638899019.7481883-242494816437750/ > /dev/null 2>&1 && sleep 0'"'"''
<10.128.67.20> (0, b'', b'')
Escalation requires password
fatal: [serveris2]: FAILED! => {
    "msg": "Missing sudo password"
}
<10.128.67.8> ESTABLISH SSH CONNECTION FOR USER: None
<10.128.67.8> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/stud/.ansible/cp/62369c22bf 10.128.67.8 '/bin/sh -c '"'"'rm -f -r /home/stud/.ansible/tmp/ansible-tmp-1638899019.7293622-253348797528778/ > /dev/null 2>&1 && sleep 0'"'"''
<10.128.67.8> (0, b'', b'')
fatal: [serveris1]: FAILED! => {
    "msg": "Missing sudo password"
}

PLAY RECAP ******************************************************************************************************************************************************************
serveris1                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
serveris2                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

stud@cc-lab:~/src$ 
----

* => Duomenų gavau išties daug.

* => Į serverį SFTP įrankiu kopijuojamas ir per SSH vykdomas failas `AnsiballZ_setup.py`, kurį jau identifikavau anksčiau.

* => Iš to vis tiek neaišku, ką tiksliai tas _Python_ skriptas veikia ir ar viduje panaudoja `sudo`.

* => Tik ataskaitos kūrimo metu pastebėjau, kad `sudo` naudojama _Ansible_ viduje taip:

----
sudo \
    -H \
    -S \
    -n \
    -u root \
    /bin/sh \
           -c ' \
               echo BECOME-SUCCESS-xucyadvmmhrwwkflwsxapwvnhklmvrvo ; \
               /usr/bin/python3 \
                   /home/stud/.ansible/tmp/ansible-tmp-1638899019.7293622-253348797528778/AnsiballZ_setup.py \
           '
&& sleep 0
----

* => Dabar akivaizdu, kad _Ansible_ pagal nutylėjimą tikrai bando persijungt į `root` vartotoją: `-u root`.

Gavau dėstytojo patarimą greta `become:` instrukcijos panaudoti `become_user:` ir nurodyti jai reikšmę `stud`.  +

Papildau antrąjį, veikiantį grojaraštį komentaru su jo kilmės nuoroda bei šia instrukcija:

----
stud@cc-lab:~/src$ fg
----


----
---
# 2021-12-07 saukrs: paėmiau iš https://techexpert.tips/ansible/ansible-playbook-examples-ubuntu-linux/ ,
  ...
  become: yes
  become_user: stud
  ...
----

Ir jį patikrinu:

----
[1]+  Stopped                 vim saukrs-2.yml
stud@cc-lab:~/src$ ansible-playbook saukrs-2.yml

PLAY [all] ******************************************************************************************************************************************************************

TASK [Gathering Facts] ******************************************************************************************************************************************************
ok: [serveris1]
ok: [serveris2]

TASK [Install packages] *****************************************************************************************************************************************************
ok: [serveris2]
ok: [serveris1]

PLAY RECAP ******************************************************************************************************************************************************************
serveris1                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
serveris2                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

stud@cc-lab:~/src$ 
----

* => `BECOME password:` nebeprašomas, iš vienos pusės džiugu.

* => Iš kitos pusės _Ansible_ dabar nebedarė jokių pakeitimų.  +
     Jei paketai serveriuose dar būtų neįdiegti ar neatnaujinti, `sudo` slaptažodžio turbūt vis tiek prireiktų.  +

* => Kaip elgtųsi _Ansible_ pastaruoju atveju (ar paprašytų slaptažodžio ne iškart, vėliau, ar tiesiog sustotų ir pateiktų klaidą), lieka man neaišku ir neištestuota.

<<<


[.text-left]
=== Laboratorinio darbo pabaiga

* Susipažinta su _Ansible_ sistema iš naudotojo pusės.
* Sukurtas inventoriaus failas.
* Patikrintas nuotolinis komandų vykdymas.
* Patikrintas grojaraščio vykdymas
* Susipažinta truputį ir su _Ansible_ vidiniu mechanizmu (angl. _Under the hood_).
+
Toks pažinimo būdas klasikinėje elektronikos inžinieriaus mąstysenoje (angl. _From the bottom up_, nuo įrangos iki abstraktesnių lygmenų) yra tiesiausias link užtikrinto sistemos supratimo (bent jau mano atveju).
* Laboratorinis darbas man suteikė praktiškai naudingų įgūdžių (užtikrintumą).


[bibliography]
[.text-left]
=== Nuorodos

`2020-06-29` **[[[1]]]** `msys2.org`, (updated) https://github.com/msys2/msys2.github.io/commit/67e99dd672505c48c500c73477fbd9b698960b84#diff-b4d68dc855d0f9476d3f2ee343853bd21bf82ea9960d0cf06661baa244439dd6R9[MSYS2 | Software Distribution and Building Platform for Windows]

`2020-04-23` **[[[2]]]** `digitalocean.com`, Brian Boucheron, https://www.digitalocean.com/community/tutorials/how-to-set-up-ssh-keys-on-ubuntu-20-04[How to Set Up SSH Keys]

`2021-02-13` **[[[3]]]** `jumpnowtek.com`, Jumpnow Technologies, LLC  https://jumpnowtek.com/security/SSH-Hostkey-Fingerprints.html[SSH Hostkey Fingerprints]

`2020-12-01` **[[[4]]]** `ansible.com`, Red Hat, Inc.
https://docs.ansible.com/ansible/2.3/intro_inventory.html#hosts-and-groups[Documentation: Ansible Core v2.3 > Introduction > Inventory > Hosts and Groups]

`2020-04-06` **[[[5]]]** `redhat.com`, Ken Hitchcock, https://www.redhat.com/en/blog/ansible-101-ansible-beginners[Ansible 101 - Ansible for beginners]

`2019-10-20` **[[[6]]]** `techexpert.tips`, facebook.com/fkingit, https://techexpert.tips/ansible/ansible-playbook-examples-ubuntu-linux/#:~:text=To%20run%20this%20Ansible%20playbook,%20use%20the%20following%20command[Ansible - Playbook Examples for Ubuntu Linux]

`2018-08-15` **[[[7]]]**, `stackoverflow.com`, nesinor, https://stackoverflow.com/questions/25582740/missing-sudo-password-in-ansible/51864689#51864689[Missing sudo password in Ansible]
