= Informacinės sistemos rizikos vertinimas
:doctype: book
:toc:
:toc-title: Turinys
:pdf-page-margin: [5mm, 5mm, 10mm, 20mm]

<<<
{nbsp}


[.text-center]
== Informacinės sistemos rizikos vertinimas

{nbsp}


[.text-center]
=== Darbo struktūra
[.text-left]

* Turinys

* Įvadas:

 ** Tikslas
 ** Rizikos vertinimo ribos.  +
    _Aprašomos IS komponentai, jos vartotojai, nutolusių padalinių išsidėstymas (jeigu tokie yra) ir t.t._
 ** Rizikos vertinimo būdas.  +
    _Trumpai aprašomas pasirinktas grėsmių įvertinimo būdas, tame tarpe:_

  *** riziką vertinančios grupės sudėtis;
  *** informacijos surinkimo metodai;
      _(klausimynai, programinės priemonės ir pan.);
  *** pasirinktos rizikos vertinimo skalės aprašymas.

* Sistemos charakteristikos.  +
  _Aprašoma sistema, įskaitant aparatūrą (serverius, tinklo įrangą ir t.t.), programinį aprūpinimą (taikomąsias programas, bazinę PĮ, protokolus), duomenis, vartotojus.
  Pateikiama sąryšių diagrama, duomenų įėjimo ir išėjimo srautai._

* Pažeidžiamumų sąrašas.  +
  _Sudaromas galimai egzistuojančių potencialių IS pažeidžiamumų sąrašas._

* Grėsmių šaltinių sąrašas.  +
  _Sudaromas potencialių, aktualių vertinamai sistemai grėsmių sąrašas._

* Rizikos vertinimo rezultatai.  +
  _Pateikiamas nustatytų rizikų sąrašas (pora „Pažeidžiamumas/Grėsmė“)._  +
  Į kiekvieną šio sąrašo elementą turi įeiti:

 ** numeris ir trumpas aprašymas  +
    _(pvz. „1. Vartotojų slaptažodžiai gali būti atspėti arba parinkti“);_
 ** poros „Pažeidžiamumas/Grėsmė“ aptarimas;
 ** riziką mažinančių esamų apsaugos priemonių rinkinys;
 ** grėsmės realizavimo tikimybės analizė ir jos įvertinimas  +
    _(pvz. „didelė [1,0]“, „vidutinė [0,5]“, „maža [0,1]“);_
 ** poveikio analizė ir jo įvertinimas  +
    _(pvz. „didelis [10]“, „vidutinis [50]“, „mažas [100]“);_
 ** rizikos įvertinimas (reitingas)  +
    _(pvz. didelė, vidutinė, maža);_
 ** rekomenduojamos apsaugos priemonės arba kiti rizikos sumažinimo būdai.

* Išvados.  +
  _Pateikiama rizikų ir jų lygių suvestinė, rekomendacijos ir komentarai,
  paaiškinantys rekomenduojamų apsaugos priemoni panaudojimą rizikos neutralizavimo procese._


[.text-center]
== Eiga

== Turinys

== Įvadas:

=== Tikslas

=== Rizikos vertinimo ribos

_Aprašomos IS komponentai, jos vartotojai, nutolusių padalinių išsidėstymas (jeigu tokie yra) ir t.t._

=== Rizikos vertinimo būdas

_Trumpai aprašomas pasirinktas grėsmių įvertinimo būdas, tame tarpe:_

  *** riziką vertinančios grupės sudėtis;
  *** informacijos surinkimo metodai;
      _(klausimynai, programinės priemonės ir pan.);
  *** pasirinktos rizikos vertinimo skalės aprašymas.

== Sistemos charakteristikos

_Aprašoma sistema, įskaitant aparatūrą (serverius, tinklo įrangą ir t.t.), programinį aprūpinimą (taikomąsias programas, bazinę PĮ, protokolus), duomenis, vartotojus.
  Pateikiama sąryšių diagrama, duomenų įėjimo ir išėjimo srautai._

== Pažeidžiamumų sąrašas

_Sudaromas galimai egzistuojančių potencialių IS pažeidžiamumų sąrašas._

== Grėsmių šaltinių sąrašas

_Sudaromas potencialių, aktualių vertinamai sistemai grėsmių sąrašas._

== Rizikos vertinimo rezultatai

_Pateikiamas nustatytų rizikų sąrašas (pora „Pažeidžiamumas/Grėsmė“)._  +
  Į kiekvieną šio sąrašo elementą turi įeiti:

 ** numeris ir trumpas aprašymas  +
    _(pvz. „1. Vartotojų slaptažodžiai gali būti atspėti arba parinkti“);_
 ** poros „Pažeidžiamumas/Grėsmė“ aptarimas;
 ** riziką mažinančių esamų apsaugos priemonių rinkinys;
 ** grėsmės realizavimo tikimybės analizė ir jos įvertinimas  +
    _(pvz. „didelė [1,0]“, „vidutinė [0,5]“, „maža [0,1]“);_
 ** poveikio analizė ir jo įvertinimas  +
    _(pvz. „didelis [10]“, „vidutinis [50]“, „mažas [100]“);_
 ** rizikos įvertinimas (reitingas)  +
    _(pvz. didelė, vidutinė, maža);_
 ** rekomenduojamos apsaugos priemonės arba kiti rizikos sumažinimo būdai.

== Išvados


=== Planas

Renkuosi nagrinėti vienos IRT/Telco kompanijos _„Bastioninę“_ IS,
priklausančią _Mobility_ infrastruktūrai ir aptarnaujančiai visas kitas,
daugiausiai duomenų centrų (DC) IS, bet taip pat ir kelias Telco IS.

„Bastionų“ (dar kartais vadinama _Jumphost_, angl.) IS skirta jungtis prie kitų IS.

Pagalvojimui:

* įsileidžia ir su _passwd_, bet tik iš KDV arba VPN
* SSH raktai, jų auditas
* papildomos (automatinės) funkcijos/perimetras: `cron`
* somewhat HA (VM ir ne VM)
* VMware infra flapping IFaces
* senas Debian, sąlyginai naujas CentOS
  - iššūkis migruojant, pvz. Perl skriptus
* kai kam dar naudojamas `RSH`, kai kam ir `telnet` (ypač Mgmt)
* TCIN turi 4 lygius: L0, L1, L2, L3
* Bastionai veikia L2 (gal ir L1)
* Turi SSH (kartais RSH ir Telnet) praleidimus į beveik visas infrastruktūros *nix ir OpenVMS mašinas,
  veikiančias visuose TCIN lygiuose (ar tik gretimuose?)
