Debesų kompiuterija

[.text-center]
=== Laboratorinis darbas nr. 3

[.text-center]
== Susipažinimas su Kubernetes platforma

[.text-left]
=== Darbo tikslas

* Išbandyti `Kubernetes` platformą
* Atlikti pagrindinius veiksmus su `Kubernetes` resursais.

[.text-left]
=== Užduotis

. Puslapyje *https://www.katacoda.com/courses/kubernetes[Learn Kubernetes using Interactive Browser-Based Labs | Katacoda]* susikurkite paskyrą.
. Atlikite šias užduotis:
  * Čia naudosite `Minicube` -- tai įrankis, kuriuo lengva pakeisti `Kubernetes`.
    `Minicube` paleidžia vieno mazgo `Kubernetes` klasterį virtualioje mašinoje nešiojamame kompiuteryje naudotojams, 
    norintiems išbandyti `Kubernetes` arba kurti su ja kasdien:
    - https://www.katacoda.com/courses/kubernetes/launch-single-node-cluster[Launch Single Node Kubernetes Cluster]
  * Šiame scenarijuje sužinosite, kaip naudoti `Kubectl`, 
    kad sukurtumėte ir paleistumėte diegimo, replikavimo valdiklius 
    ir pateiktumėte juos per paslaugas (angl. _Services_) be papildomų `yaml` konfigūracijų.
    Tai leidžia konteinerius greitai startuoti klasteryje.
    - https://www.katacoda.com/courses/kubernetes/kubectl-run-containers[Start containers using Kubectl]
  * Šiame scenarijuje sužinosite, kaip naudoti `Kubectl`, kad sukurtumėte ir startuotumėte diegimo, replikavimo valdiklius
    ir pateiktumėte juos per paslaugas (angl. _Services_) aprašydami `yaml` apibrėžtis.
    `YAML` aprašo `Kubernetes` objektus.
    - https://www.katacoda.com/courses/kubernetes/creating-kubernetes-yaml-definitions[Deploy Containers Using YAML]
  * Šiame scenarijuje paaiškinama, kaip paleisti paprastą daugiapakopę žiniatinklio programą naudojant `Kubernetes` ir `Docker`:
    - https://www.katacoda.com/courses/kubernetes/guestbook[Deploy Guestbook example on Kubernetes]

Ataskaitos turinys:

  * Aprašyti pasiekti  rezultatai kiekvienoje užduotyje.
  * Failo dydis < 5 MiB, formatas `PDF`.

<<<

=== Darbo eiga

. Scenarijus *Launch Single Node Kubernetes Cluster*

  * Žingsnis #1, *startuojame `Minikube`*

    - patikriname versiją:
+
----
$ minikube version
minikube version: v1.8.1
commit: cbda04cf6bbe65e987ae52bb393c10099ab62014
----
https://asciinema.org/a/452640

    - startuojame VM su `Kubernetes` klasteriu
+
----
$ minikube start --wait=false
* minikube v1.8.1 on Ubuntu 18.04
* Using the none driver based on user configuration
* Running on localhost (CPUs=2, Memory=2460MB, Disk=145651MB) ...
* OS release is Ubuntu 18.04.4 LTS
* Preparing Kubernetes v1.17.3 on Docker 19.03.6 ...
  - kubelet.resolv-conf=/run/systemd/resolve/resolv.conf
* Launching Kubernetes ... 
* Enabling addons: default-storageclass, storage-provisioner
* Configuring local host environment ...
* Done! kubectl is now configured to use "minikube"
----
https://asciinema.org/a/452643

  * Žingsnis #2, *klasterio informacija*

    - rodome klasterio būseną:
+
----
$ kubectl cluster-info
Kubernetes master is running at https://172.17.0.86:8443
KubeDNS is running at https://172.17.0.86:8443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
----
https://asciinema.org/a/452671

    - klasterio nodų sąrašas:
+
----
$ kubectl get nodes
NAME       STATUS     ROLES    AGE   VERSION
minikube   NotReady   master   16s   v1.17.3

$ kubectl get nodes
NAME       STATUS   ROLES    AGE   VERSION
minikube   Ready    master   18s   v1.17.3
----
https://asciinema.org/a/452686

  * Žingsnis #3, *diegiame konteinerius*

    - konteinerio diegimas klasteryje:
+
----
$ kubectl create deployment first-deployment --image=kataconda/docker-http-server
deployment.apps/first-deployment created
----
https://asciinema.org/a/452688

    - tikriname diegimo būseną:
+
----
$ kubectl get pods
NAME                               READY   STATUS              RESTARTS   AGE
first-deployment-666c48b44-92c2z   0/1     ContainerCreating   0          3s

$ kubectl get pods
NAME                               READY   STATUS              RESTARTS   AGE
first-deployment-666c48b44-92c2z   0/1     ContainerCreating   0          4s

$ kubectl get pods
NAME                               READY   STATUS    RESTARTS   AGE
first-deployment-666c48b44-92c2z   1/1     Running   0          5s
----
https://asciinema.org/a/452708

    - paviešiname konteinerį tinkle:
+
----
$ kubectl expose deployment first-deployment --port=80 --type=NodePort
service/first-deployment exposed
----
https://asciinema.org/a/452709

    - susirandame alokuotą TCP-portą ir vykdome HTTP-užklausą:
+
----
$ kubectl get svc first-deployment -o go-template='{{range.spec.ports}}{{if .nodePort}}{{.nodePort}}{{"\n"}}{{end}}{{end}}'
31900

$ export PORT=$(kubectl get svc first-deployment -o go-template='{{range.spec.ports}}{{if .nodePort}}{{.nodePort}}{{"\n"}}{{end}}{{end}}')

$ echo "Accessing host01:$PORT"
Accessing host01:31900

$ curl host01:$PORT
<h1>This request was processed by host: first-deployment-666c48b44-92c2z</h1>
----
https://asciinema.org/a/452711

  * Žingsnis #4, *_Kubernetes Dashboard_ sąsaja (web-UI)*

    - įgaliname _Minicube_ priedą _Dashboard_:
+
----
$ minikube addons enable dashboard
* The 'dashboard' addon is enabled
----
https://asciinema.org/a/452714

    - diegiame _Kubernetes Dashboard_ pagal duotą YAML šabloną:
+
----
$ kubectl apply -f /opt/kubernetes-dashboard.yaml
namespace/kubernetes-dashboard configured
service/kubernetes-dashboard-katacoda created
----
https://asciinema.org/a/452718

    - stebime _Dashboard_ konteinerių startą:
+
----
$ kubectl get pods -n kubernetes-dashboard -w
NAME                                         READY   STATUS              RESTARTS   AGE
dashboard-metrics-scraper-7b64584c5c-7x46c   0/1     ContainerCreating   0          1s
kubernetes-dashboard-79d9cd965-7f5pb         0/1     ContainerCreating   0          1s
kubernetes-dashboard-79d9cd965-7f5pb         1/1     Running             0          1s
dashboard-metrics-scraper-7b64584c5c-7x46c   1/1     Running             0          2s
^C
$ 
----
https://asciinema.org/a/452725
