Debesų kompiuterija

[.text-center]
=== Laboratorinis darbas nr. 3

[.text-center]
== Susipažinimas su Kubernetes platforma

[.text-left]
=== Darbo tikslas

* Išbandyti `Kubernetes` platformą
* Atlikti pagrindinius veiksmus su `Kubernetes` resursais.

[.text-left]
=== Užduotis

. Puslapyje *https://www.katacoda.com/courses/kubernetes[Learn Kubernetes using Interactive Browser-Based Labs | Katacoda]* susikurkite paskyrą.
. Atlikite šias užduotis:
  * Čia naudosite `Minicube` -- tai įrankis, kuriuo lengva pakeisti `Kubernetes`.
    `Minicube` paleidžia vieno mazgo `Kubernetes` klasterį virtualioje mašinoje nešiojamame kompiuteryje naudotojams, 
    norintiems išbandyti `Kubernetes` arba kurti su ja kasdien:
    - https://www.katacoda.com/courses/kubernetes/launch-single-node-cluster[Launch Single Node Kubernetes Cluster]
  * Šiame scenarijuje sužinosite, kaip naudoti `Kubectl`, 
    kad sukurtumėte ir paleistumėte diegimo, replikavimo valdiklius 
    ir pateiktumėte juos per paslaugas (angl. _Services_) be papildomų `yaml` konfigūracijų.
    Tai leidžia konteinerius greitai startuoti klasteryje.
    - https://www.katacoda.com/courses/kubernetes/kubectl-run-containers[Start containers using Kubectl]
  * Šiame scenarijuje sužinosite, kaip naudoti `Kubectl`, kad sukurtumėte ir startuotumėte diegimo, replikavimo valdiklius
    ir pateiktumėte juos per paslaugas (angl. _Services_) aprašydami `yaml` apibrėžtis.
    `YAML` aprašo `Kubernetes` objektus.
    - https://www.katacoda.com/courses/kubernetes/creating-kubernetes-yaml-definitions[Deploy Containers Using YAML]
  * Šiame scenarijuje paaiškinama, kaip paleisti paprastą daugiapakopę žiniatinklio programą naudojant `Kubernetes` ir `Docker`:
    - https://www.katacoda.com/courses/kubernetes/guestbook[Deploy Guestbook example on Kubernetes]

Ataskaitos turinys:

  * Aprašyti pasiekti  rezultatai kiekvienoje užduotyje.
  * Failo dydis < 5 MiB, formatas `PDF`.

<<<

=== Darbo eiga

. Scenarijus *Launch Single Node Kubernetes Cluster*

  * Žingsnis #1, *startuojame `Minikube`*

    - patikriname versiją:
+
----
$ minikube version
minikube version: v1.8.1
commit: cbda04cf6bbe65e987ae52bb393c10099ab62014
----
https://asciinema.org/connect/17d6505f-db3f-4ac3-b2f4-3e357d57a4bb

    - startuojame VM su `Kubernetes` klasteriu
+
----
$ minikube start --wait=false
* minikube v1.8.1 on Ubuntu 18.04
* Using the none driver based on user configuration
* Running on localhost (CPUs=2, Memory=2460MB, Disk=145651MB) ...
* OS release is Ubuntu 18.04.4 LTS
* Preparing Kubernetes v1.17.3 on Docker 19.03.6 ...
  - kubelet.resolv-conf=/run/systemd/resolve/resolv.conf
* Launching Kubernetes ... 
* Enabling addons: default-storageclass, storage-provisioner
* Configuring local host environment ...
* Done! kubectl is now configured to use "minikube"
----
https://asciinema.org/a/qcbhdN5CZysBQzNNef4rhwaz6

  * Žingsnis #2, *klasterio informacija*

    - parodome klasterio detales
+
----
$ kubectl cluster-info
Kubernetes master is running at https://172.17.0.86:8443
KubeDNS is running at https://172.17.0.86:8443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
----
+++<a href="https://asciinema.org/a/W7G6hV6vzy6v6X4VhBWP6rBxg" target="_blank"><img src="https://asciinema.org/a/W7G6hV6vzy6v6X4VhBWP6rBxg.svg" /></a>+++
