Debesų kompiuterija

[.text-center]
=== Laboratorinis darbas nr. 3
[.text-center]
== Susipažinimas su Kubernetes platforma

[.text-left]
=== Darbo tikslas

* Išbandyti `Kubernetes` platformą
* Atlikti pagrindinius veiksmus su `Kubernetes` resursais.

[.text-left]
=== Užduotis

. Puslapyje *https://www.katacoda.com/courses/kubernetes[Learn Kubernetes using Interactive Browser-Based Labs | Katacoda]* susikurkite paskyrą.
. Atlikite šias užduotis:
  * Čia naudosite `Minicube` -- tai įrankis, kuriuo lengva pakeisti `Kubernetes`.
    `Minicube` paleidžia vieno mazgo `Kubernetes` klasterį virtualioje mašinoje nešiojamame kompiuteryje naudotojams, 
    norintiems išbandyti `Kubernetes` arba kurti su ja kasdien:
    - https://www.katacoda.com/courses/kubernetes/launch-single-nde-cluster[Launch Single Node Kubernetes Cluster]
  * Šiame scenarijuje sužinosite, kaip naudoti `Kubectl`, 
    kad sukurtumėte ir paleistumėte diegimo, replikavimo valdiklius 
    ir pateiktumėte juos per paslaugas (`Services`) be papildomų `yaml` konfigūracijų.
    Tai leidžia konteinerius greitai startuoti klasteryje.
    - https://www.katacoda.com/courses/kubernetes/kubectl-run-containers[Start containers using Kubectl]
  * Šiame scenarijuje sužinosite, kaip naudoti `Kubectl`, kad sukurtumėte ir startuotumėte diegimo, replikavimo valdiklius
    ir pateiktumėte juos per paslaugas (`Services`) aprašydami `yaml` apibrėžtis.
    `YAML` aprašo `Kubernetes` objektus.
    - https://www.katacoda.com/courses/kubernetes/creating-kubernetes-yaml-definitions[Deploy Containers Using YAML]
