Debesų kompiuterija

[.text-center]
=== Laboratorinis darbas nr. 3

[.text-center]
== Susipažinimas su Kubernetes platforma

[.text-left]
=== Darbo tikslas

* Išbandyti `Kubernetes` platformą
* Atlikti pagrindinius veiksmus su `Kubernetes` resursais.

[.text-left]
=== Užduotis

. Puslapyje *https://www.katacoda.com/courses/kubernetes[Learn Kubernetes using Interactive Browser-Based Labs | Katacoda]* susikurkite paskyrą.
. Atlikite šias užduotis:
  * Čia naudosite `minicube` -- tai įrankis, kuriuo lengva pakeisti _Kubernetes_.
    `minicube` paleidžia vieno mazgo _Kubernetes_ klasterį virtualioje mašinoje nešiojamame kompiuteryje naudotojams, 
    norintiems išbandyti _Kubernetes_ arba kurti su ja kasdien:
    - https://www.katacoda.com/courses/kubernetes/launch-single-node-cluster[Launch Single Node Kubernetes Cluster]
  * Šiame scenarijuje sužinosite, kaip naudoti `kubectl`, 
    kad sukurtumėte ir paleistumėte diegimo, replikavimo valdiklius 
    ir pateiktumėte juos per paslaugas (angl. _Services_) be papildomų `yaml` konfigūracijų.
    Tai leidžia konteinerius greitai startuoti klasteryje.
    - https://www.katacoda.com/courses/kubernetes/kubectl-run-containers[Deploy Containers Using Kubectl]
  * Šiame scenarijuje sužinosite, kaip naudoti `kubectl`, kad sukurtumėte ir startuotumėte diegimo, replikavimo valdiklius
    ir pateiktumėte juos per paslaugas (angl. _Services_) aprašydami `yaml` apibrėžtis.
    `YAML` aprašo _Kubernetes_ objektus.
    - https://www.katacoda.com/courses/kubernetes/creating-kubernetes-yaml-definitions[Deploy Containers Using YAML]
  * Šiame scenarijuje paaiškinama, kaip paleisti paprastą daugiapakopę žiniatinklio programą naudojant _Kubernetes_ ir _Docker_:
    - https://www.katacoda.com/courses/kubernetes/guestbook[Deploy Guestbook example on Kubernetes]

Ataskaitos turinys:

  * Aprašyti pasiekti  rezultatai kiekvienoje užduotyje.
  * Failo dydis < 5 MiB, formatas `PDF`.
