Debesų kompiuterija

[.text-center]
=== Laboratorinis darbas nr. 4

[.text-center]
== Automatizavimas `Ansible` pagalba

[.text-left]
=== Darbo tikslas

* Išbandyti `Ansible` įrankį.

[.text-left]
=== Prisijungimai

==== Prie serverio nr. 1 (iš asmeninio tinklo) 
|===
  | Service  | Username  | TCP port         | IP                | Hostname

  | SSH      | `stud`    | `45**x**22` ^*^  | `158.129.200.236` | `cc-lab`
|===

^*^ -- `**x**` reikšmę rasite žemiau:

==== Prie serverio nr. 2 (iš serverio nr. 1)
|===
  | `**x**` | Studentas                        | Service  | Username     | TCP port  | IP                 | Hostname

  | 1       | Šarūnas Budrevičius           .8+| SSH   .8+| `stud`    .8+| `22`      | `10.128.67.13`  .8+| `cc-lab`
  | 2       | Areta Jaškūnaitė                                                       | `10.128.67.21`               
  | 3       | Darius Jelinskij                                                       | `10.128.67.14`               
  | 4       | Edgar Kalinovski                                                       | `10.128.67.17`               
  | 5       | Saulius Krasuckas                                                      | `10.128.67.20`               
  | 6       | Andrius Kęstutis Stanaitis                                             | `10.128.67.20`               
  | 7       | Povilas Stepkovičius                                                   | `10.128.67.16`               
  | 8       | Gediminas Zinkus                                                       | `10.128.67.18`               
|===


[.text-left]
=== Užduotis

. Prisijunkite prie jūsų **serverio nr. 1**
. Atlikite šias užduotis:
  * Atsinaujinkite:  +
    `sudo apt update`
  * Įdiekite `Ansible`:  +
    `sudo apt install ansible`
  * Užtikrinkite, kad **serveris nr. 1** pasiektų **serverį nr. 2** naudojantis SSH raktais  +
    (https://www.digitalocean.com/community/tutorials/how-to-set-up-ssh-keys-on-ubuntu-20-04[How to Set Up SSH Keys])

=== _Inventory failo paruošimas:_

Inventoriaus faile pateikiama informacija apie mašinas, kurias valdysite naudodami `Ansible`.
Į inventoriaus failą galite įtraukti nuo vieno iki kelių šimtų serverių, 
o prieglobos kompiuterius (angl. _Remote computers_ ar _hosts_ ?) galima suskirstyti į grupes ir pogrupius.

Inventoriaus failas taip pat dažnai naudojamas nustatyti kintamiesiems, kurie galios tik tam tikriems prieglobos kompiuteriams arba grupėms, 
kad juos būtų galima naudoti grojaraščiuose (angl. _Playbooks_ ?) ir šablonuose (angl. _Templates_ ?).

Inventoriaus failas yra `/etc/ansible/hosts`.  Jis pasiekiamas pvz. taip:  +

* `sudo nano /etc/ansible/hosts`

Įdiegiant `Ansible` pateikiamas ir numatytasis inventoriaus failas.
Jame yra keletas pavyzdžių, kuriais galite remtis nustatydami inventorių.

Toliau pateiktame pavyzdyje apibrėžiama grupė pavadinimui `[serveriai]`.
Joje yra trys skirtingi serveriai, kiekvienas identifikuojamas pasirinktiniu slapyvardžiu:
`server1`, `server2`, `server3`.
Būtinai pakeiskite paryškintus IP adresus savo `Ansible` mašinų IP adresais:

```
[servers]
server1 ansible_host=20.0.13.11
server2 ansible_host=20.0.13.12
server3 ansible_host=20.0.13.13
```

Paruoškite inventoriaus failą ir jame nurodykite Jums priskirtą serverį nr. 2.

Pasitikrinkite savo inventoriaus failą:

* `ansible-inventory --list -y`

=== _Tikrinimas:_

Sukūrėte inventoriaus failą, į kurį įtraukėte savo serverius (serverį).
Laikas patikrinti, ar `Ansible` gali prisijungti prie prie šių serverių per SSH.

=== _Nuotolinis komandų vykdymas:_



Ataskaitos turinys:

  * Aprašyti pasiekti rezultatai kiekvienoje užduotyje.
  * Failo dydis < 5 MiB, formatas `PDF`.

<<<

[.text-left]
=== Darbo eiga
