Debesų kompiuterija

[.text-center]
=== Laboratorinis darbas nr. 2


[.text-center]
== Susipažinimas su Docker konteineriais


[.text-left]
=== Darbo tikslas

* Naudotis pagrindinėmis _Docker_ funkcijomis.
* Iš pirminio failo sukurti ir vykdyti konteinerio atvaizdį (angl. _Image).


[.text-left]
=== Įvadas. Kas yra _Docker_?

_Docker_ -- įrankis aplikacijų kūrimo, diegimo ir vykdymo palengvinimui, naudojantis konteinerizavimo principą.

Konteineriai įgalina kūrėjus supakuoti aplikaciją su visomis jai reikiamomis dalimis,
pvz. bibliotekomis ir kitais priklausomumais (angl. _Dependencies_),
ir išsiųsti ją diegimams kaip vientisą pakuotę.

Konteinerizavimo technologijos dėka šis būdas kūrėjui užtikrina,
kad aplikacija veiks bet kurioje kitoje _Linux_ mašinoje,
ir tas veikimas nepriklausys nuo jokių individualizuotų šios mašinos nustatymų (nuostatų), besiskiriančių atžvilgiu tos mašinos, kur aplikacija buvo kuriama ar testuojama.

Daugiau: <<1>>


[.text-left]
=== Užduotys

==== Užduotis nr. 1: **Prisijungimas prie Jūsų virtualaus serverio**


. Panaudokite SSH klientinę programą ir prisijunkite prie virtualaus serverio:
+
|===
      ^| Hostname   ^| Service    ^| IP                          +            ^| TCP port
  
  .2+.^| `cc-lab`    | SSH    .2+.^| {nbsp} `1~y~8.1~z~9.200.236` ^*^ {nbsp}      | `45~x~22` ^*^
                     | HTTP                                                       | `45~x~80` ^*^
|===
+
$$*$$  -- `~x~`, `~y~` ir `~z~` reikšmes pateiks dėstytojas.

. Jūsų laboratorinės aplinkos sujungimų diagrama:
+
image::https://raw.githubusercontent.com/VGTU-ELF/TETfm-20/main/Semestras-3/2-Debes%C5%B3-kompiuterija/laboratoriniai-darbai/LD2-pav1-laboratorin%C4%97-aplinka.svg[]


==== Užduotis nr. 2: **_Docker_ tyrinėjimas**

TODO

==== Užduotis nr. 3: **_Web_-serviso atvaizdžio sukūrimas pagal _Dockerfile_**

TODO

==== Ataskaitos turinys:

  * Aprašyti pasiekti  rezultatai kiekvienoje užduotyje.
  * Iliustracija, kad Jūsų tinklalapis pasiekiamas internetu.
  * Laikykitės principo: _Less is more_. Svarbu kokybė.
  * Išlaikykite vienodą stilių.
  * Failo dydis < 5 MiB, formatas `PDF`, talpinimo vieta: _Moodle_.


[bibliography]
==== Nuorodos

`2020<04-01` **[[[1]]]** `opensource.com`, (atnaujinta) Red Hat, Inc. https://opensource.com/resources/what-docker[What is Docker?]
