Duomenų centrai

== Laboratorinis darbas nr. 3: +++<br />+++ DC išskiriamos šilumos skaičiavimas

=== Darbo tikslas

Išmokti suskaičiuoti DC išskiriamą šilumos kiekį.

=== Bendra informacija

Visi elektros įrenginiai išskiria šilumą, kurią reikia šaltinti, kad įrangos temperatūra neviršytų priimtino lygio.
Dauguma informacinių technologijų (IT) įrangos ir kitos įrangos, esančios DC ar tinklo patalpoje, yra aušinama oru.
Norint nustatyti, aušinimo sistemos dydį, reikia suprasti, kiek uždaroje erdvėje esanti įranga sukuria šilumos.

==== _Šiluminės galios matavimas_

Šiluma yra energija, kuri paprastai išreiškiama džauliais, BTU, tonomis ar kalorijomis.
Įprasti įrangos šilumos išėjimo rodikliai yra:

  * BTU per valandą, 
  * tonos per dieną ir 
  * džauliai per sekundę (lygūs vatams).

Nėra jokios įtikinamos priežasties, kodėl visi šie skirtingi matai naudojami, tačiau bet kuris iš jų gali būti naudojamas galios ar vėsinimo pajėgumams išreikšti.
Mišrus šių matų naudojimas sukelia daug beprasmiškos painiavos naudotojams ir specifikacijų rengėjams.

Laimei, standartus nustatančiose organizacijose pastebima pasaulinė tendencija visus galios ir aušinimo pajėgumų matavimus perkelti į bendrą standartą -- vatus.
Laikui bėgant bus atsisakyta archaiškų BTU ir tonos terminų.
Dėl šios priežasties aušinimo ir galios pajėgumai toliau bus aptariami vatais.

==== Konvertavimo lentelė
|===

| Matavimo vienetas | Daugiklis | Norime

|===

=== Visos sistemos šiluminės galios nustatymas

=== Pavyzdys

=== Užduotis

Suskaičiuoti išskiriamą šilumos kiekį duomenų centre, kuris:

  * yra 70 m^2 dydžio;
  * jam aptarnauti nereikia daugiau nei 2 darbuotojų;
  * yra 30 spintų, kurių dydis 42U, o projektinė spintos galia 9 kW;
  * kiekvienos spintos duomenų centre užpildymas siekia 33%.

Apkrovimui skaičiavimui pasinaudokite internete rasta ir jūsų pasirinkto serverio specifikacija bei joje nurodytais maitinimo šaltinio duomenimis.

Pakomentuokite savo pasirinkimą ir kokią įtaką jis daro skaičiavimams.

=== Parenkite trumpą ataskaitą, kurioje:

  * Bus pateiktas skaičiavimo rezultatas;
  * Bus pateiktas informatyvus sukuriamos informacijos (informacinis šilumos?) grafikas;
  * Bus pateikta informacija apie pasirinktą serverį;
  * Laikysitės principo: _Less is more_.  Svarbu kokybė;
  * Išlaikykite vienodą stilių.

=== Parengtą ataskaitą .pdf formatu įkelkite į _Moodle_ sistemą.

<<<

[.text-left]
=== Eiga

. TODO
