Duomenų centrai

== Laboratorinis darbas nr. 3: +++<br />+++ DC išskiriamos šilumos skaičiavimas

=== Darbo tikslas

Išmokti suskaičiuoti DC išskiriamą šilumos kiekį.

=== Bendra informacija

Visi elektros įrenginiai išskiria šilumą, kurią reikia šaltinti, kad įrangos temperatūra neviršytų priimtino lygio.
Dauguma informacinių technologijų (IT) įrangos ir kitos įrangos, esančios DC ar tinklo patalpoje, yra aušinama oru.
Norint nustatyti, aušinimo sistemos dydį, reikia suprasti, kiek uždaroje erdvėje esanti įranga sukuria šilumos.

=== Visos sistemos šiluminės galios nustatymas

=== Pavyzdys

=== Užduotis

Suskaičiuoti išskiriamą šilumos kiekį duomenų centre, kuris:

  * yra 70 m^2 dydžio;
  * jam aptarnauti nereikia daugiau nei 2 darbuotojų;
  * yra 30 spintų, kurių dydis 42U, o projektinė spintos galia 9 kW;
  * kiekvienos spintos duomenų centre užpildymas siekia 33%.

Apkrovimui skaičiavimui pasinaudokite internete rasta ir jūsų pasirinkto serverio specifikacija bei joje nurodytais maitinimo šaltinio duomenimis.

Pakomentuokite savo pasirinkimą ir kokią įtaką jis daro skaičiavimams.

=== Parenkite trumpą ataskaitą, kurioje:

  * Bus pateiktas skaičiavimo rezultatas;
  * Bus pateiktas informatyvus sukuriamos informacijos (informacinis šilumos?) grafikas;
  * Bus pateikta informacija apie pasirinktą serverį;
  * Laikysitės principo: _Less is more_.  Svarbu kokybė;
  * Išlaikykite vienodą stilių.

=== Parengtą ataskaitą .pdf formatu įkelkite į _Moodle_ sistemą.

<<<

[.text-left]
=== Eiga

. TODO
