Duomenų centrai

== Laboratorinis darbas nr. 3: +++<br />+++ DC išskiriamos šilumos skaičiavimas

=== Darbo tikslas

Išmokti suskaičiuoti DC išskiriamą šilumos kiekį.

=== Bendra informacija

Visi elektros įrenginiai išskiria šilumą, kurią reikia šaltinti, kad įrangos temperatūra neviršytų priimtino lygio.
Dauguma informacinių technologijų (IT) įrangos ir kitos įrangos, esančios DC ar tinklo patalpoje, yra aušinama oru.
Norint nustatyti, aušinimo sistemos dydį, reikia suprasti, kiek uždaroje erdvėje esanti įranga sukuria šilumos.

==== _Šiluminės galios matavimas_

Šiluma yra energija, kuri paprastai išreiškiama džauliais, BTU, tonomis ar kalorijomis.
Įprasti įrangos šilumos išėjimo rodikliai yra:

  * BTU per valandą, 
  * tonos per dieną ir 
  * džauliai per sekundę (lygūs vatams).

Nėra jokios įtikinamos priežasties, kodėl visi šie skirtingi matai naudojami, tačiau bet kuris iš jų gali būti naudojamas galios ar vėsinimo pajėgumams išreikšti.
Mišrus šių matų naudojimas sukelia daug beprasmiškos painiavos naudotojams ir specifikacijų rengėjams.

Laimei, standartus nustatančiose organizacijose pastebima pasaulinė tendencija visus galios ir aušinimo pajėgumų matavimus perkelti į bendrą standartą -- vatus.
Laikui bėgant bus atsisakyta archaiškų BTU ir tonos terminų.
Dėl šios priežasties aušinimo ir galios pajėgumai toliau bus aptariami vatais.

==== Konvertavimo lentelė
|===

| Matavimo vienetas | Daugiklis | Norime gauti
| BTU/h             | 0,293     | vatus (W)
| Vatai (W)         | 3,41      | BTU/h
| Tonos             | 3,53      | Vatus (W)
| Vatai (W)         | 0,000283  | Tonos

|===

Visa iš kintamos srovės elektros (AC) tinklo suvartojama energija iš esmės paverčiama šiluma.
Dėl šios priežasties IT įrangos šiluminė galia vatais yra tiesiog lygi jos suvartojamai energijai vatais.
BTU per valandą, kaip kartais nurodoma duomenų lapuose, nėra būtina nustatant šiluminę įrangos galią.
Šiluminė galia yra tiesiog tokia pati, kaip suvartojama galia.

=== Visos sistemos šiluminės galios nustatymas

Bendra sistemos šiluminė galia yra sudedamųjų dalių šiluminės galios suma.
Visą sistemą sudaro IT įranga ir kiti elementai, UPS, energijos skirstymo įrenginiai (PDU), oro kondicionieriai, apšvietimas ir žmonės.
Laimei, šių elementų šiluminės galios rodiklius galima lengvai nustatyti naudojant paprastas ir standartizuotas taisykles.

UPS ir maitinimo paskirstymo sistemų šiluminę galią sudaro fiksuoti nuostoliai ir nuostoliai, proporcingi darbinei galiai.
Šie nuostoliai yra pakankamai vienodi įvairių prekės ženklų ir modelių įrangai, todėl juos galima apytiksliai apskaičiuoti be didelių paklaidų.
Apšvietimą ir žmones taip pat galima lengvai įvertinti naudojant standartines vertes.
Vienintelė informacija, kurios reikia visos sistemos vėsinimo apkrovai nustatyti, yra kelios lengvai prieinamos vertės, pavyzdžiui: grindų plotas kvadratiniais metrais ir vardinė  elektros sistemos galia.

Ventiliatoriai ir kompresoriai oro kondicionavimo įrenginiuose išskiria daug šilumos.
Ši šiluma yra išleidžiama į išorę ir nesukuria šiluminės apkrovos duomenų centre.
Tačiau ji yra, mažina oro kondicionavimo sistemos efektyvumą ir paprastais į ją atsižvelgiama, kai _<oro?>_ oro kondicionieriaus dydis.

Galima atlikti išsamią šiluminę analizę naudojant kiekvieno DC elemento šiluminės galios duomenis, tačiau atlikus greitą įvertinimą pagal paprastas taisykles, gaunami rezultatai, kurie neviršija tipinės paklaidos, būdingos labiau sudėtingai analizei.
Greito įvertinimo privalumas yra ir tas, kad jį gali atlikti bet kas, neturėdamas specialių žinių ar apmokymų.

=== Pavyzdys

=== Užduotis

Suskaičiuoti išskiriamą šilumos kiekį duomenų centre, kuris:

  * yra 70 m^2 dydžio;
  * jam aptarnauti nereikia daugiau nei 2 darbuotojų;
  * yra 30 spintų, kurių dydis 42U, o projektinė spintos galia 9 kW;
  * kiekvienos spintos duomenų centre užpildymas siekia 33%.

Apkrovimui skaičiavimui pasinaudokite internete rasta ir jūsų pasirinkto serverio specifikacija bei joje nurodytais maitinimo šaltinio duomenimis.

Pakomentuokite savo pasirinkimą ir kokią įtaką jis daro skaičiavimams.

=== Parenkite trumpą ataskaitą, kurioje:

  * Bus pateiktas skaičiavimo rezultatas;
  * Bus pateiktas informatyvus sukuriamos informacijos (informacinis šilumos?) grafikas;
  * Bus pateikta informacija apie pasirinktą serverį;
  * Laikysitės principo: _Less is more_.  Svarbu kokybė;
  * Išlaikykite vienodą stilių.

=== Parengtą ataskaitą .pdf formatu įkelkite į _Moodle_ sistemą.

<<<

[.text-left]
=== Eiga

. TODO
