Duomenų centrai

== Laboratorinis darbas nr. 4: +++<br />+++ IT įrangos išdėstymas DC

=== Darbo tikslas

Suprojektuoti IT įrangos įšdėstymą duomenų centre.

=== Bendra informacija

Dauguma naudotojų nustema sužinoję, kad DC elektros energijos suvartojimui didelę įtaką daro įrangos išdėstymas.
Taip yra todėl, kad išdėstymas turi reikšmę aušinimo sistemos efektyvumui.
Tai ypač pasakytina apie tradicinius perimetrinio aušinimo būdus.

IT įrangos išdėstymas:

* turi įtakos grįžtančiai temperatūrai į aušinimo įrenginius, 
o netinkamas išdėstymas lemia žemesnę grįžtančio oro temperatūrą.
Dėl žemesnės grįžtančio oro temperatūros sumažėja efektyvumas.

* turi įtakos reikiamai oro tiekimo į aušinimo įrenginius temperatūrai,
o blogas išdėstymas lemia, kad oro temperatūra yra žemesnė už reikiamą.
Išdėstymas reikalauja žemesnės temperatūros, kad būtų užtikrinta ir išlaikoma reikalinga temperatūra prie IT apkrovos.
Žemesnė nei reikalinga aušinimo sistemos tiekiamo oro temperatūra mažina vėsinimo įrenginių efektyvumą ir verčia juos sausinti orą, 
o tai savo ruožtu didina energijos reikalaujančio drėkinimo poreikį.

* turi įtakos aušinimo sisetmos oro srauto kiekiui, kuris turi būti naudojamas "maišant" DC orą, kad būtų suvienodinta temperatūra visoje patalpoje.
Dėl netinkamo išdėstymo reikia papildomos maišymo ventiliatoriaus galios, o tai mažina efektyvumą,
ir gali prireikti papildomų aušinimo įrenginių, kurie sunaudoja dar daugiau elektros energijos.

=== Bendri principai

Kadangi kompiuterių spinta (angl. _Rack_) yra pagrindinis išdėstymo elementas, galima taikyti standartizuotą grindų planavimo metodą.
Pagrindiniai principai apibrendinami tapi:
