Duomenų centrai

== Laboratorinis darbas nr. 6: +++<br />+++ DC ugniasienės

=== Darbo tikslas

Susipažinti su duomenų centrų (DC) ugniasienėmis.

=== Bendra informacija

==== Kas yra DC ugniasienė

DC užkarda -- programinės arba techninės įrangos įrenginys, kuris stebi srautą, patenkantį į organizacijos tinklą ir išeinantį iš jo,
arba (kai tinklo perimetras fragmentuotas) to tinklo dalį iki darbo krūvio lygio (angl. _Workload level_), kad būtų pašalintos išorinės grėsmės.

DC saugumas tradiciškai buvo grindžiamas perimetro ugniasiene, skirta apsaugoti visaus resursus nuo piktavalių išorės kenkėjų, pasislėpusių „Šiaurės–Pietų“ sraute.

Tačiau plintant paskirstytiesiems tinklams ir šiuolaikinėms taikomosioms programoms, tinklo perimetras tampa vis labiau išplėstas.
Todėl reikia sudėtingų paskirstytųjų ugniasienių, galinčių užtikrinti tikslią vidaus (arba „Rytų-Vakarų“) srauto stebėseną ir apsaugą.


==== Kodėl verta diegti DC ugniasienę?

Nepaisant to, kad vis dažniau naudojami debesijos ištekliai ir paskirstytieji darbuotojai, DC išlieka labai svarbus daugeliui, jei ne daugumai, įmonių.

==== DC ugniasienės privalumai
==== Kaip veikia DC ugniasienė

=== Užduotis

Parinkti ir apžvelgti ugniasienes.

Internete raskite bent dviejų skirtingų gamintojų naujos kartos DC ugniasienes (NGFW, angl. _Next-Generation Firewall_) ir jų specifikaciją (angl. _Data sheet_), pagal savo reikalavimus:
