Duomenų centrai

== Laboratorinis darbas nr. 7 (+8): +++<br />+++ Virtualizacija

=== Darbo tikslas

Artimiau susipažinti su virtualizacija ir paanalizuoti _Type-1_ hipervizorių.


=== Bendra informacija

(toliau anglų k.)


==== Terminai

Virtual Machine -- _[TODO]_

Hypervisor -- _[TODO]_


==== Intro

.


==== Virtualization for Server Consolidation and Containment

.


==== Types of hypervisor

.


=== Parenkite trumpą ataskaitą, kurioje:

* bus pateiktas Jūsų pasirinkto `I`-tipo hipervizoriaus pristatymas (pagrindinės funkcijos ir pan.)
* laikysitės principo: _Less is more_; svarbu kokybė.
* išlaikykite vienodą stilių.


=== Parengtą ataskaitą PDF formatu įkelkite į `Moodle` sistemą


<<<

[.text-left]
== Darbo eiga

Pasirenku apraše minimą _SmartOS_ hipervizorių.

Tiksliau, tai hipervizorinė platforma (OS).
Virtualių mašinų (toliau VMų) valdymui ji turi (geba naudoti) net du hipervizorius pasirinktinai:

* **KVM** (atportintas iš Linux branduolio);
* **bhyve** (atportintas iš FreeBSD branduolio).

Tiesą sakant, tai nėra tikri _Type I_ hipervizoriai:  +
https://www.serverwatch.com/virtualization/hypervisor-server/#:~:text=Linux%20KVM%20and%20FreeBSD%20bhyve

Jie abu startuoja ne iš „pliko metalo“, bet iš jau veikiančios įprastinės OS (Linux, FreeBSD, SmartOS).
Jie abu tą OS suspecializuoja: paverčia _Type I_ hipervizoriumi.

Tačiau kadangi ši OS yra bendros paskirties, pagal apibrėžimą tokį hipervizorių tinka laikyti ir _Type II_ hipervizoriumi.

Dėl to juos abu priskiriu _Type 1.5_ (dar vadinamai _Type 3_) kategorijai:  +
https://www.marksei.com/what-is-virtual-machine/#:~:text=called%20Type%2D3%20or%20Type%2D1.5

Pati _SmartOS_ yra distribucija _"illumos"_ sistemos, kadaise kilusios iš Solaris OS, ir yra klasikinė Unix OS.

Ji specializuota -- skirta tik VMų ir konteinerių startavimui bei valdymui:
