Duomenų centrai

== Laboratorinis darbas nr. 7 (+8): +++<br />+++ Virtualizacija

=== Darbo tikslas

Artimiau susipažinti su virtualizacija ir paanalizuoti _Type-1_ hipervizorių.


=== Bendra informacija

(toliau anglų k.)


==== Terminai

Virtual Machine -- _[TODO]_

Hypervisor -- _[TODO]_


==== Intro

.


==== Virtualization for Server Consolidation and Containment

.


==== Types of hypervisor

.


=== Parenkite trumpą ataskaitą, kurioje:

* bus pateiktas Jūsų pasirinkto `I`-tipo hipervizoriaus pristatymas (pagrindinės funkcijos ir pan.)
* laikysitės principo: _Less is more_; svarbu kokybė.
* išlaikykite vienodą stilių.


=== Parengtą ataskaitą PDF formatu įkelkite į `Moodle` sistemą


<<<

[.text-left]
== Darbo eiga

Pasirenku apraše minimą _SmartOS_ hipervizorių.

Tiksliau, tai hipervizorinė platforma (OS).
Virtualių mašinų (toliau VMų) valdymui ji turi (geba naudoti) net du hipervizorius pasirinktinai:

* **KVM** (atportintas iš Linux branduolio);
* **bhyve** (atportintas iš FreeBSD branduolio).

Tiesą sakant, tai nėra tikri _Type I_ hipervizoriai:  +
https://www.serverwatch.com/virtualization/hypervisor-server/#:~:text=Linux%20KVM%20and%20FreeBSD%20bhyve

Jie abu startuoja ne iš „pliko metalo“, bet iš jau veikiančio įprastinės OS (Linux, FreeBSD, SmartOS) branduolio.
Jie abu tą OS paverčia _Type I_ hipervizoriumi.

Tačiau kadangi ši OS yra bendros paskirties, pagal apibrėžimą tokį hipervizorių tinka laikyti ir _Type II_ hipervizoriumi.

Dėl aiškumo juos abu priskiriu _Type 1.5_ (dar vadinamai _Type 3_) kategorijai:  +
https://www.marksei.com/what-is-virtual-machine/#:~:text=called%20Type%2D3%20or%20Type%2D1.5

Pati _SmartOS_ yra distribucija _"illumos"_ sistemos, kadaise kilusios iš Solaris OS, ir yra klasikinė Unix OS.

Ji specializuota -- skirta tik VMų ir konteinerių startavimui / valdymui:

* Užima mažai vietos (kelis šimtus MiB):
  - [TODO] naudokime _Ansible_ ar kt.
  - => sparti keltis (įkrova), ~30s
  - => sumažintas atakų perimetras
* Skirta kelčiai iš R/O atvaizdo (_Live image_) ar bent ne diskinės medijos:
  - per PXE (tinklu)
  - iš USB Flash Disk (UFD)
  - iš CD-ROM
  - _Host OS_ nenaudoja lokalių diskų
  - => padidintas atsparumas sisteminio disko gedimams
  - => supaprastėja „diegimas“, ypač turint daug mašinų
  - => spartus atnaujinimas (pakanka tinklu nusikopijuoti bendrą atvaizdą + _Reboot_)
  - => daugiau vietos diskuose lieka _Guest OS_ egzemplioriams
  - => dar labiau sumažintas atakų perimetras
* _Live OS_:
  - _root_ failų sistema (FS) laikoma RAMe
  - FS pakeitimai arba neįmanomi (R/O), arba efemeriniai (`/etc`)
  - (išskyrus keletą svarbių direktorijų ir failų, atvirų rašymui; gal pvz.?)
  - => neveikia naujų vartotojų kūrimas
  - => neveikia `/usr` failų keitimas
  - => dar labiau sumažintas atakų perimetras
* Visi serverio lokalūs diskai apjungiami į vieną grupę (_pool_) pagal RAIDZ:
  - schema panaši į RAID 5/6/7
  - => padidinta I/O sparta ir patikimumas
* Naudoja dvigubą virtualizaciją:
  - https://www.joyent.com/blog/reintroducing-bhyve#:~:text=This%20is%20what%20we%20mean%20when%20we%20say%20double%2Dhulled%2Dvirtualization[double-hulled-virtualization] -- Guest OS VMM procesas konteineryje
  - => dar labiau sumažintas atakos perimetras
  - => unifikuotas konteinerių ir VMų valdymas (`vmadm`)

[TODO:]

https://klarasystems.com/articles/bhyve-the-freebsd-hypervisor/

- Modernus kodas, Mažas Overhead, Spartus
- Solaris/illumos projektuotas didesniam (apskritai) saugumui nei Linux, ir tai juntama
- Palaiko labai įvairius Storage backend-us
- ZFS privalumai: akimirksniniai klonai, šifravimas (jei reikia, ir deduplikacija)
- PCI pass-through

https://bhyvecon.org/bhyvecon2018-Gwydir.pdf

- _Guest OS_ tik UEFI?
- net antispoofing built-in
- cloud-init


Trūkumai:

https://www.youtube.com/watch?v=uV61mVYsFM8

- kol kas tik x86 (no ARM)
- kiek vėlokai žengė į rinką (2011-2013 m.), todėl mažoka rinka
- valdoma per CLI, JSON ir truputį YAML (norint GUI reiktų naudoti Triton)
- rinkodaros strategija dar tik kuriama, ji kinta (todėl kitur stipresnės adminų ir jūzerių bendruomenės)

- VGA tik per VNC?

https://docs.google.com/document/d/1PFUmz6XpTVAGkq5dBe8uaBFV2Y4i-uR88AuiCLIRxIQ/edit

- dar tik kuriamas VM Cold/Warm/Live Migration
