Duomenų centrai

== Laboratorinis darbas nr. 7 (+8): +++<br />+++ Virtualizacija

=== Darbo tikslas

Artimiau susipažinti su virtualizacija ir paanalizuoti _Type-1_ hipervizorių.


=== Bendra informacija

(toliau anglų k.)


==== Terminai

Virtual Machine -- _[TODO]_

VMM, Virtual machine manager -- _[TODO]_

Hypervisor -- _[TODO]_


==== Intro

.


==== Virtualization for Server Consolidation and Containment

.


==== Types of hypervisor

.


=== Parenkite trumpą ataskaitą, kurioje:

* bus pateiktas Jūsų pasirinkto `I`-tipo hipervizoriaus pristatymas (pagrindinės funkcijos ir pan.)
* laikysitės principo: _Less is more_; svarbu kokybė.
* išlaikykite vienodą stilių.


=== Parengtą ataskaitą PDF formatu įkelkite į `Moodle` sistemą


<<<

[.text-left]
== Darbo eiga

Apžvalgai pasirenku dedikuotą **SmartOS** hipervizorių, minimą laboratorinio darbo apraše.


=== Kas yra SmartOS ?

Kalbant tiksliau, tai konverguota hipervizorinė operacijų sistema (OS).

Tai distribucija ne populiarios Linux OS, bet mažiau žinomos _"illumOS"_ sistemos (2010 m. kilusios iš Solaris OS), ir yra klasikinė Unix OS.
Lyginant su Linux, ji turi gerokai stabilesnę architektūrą.


==== Du hypervizoriai kartu

Virtualių mašinų (toliau: VMų) valdymui SmartOS siūlo du skirtingus hipervizorius pasirinktinai:

* **KVM**  <<21>> psl. 5 + 14   +
  (gana senos Linux 2.6.34 versijos VMM + senos _Qemu_ 0.14.1 versijos emuliatoriaus portas, 2011 m.);  +
* **bhyve**  <<24>> psl. 6  +
  (gana naujos FreeBSD 11.1 versijos VMM portas, 2017 m.)

Tiesą sakant, jie abu nėra gryni _Type I_ hipervizoriai. <<1>>

Jie abu startuoja ne „plikame metale“, bet jau veikiančioje įprastinėje OS (Linux, FreeBSD, SmartOS).
Ir jie abu tą OS paverčia _Type I_ hipervizoriumi, suspecializuoja.

Tačiau kadangi tokia OS tinka ir bendros paskirties naudojimui, pagal apibrėžimą tokį hipervizorių priimtina laikyti ir _Type II_ hipervizoriumi.

Dėl aiškumo juos abu priskiriu hibridinei _Type 1.5_ (dar vadinamai _Type 3_) kategorijai. <<2>>


==== Abiejų hypervizorių palyginimas

* **KVM**:
 ** Gana paplitęs VM mechanizmas / interfeisas;
 ** SmartOS KVM implementacija neleidžia plėsti VM resursų: diskų, CPU, RAM;  +
    (tenka VM perkurti iš naujo ir perkelti aplikacijos duomenis)
 ** palaiko iki 256 vCPU / VM;  <<25>>
 ** palaiko iki 2 TiB RAM / VM;
 ** su _illumOS_ išeities kodu nesuderinama `GPL` licencija;  <<29>> +
    (Todėl SmartOS KVM vystomas kaip atskiras projektas)
 ** Linux branduolys ir KVM yra „judantis taikinys“ su kitokia architektūra nei illumOS sistema.  +
    Į pastarąją pastoviai atkelti naujus pakeitimus būtų itin daug darbo.  +
    Todėl SmartOS KVM implementacija neanaujinama.

* **bhyve**:
 ** _bhyve_ kilo kitoje OS, _FreeBSD_, ir naujas funkcijos ten atsiranda anksčiau / greičiau;  <<8>>
 ** palaiko šiek mažiau OSų / OS atvaizdų;
 ** palaiko tik 16 vCPU / VM;  <<26>>
 ** implementuoja UEFI platforminį interfeisą:
  *** palaikomi tik su UEFI suderinami _Guest OS_;  <<28>>
  *** nepalaiko tiesioginės, neemuliuotos _Legacy_ BIOS / Boot-ROM kelties;  <<24>> psl. 12
  *** todėl kai kuriems OS tenka turėti po skirtingą atvaizdą kiekvienam hipervizoriui;
 ** modernus kodas, mažas _Overhead_
 ** didesnis našumas (angl. _Performance_);
 ** stipresnis pajėgumų dauginamumas (angl. _Scalability_);
 ** integracija su `ZFS`:
   - akimirksniniai duomenų (FSų) klonai
   - duomenų šifravimas (jei reikia)
   - ir jų deduplikacija (jei reikia)
 ** palaiko _labai_ įvairius Storage backend-us
 ** _PCI pass-through_ galimybė;  <<13>> psl. 10
 ** integruotas `net antispoofing` mechanizmas;  <<9>> psl. 11
 ** su _illumOS_ išeities kodu ("CDDL") tiesiogiai suderinama licencija ("Simplified BSD License") leidžia integruoti `bhyve` kodą tiesiogiai į branduolį;  +
 ** SmartOS dabar _bhyve_ yra naudojamas pagal nutylėjimą.

Kadangi apie populiarų KVM tikėtinai rašys kiti grupiokai (o be to, SmartOS naudoja senoką KVM versiją), toliau akcentuoju SmartOS + _bhyve_ VMM kombinaciją.


=== Ką SmartOS siūlo ?

Pati SmartOS yra specializuota OS -- skirta tik Guest OS startavimui / valdymui, ir niekam kitam.

* Užima mažai vietos (kelis šimtus MiB):
 ** => sparti keltis (įkrova), ~30s
 ** => sumažintas atakų perimetras
 ** Nodų priežiūrai rekomenduojama naudoti _Chef_ (gamintojo rekomenduojamiausią), _Ansible_ ar kt. _Configuration Management_ sistemą. <<3>>
* Skirta kelčiai iš R/O atvaizdo (_Live image_) ar bent ne diskinės medijos:
 ** per PXE (tinklu)
 ** iš USB Flash Disk (UFD)
 ** iš CD-ROM
 ** _Host OS_ nenaudoja lokalių diskų
  - => padidintas atsparumas sisteminio disko gedimams
  - => supaprastėja „diegimas“, ypač turint daug mašinų (vos keli nustatymai) <<4>>
  - => spartus atnaujinimas  +
       (pakanka tinklu nusikopijuoti bendrą OS atvaizdą + _Reboot_)
    *** kaskart per PXE
    *** vieną sykį į UFD per SSH
  - => daugiau vietos diskuose lieka _Guest OS_ egzemplioriams
* _in-memory_ / _Live OS_:
 ** _root_ failų sistema (FS) laikoma RAMe
 ** FS pakeitimai arba neįmanomi (R/O), arba efemeriški (`/etc`) <<5>>  +
    (išskyrus keletą svarbių direktorijų ir failų, atvirų rašymui; gal pvz.: ?)
  - => neveikia naujų vartotojų kūrimas
  - => `/usr` failai primontuoti R/O
  - => dar labiau sumažintas atakų perimetras
* Visi serverio lokalūs diskai apjungiami į vieną grupę (_pool_):
 ** apjungimas _programinis_
 ** apjungiama pagal RAIDZ
 ** schema panaši į RAID 5/6/7
  - => padidinta diskų I/O sparta ir patikimumas
 ** tinkliniai diskai nenaudojami
* Siūlo iškart du virtualizacijos lygius:
 ** OS lygis (konteineriai), labai efektyvus;  +
    Guest OS:  <<30>>
  *** Linux distribucijų atvaizdai:
    - => CentOS 7: 20180323
    - => CentOS 6: 20170407
    - => Alpine 3: 20170303
    - => Debian 9: 20180404
    - => Debian 8: 20170214
    - => Debian 7: 20161213
    - => Ubuntu 16.04: 20170403
    - => Ubuntu 14.04: 20170403
  *** SmartOS Guest atvaizdai (_developer-friendly_).
    - => Base (švari aplinka, DIY)
    - => Apache
    - => Brocade Virtual Traffic Manager (vTM)
    - => Cassandra
    - => Ghost
    - => Java
    - => Minimal
    - => MongoDB
    - => MySQL Cluster
    - => Nginx
    - => Node.js
    - => Pkgbuild
    - => Percona
    - => Percona Cluster
    - => PostgreSQL
    - => Redis
    - => Standard (Web-development)
 ** „geležies“ lygis (virtualios mašinos, VM), labai izoliuotas;  +
    Guest OS:  <<31>> (beveik visos populiariausios OS)
  - => Windows _desktop_ ir Windows Server versijos;
  - => Linux distribucijos;
  - => *BSD distribucijos;
  - => illumOS distribucijos (SmartOS, OmniOS);
  - => Plan9
* Naudoja ir dubliuotą virtualizaciją:
 ** Guest OSą palaikantis VMM procesas (tiek `qemu-kvm`, tiek `bhyve`) veikia tik konteineryje;  +
    (_Double hulled virtualization_ patentas <<6>>)
  - => dar labiau sumažintas atakos perimetras;  <<9>> psl. 9
  - => preciziškas Guest OSų valdymas -- konteineris užtikrina QoS, resursų valdymą, I/O ribojimą (angl. _throttling_), apskaitą, kitą instrumentuotę;  <<21>> psl. 22
  - => apjungtas konteinerių bei VMų valdymas (komandos `vmadm`)
 ** Abu hipervizoriai, `KVM` ir `bhyve` geba veikti kartu -- vienu metu viename hoste aptarnauti savo atskirus VMus;  <<24>> psl. 8
* Host OS turi po atskirą įrankį:
 ** `imgadm` valdyti Guest OS atvaizdams
 ** `vmadm` valdyti Guest OS egzemplioriams
  - Guest aprašymui naudojamas JSON formatas;
 ** `dladm` valdyti OS tinklo interfeisams (L2, įskaitant jų virtualizavimą)
 ** `ipadm` valdyti OS potinkliams (L3)
 ** `fwadm` valdyti OS ugniasienei (L2 - L4)
* Naudoja tarpplatforminį paketų valdiklį `pkgsrc` (kilusį NetBSD sistemoje).


Dalis šių savybių išplaukia iš **griežtai lokalios** Host nodų **talpyklinės architektūros**. <<23>>

Tai reiškia, kad kiekviename Host node VMai saugomi tik lokaliuose diskuose ir startuoja ne iš NAS ar SAN tinklo.

Tokia architektūra lemia neitin tipinį hipervizoriaus panaudojimo scenarijų (mažiau kompleksišką nei pvz. rinkos lyderis VMware _ESXi_):

* Atkrinta _Storage_ tinklo įnešamas vėlinimas;
* Išauga nodų I/O nepriklausomumas;
* _High-availability_ (HA) / _Fault tolerance_ (FT) tenka projektuoti _Application_ lygmenyje;  <<27>>
* _Live Migration_ sunkiau įgyvendinamas;
* _Live Migration_ lėtesnis.  +
  (Duomenų suvienodinimas tarp lokalių talpyklų „suvalgo“ dalį LAN pralaidumo).

Kaip jau paminėta, šis hipervizorius naudoja tiek OS konteinerius 
Guest OS valdymas yra konverguotas -- ir VMai, ir OS konteineriai valdomi vienu įrankiu.


=== Kokius DC/IT uždavinius SmartOS sprendžia ?

Sprendžia ir įprastus virtualizavimo uždavinius, ir keletą naujų:

- Kadangi greta VM virtualizacijos SmartOS naudoja dar ir lanksčią savo konteinerių architektūrą (angl. Cloud-native).
Bent anksčiau (2013 m.) ji leisdavo SmartOS pagrindu veikiantiems „debesims“ drąsiai atlaikyti staigų apkrovų šuolį per kelias dešimtis tūkstančių KAV (kasdienių aktyvių vartotojų), kai tuo metu kitos architektūros tiesiog naudodavo 50% Overprovisioning.
https://www.joyent.com/blog/joyent-takes-gaming-companies-to-the-next-level#:~:text=dramatically%20reducing%20the%20cost%20per%20DAU

- Palaiko I/O pralaidumo paskirstymą tarp VMų Overprovisioning sumažinimui, VM tankio bei Host išnaudojamumo padidinimui:
https://www.joyent.com/blog/nodestack-is-nodejs-mongodb-and-smartos#:~:text=burstable%20IO%20sharing%20across%20VMs%20for%20less%20overprovisioning


==== Įprasti virtualizavimo uždaviniai

- ar VM migruojami tarp hostų klasteryje?

Taip: ...

- migracija be Downtime ar su?

Su trumpu Downtime: ...

- ar yra VMų snapšotai?

Tik VM diskinės atminties: ...

- ar yra globalus resursų ribojimas (pvz. užtikrinant DR rezervą)
- ar veikia Oversubscription?
- kaip skeilinasi?

..?

- kaip atliekamas DRas? 

..?


==== Ar SmartOS valdomas tiesiogiai, ar klasteriniu būdu ?

Kaip pavienis įrankis, SmartOS valdomas tiesiogiai.

REST ?

Tačiau daugianodžių SmartOS debesų valdymui siūlomas atskiras, irgi atvirojo kodo įrankis (angl. _Cloud management platform_) **Triton DataCenter** / **Triton Compute Service**, į kurio funkcijas irgi trumpai atsižvelgsiu. <<7>>

Jei norime kelti OSus tinklu, šiame įrankyje verta PXE mechanizmui dedikuoti atskirą hostą, vad. Head Node (HN).
Kiti pakeltieji hostai jau vadinsis Compute Node (CN).

https://docs.joyent.com/content/10-public-cloud/050-network/030-firewall/TCP_firewall_status.jpg
https://docs.joyent.com/content/20-private-cloud/060-networks/networks01.png

https://docs.joyent.com/content/20-private-cloud/triton01.png
https://docs.joyent.com/content/20-private-cloud/triton02.png

Jis įgalina centralizuotai:

* atlikti _Firewalling_ (OS vidinio mechanizmo IPFilter dėka): https://docs.joyent.com/public-cloud/network/firewall
* valdyti tinklus L2 (Fabric, VLAN, VNIC, per-container TCP/IP stack) ir L3 (IP subnets, VXLAN, antispoofing, routing, NAT) lygmenyse programiškai (SDN): https://docs.joyent.com/public-cloud/network/sdn

---

Pranašumai:

* _Solaris_ / _illumOS_ projektuotas didesniam saugumui (apskritai TODO patikimumui) nei Linux, ir naudojantis tai juntama tiesiogiai

* _VirtIO_ -- vieno efektyviausių paravirtualizacijos (PV) interfeisų palaikymas;  <<13>> psl. 10

* _cloud-init_ standarto palaikymas: <<19>>, <<20>>  +
 ** Įgalina debesų (egzempliorių) inicializavimą nepriklausomai nuo platformos, pvz.:
  *** OS vartotojų paskyrų sukūrimą
  *** programinių paketų sudiegimą
  *** Git repozitorijų nuklonavimą
  *** apskritai kone bet kuriuos OS administravimo veiksmus.
 ** Naudoja YAML sintaksę
  *** tenka ją suderinti su SmartOS `vmadm` naudojama JSON sintakse.
 ** Palaikomas:
  *** tiek visų didžiųjų viešos debesijos tiekėjų, 
  *** tiek atliekant OS provizijavimą ir privačiuose debesyse, 
  *** ir „plikoj geležy“ (angl. _Bare metal_).

---

Trūkumai:

* Kol kas palaiko tik _x86_ architektūrą (_no ARM_);  <<10>>

* Kol kas neveikia VM _Live Migration_ (dar tik kuriama);  +
  veikia tik VM _Warm / Cold Migration_;  <<11>>

* Guest OS VGA išvestis ribota ir pasiekiama tik VNC protokolu;

* Hostas valdomas per CLI, JSON ir truputį YAML (sąlyginis trūkumas).  +
  Norint GUI, reiktų naudoti papildomą įrankį: 
 ** debesinį orkestratorių _Triton_ arba 
 ** _Project FiFo_ (kai mažesnis ūkis ir vengiama dedikuoto HNo, _Head-node_).

* Kiek vėlokai žengė į rinką (2011-2013 m.), todėl kol kas užima mažoką jos dalį;

* Rinkodaros strategija dar tik kuriama, ji kinta;  +
  (todėl stipresnės kitų hipervizorių adminų ir jūzerių bendruomenės)

=== Ar SmartOS yra nišinis hipervizorius ?

Pagal rinkos dydį ir kai kuriuos trūkumus SmartOS gal ir tiktų vadinti nišiniu sprendimu.

Tačiau pagal siūlomą architektūrą SmartOS yra kaip tik inovatyvus, genialiai paprastas ir nemokamas atvirojo kodo sprendimas.

Ar tai hipervizorių daro labiau nišiniu, ar mažinau nišiniu -- požiūrio ir susitarimo klausimas.

---

Ankstesnės FreeBSD prezentacijos (apie komponentus):

- <<12>> Diagramos
- <<13>> Sąrašėlis

Apie Triton DataCenter + diagramos:

- Konteinerių ir VMų Combo diagramos: <<14>>
- Detalesnė Triton DC sudėtis: <<15>>
- Diagramos: https://wiki.smartos.org/smartos-virtualization/


Taikymo pavyzdžiai:

- Docker konteinerių startavimas be _Triton_ pagalbos; <<16>>
  (t. p. ir `fwadm` aprašymas)
- Asmeninio Docker registro naudojimas. <<17>>
- Orientavimasis į _Node.js_ servisus: <<18>>
- Deploying Kubernetes on SmartOS | Virtualization: How SmartOS Does it Differently ¶:
  https://www.youtube.com/watch?v=rA0pcmqpRx4



<<<

[bibliography]
=== Nuorodos

`2020-11-17` **[[[1]]]** `serverwatch.com`, Christine Taylor,  https://www.serverwatch.com/virtualization/hypervisor-server/#:~:text=Linux%20KVM%20and%20FreeBSD%20bhyve[What Is a Hypervisor Server?]

`2016-06-01` **[[[2]]]** `marksei.com`, Marksei, https://www.marksei.com/what-is-virtual-machine/#:~:text=called%20Type%2D3%20or%20Type%2D1.5[What is a Virtual Machine?]

`2021-12-15` **[[[3]]]** `smartos.org`, (peržiūrėta) https://wiki.smartos.org/configuration-management-on-smartos/[Configuration Management on SmartOS]

`2012-04-13` **[[[4]]]** `perkin.org.uk`, Jonathan Perkin, https://www.perkin.org.uk/posts/smartos-global-zone-tweaks.html[SmartOS global zone tweaks]

`2012-11-23` **[[[5]]]** `perkin.org.uk`, Jonathan Perkin, https://www.perkin.org.uk/posts/smartos-and-the-global-zone.html#:~:text=on%20running%20SmartOS.-,So%20what%20can%20I%20do%3F,-Firstly%2C%20let%E2%80%99s%20look[SmartOS and the global zone]

`2021-07-08` **[[[6]]]** `joyent.com`, Michael Zeller, https://www.joyent.com/blog/reintroducing-bhyve#:~:text=This%20is%20what%20we%20mean%20when%20we%20say%20double%2Dhulled%2Dvirtualization[Reintroducing Bhyve]

`2021-01-05` **[[[7]]]** `docs.joyent.com`, (redaguota) https://docs.joyent.com/private-cloud[Triton Operator Documentation]

`2020-09-03` **[[[8]]]** `klarasystems.com`, Allan Jude, https://klarasystems.com/articles/bhyve-the-freebsd-hypervisor/[bhyve | The FreeBSD Hypervisor]

`2018-03-05` **[[[9]]]** `bhyvecon.org`, Mike Gerdts, https://bhyvecon.org/bhyvecon2018-Gwydir.pdf[bhyve zones in SmartOS]

`2021-01-27` **[[[10]]]** `youtube.com`, Yaroslav Koisa, https://www.youtube.com/watch?v=uV61mVYsFM8[FreeBSD's Bhyve Overview: Why it's better than other hypervisors. At least for our use-case.]

`2021-07-01` **[[[11]]]** `docs.google.com`, Alan Jude, https://docs.google.com/document/d/1PFUmz6XpTVAGkq5dBe8uaBFV2Y4i-uR88AuiCLIRxIQ/[bhyve Weekly Call]

`2011-05-13` **[[[12]]]** `people.freebsd.org`, Neel Natu | Peter Grehan, https://people.freebsd.org/~neel/bhyve/bhyve_bsdcan_2011.pdf[BHyVe | BSD Hypervisor]

`2014-05-07` **[[[13]]]** `papers.freebsd.org`, John Baldwin, https://papers.freebsd.org/2014/baldwin-Introduction_to_bhyve.files/slides.pdf#page=6[Introduction to bhyve]

`2021-01-05` **[[[14]]]** `docs.joyent.com`, (redaguota) https://docs.joyent.com/public-cloud/instances[Triton End User Documentation › Containers and virtual machines ›]

`2021-07-14` **[[[15]]]** `github.com/joyent/triton`, 
https://github.com/joyent/triton/blob/master/README.md#overview[Triton DataCenter | README]

`2021-06-11` **[[[16]]]** `gaige.net`, Gaige B. Paulsen, https://www.gaige.net/docker-on-smartos.html[Docker on SmartOS]

`2018-02-11` **[[[17]]]** `cyber-tec.org`, Thomas Merkel, https://www.cyber-tec.org/2018/02/11/run-docker-images-on-smartos/[Run Docker images on SmartOS]

`2017-01-12` **[[[18]]]** `joyent.com`, Wyatt Preul, https://www.joyent.com/blog/microservices-containers-nodejs[Containers and microservices and Node.js! Oh, my!]

`2019-09-04` **[[[19]]]** `readthedocs.io`, (redaguota) https://cloudinit.readthedocs.io/en/latest/topics/datasources/smartos.html[cloud-init » Docs » Datasources » SmartOS Datasource]
-28 **[[[30]]]** `01-16` `
`2019-01-16` **[[[20]]]** `shaner.life`, Shaner, 
https://shaner.life/using-cloud-init-with-smartos/[Using cloud-init with SmartOS]

`2011-08-15` **[[[21]]]** `slideshare.net`, Bryan Cantrill, 
https://www.slideshare.net/bcantrill/experiences-porting-kvm-to-smartos/22[Experiences porting KVM to SmartOS]

`2012-06-29` **[[[22]]]** `github.com/joyent/illumos-kvm`, (redaguota) 
https://github.com/joyent/illumos-kvm/blob/master/README.md#illumos-kvm-kvm-for-illumos[illumos-kvm: KVM for illumos]

`2014-06-06` **[[[23]]]** `wikipedia.org`, (redaguota) Trentstersla, https://en.wikipedia.org/wiki/SmartOS#:~:text=SmartOS%20follows%20a%20strict%20local%20node%20storage%20architecture[SmartOS | "SmartOS follows a strict local node storage architecture"]

`2019-05-14` **[[[24]]]** `bhyvecon.org`, Patrick Mooney, 
https://bhyvecon.org/bhyveconOttawa2019-Patrick.pdf[Porting bhyve to SmartOS]

`2011-09-21` **[[[25]]]** `lwn.net`, Koen Vervloesem, https://lwn.net/Articles/459754/[SmartOS: virtualization with ZFS and KVM]

`2019-05-14` **[[[26]]]** `bhyvecon.org`, Rod Grimes, 
https://bhyvecon.org/bhyveconOttawa2019-Rodney.pdf#page=3[bhyve VM_MAXCPU cleanup | VM_MAXCPU]

`2015-12-08` **[[[27]]]** `lists.smartos.org`, Bryan Horstmann-Allen, https://www.mail-archive.com/smartos-discuss@lists.smartos.org.email.enqueue.archive.listbox.com/msg01707.html[Re: [smartos-discuss] High availability solutions with SmartOS]

`2018-12-26` **[[[28]]]** `gist.github.com`, Mike Gerdts, https://gist.github.com/mgerdts/10376cdbd8f015f422d61664408db2aa#file-1-guest-images-md[Bhyve Machine Images | UEFI and BIOS Emulation]

`2010-08-09` **[[[29]]]** `github.com/joyent/illumos-kvm`, https://github.com/joyent/illumos-kvm/blob/master/COPYING.linux[The KVM Project is derived from the Linux kernel]

`2021-04-28` **[[[30]]]** `docs.joyent.com`, (redaguota) https://docs.joyent.com/public-cloud/instances/infrastructure/images#:~:text=Container%20images%3A%20Table%20of%20Contents[Container images: Table of Contents]

`2021-12-10` **[[[31]]]** `wiki.freebsd.org`, Christos Margiolis, https://wiki.freebsd.org/bhyve#Q:_What_VM_operating_systems_does_bhyve_support.3F[bhyve | Q: What VM operating systems does bhyve support?]
