Duomenų centrai

== Laboratorinis darbas nr. 7 (+8): +++<br />+++ Virtualizacija

=== Darbo tikslas

Artimiau susipažinti su virtualizacija ir paanalizuoti _Type-1_ hipervizorių.


=== Bendra informacija

(toliau anglų k.)


==== Terminai

Virtual Machine -- _[TODO]_

VMM, Virtual machine manager -- _[TODO]_

Hypervisor -- _[TODO]_


==== Intro

.


==== Virtualization for Server Consolidation and Containment

.


==== Types of hypervisor

.


=== Parenkite trumpą ataskaitą, kurioje:

* bus pateiktas Jūsų pasirinkto `I`-tipo hipervizoriaus pristatymas (pagrindinės funkcijos ir pan.)
* laikysitės principo: _Less is more_; svarbu kokybė.
* išlaikykite vienodą stilių.


=== Parengtą ataskaitą PDF formatu įkelkite į `Moodle` sistemą


<<<

[.text-left]
== Darbo eiga

Pasirenku apraše minimą _SmartOS_ hipervizorių.

Tiksliau, tai konverguota hipervizorinė platforma (operacijų sistema, OS).
Virtualių mašinų (toliau VMų) valdymui ji turi (geba naudoti) du skirtingus hipervizorius pasirinktinai:

* **KVM** (gana senos Linux VMM versijos portas);
* **bhyve** (gana naujos FreeBSD VMM versijos portas).

Tiesą sakant, jie abu nėra gryni _Type I_ hipervizoriai. <<1>>

Jie abu startuoja ne iš „pliko metalo“, bet iš jau veikiančio įprastinės OS (Linux, FreeBSD, SmartOS) branduolio.
Ir jie abu tą OS paverčia _Type I_ hipervizoriumi, specializuoja.

Tačiau kadangi ši OS yra bendros paskirties, pagal apibrėžimą tokį hipervizorių tinka laikyti ir _Type II_ hipervizoriumi.

Dėl aiškumo juos abu priskiriu _Type 1.5_ (dar vadinamai _Type 3_) kategorijai. <<2>>

Pati _SmartOS_ yra distribucija _"illumOS"_ sistemos, kadaise kilusios iš Solaris OS, ir yra klasikinė Unix OS. 

Ji specializuota -- skirta tik konverguotam VMų ir konteinerių startavimui / valdymui:

* Užima mažai vietos (kelis šimtus MiB):
 ** => sparti keltis (įkrova), ~30s
 ** => sumažintas atakų perimetras
 ** Nodų priežiūrai rekomenduojama naudoti _Chef_ (gamintojo rekomenduojamiausią), _Ansible_ ar kt. _Configuration Management_ sistemą. <<3>>
* Skirta kelčiai iš R/O atvaizdo (_Live image_) ar bent ne diskinės medijos:
 ** per PXE (tinklu)
 ** iš USB Flash Disk (UFD)
 ** iš CD-ROM
 ** _Host OS_ nenaudoja lokalių diskų
  - => padidintas atsparumas sisteminio disko gedimams
  - => supaprastėja „diegimas“, ypač turint daug mašinų (vos keli nustatymai) <<4>>
  - => spartus atnaujinimas  +
       (pakanka tinklu nusikopijuoti bendrą OS atvaizdą + _Reboot_)
    *** kaskart per PXE
    *** vieną sykį į UFD per SSH
  - => daugiau vietos diskuose lieka _Guest OS_ egzemplioriams
* _Live OS_:
 ** _root_ failų sistema (FS) laikoma RAMe
 ** FS pakeitimai arba neįmanomi (R/O), arba efemeriški (`/etc`) <<5>>  +
    (išskyrus keletą svarbių direktorijų ir failų, atvirų rašymui; gal pvz.: ?)
  - => neveikia naujų vartotojų kūrimas
  - => `/usr` failai primontuoti R/O
  - => dar labiau sumažintas atakų perimetras
* Visi serverio lokalūs diskai _programiškai_ apjungiami į vieną grupę (_pool_):
 ** apjungiama pagal RAIDZ
 ** schema panaši į RAID 5/6/7
  - => padidinta diskų I/O sparta ir patikimumas
* Naudoja dubliuotą virtualizaciją:
 ** Guest OSą valdantis VMM procesas veikia tik konteineryje  +
    (_Double hulled virtualization_ patentas <<6>>)
  - => dar labiau sumažintas atakos perimetras
  - => unifikuotas OS atvaizdų ir konteinerių bei VMų valdymas (komandos `imgadm` ir `vmadm`)


Kadangi apie KVM tikėtinai rašys kiti grupiokai (o čia, be to, naudojama sena KVM versija), toliau nagrinėju SmartOS + bhyve VMM kombinaciją.

O kadangi pavienis įdiegtas _SmartOS_ egzempliorius nėra pakankamai lankstus, šios platformos (variklio) pagrindu buvo sukurta debesų valdymo (angl. _Cloud management_) platforma **Triton DataCenter** / **Triton Compute Service**:  +
https://docs.joyent.com/private-cloud

Taip pat atskirai apžvelgiu ir _bhyve_ hypervizorių, kilusį iš kitos OS ir ten anksčiau gaunantį naujas funkcijas:  +
https://klarasystems.com/articles/bhyve-the-freebsd-hypervisor/

- Modernus kodas, mažas _Overhead_, spartus
- Solaris/illumOS projektuotas didesniam (apskritai) saugumui nei Linux, ir tai juntama tiesiogiai
- Palaiko _labai_ įvairius Storage backend-us
- ZFS privalumai: akimirksniniai duomenų klonai, duomenų šifravimas (jei reikia, ir jų deduplikacija)
- _PCI pass-through_ galimybė

https://bhyvecon.org/bhyvecon2018-Gwydir.pdf

- _Guest OS_ tik UEFI?
- net antispoofing built-in
- cloud-init [TODO]


Trūkumai:

https://www.youtube.com/watch?v=uV61mVYsFM8

- kol kas tik x86 (no ARM)
- kiek vėlokai žengė į rinką (2011-2013 m.), todėl mažoka rinka
- valdoma per CLI, JSON ir truputį YAML (norint GUI reiktų naudoti Triton)
- rinkodaros strategija dar tik kuriama, ji kinta (todėl kitur stipresnės adminų ir jūzerių bendruomenės)

- VGA tik per VNC?

https://docs.google.com/document/d/1PFUmz6XpTVAGkq5dBe8uaBFV2Y4i-uR88AuiCLIRxIQ/edit

- kol kas neveikia VM Live Migration (dar tik kuriamas),
  veikia tik VM Warm/Cold Migration

https://people.freebsd.org/~neel/bhyve/bhyve_bsdcan_2011.pdf  +
https://papers.freebsd.org/2014/baldwin-Introduction_to_bhyve.files/slides.pdf  +

Apie Triton DataCenter:

https://docs.joyent.com/public-cloud/instances  +
https://github.com/joyent/triton/blob/master/README.md#overview (iš ko susidaro)  +

Apie SmartOS:

https://www.gaige.net/docker-on-smartos.html  +
https://www.cyber-tec.org/2018/02/11/run-docker-images-on-smartos/  +

Orientavimasis į Node.js:

https://www.joyent.com/blog/microservices-containers-nodejs  +


<<<

[.text-left]

[bibliography]
== Nuorodos

`2020-11-17` **[[[1]]]** Christine Taylor, https://www.serverwatch.com/virtualization/hypervisor-server/#:~:text=Linux%20KVM%20and%20FreeBSD%20bhyve[What Is a Hypervisor Server?]

`2016-06-01` **[[[2]]]** Marksei, https://www.marksei.com/what-is-virtual-machine/#:~:text=called%20Type%2D3%20or%20Type%2D1.5[What is a Virtual Machine?]

`2022-01-11` **[[[3]]]** (peržiūrėta) https://wiki.smartos.org/configuration-management-on-smartos/[Configuration Management on SmartOS]

`2012-04-13` **[[[4]]]** Jonathan Perkin, https://www.perkin.org.uk/posts/smartos-global-zone-tweaks.html[SmartOS global zone tweaks]

`2012-11-23` **[[[5]]]** Jonathan Perkin, https://www.perkin.org.uk/posts/smartos-and-the-global-zone.html#:~:text=on%20running%20SmartOS.-,So%20what%20can%20I%20do%3F,-Firstly%2C%20let%E2%80%99s%20look[SmartOS and the global zone]

`2021-07-08` **[[[6]]]** Michael Zeller, https://www.joyent.com/blog/reintroducing-bhyve#:~:text=This%20is%20what%20we%20mean%20when%20we%20say%20double%2Dhulled%2Dvirtualization[Reintroducing Bhyve]
