Duomenų centrai

== Laboratorinis darbas nr. 7 (+8): +++<br />+++ Virtualizacija

=== Darbo tikslas

Artimiau susipažinti su virtualizacija ir paanalizuoti _Type-1_ hipervizorių.


=== Bendra informacija

(toliau anglų k.)


==== Terminai

Virtual Machine -- _[TODO]_

VMM, Virtual machine manager -- _[TODO]_

Hypervisor -- _[TODO]_


==== Intro

.


==== Virtualization for Server Consolidation and Containment

.


==== Types of hypervisor

.


=== Parenkite trumpą ataskaitą, kurioje:

* bus pateiktas Jūsų pasirinkto `I`-tipo hipervizoriaus pristatymas (pagrindinės funkcijos ir pan.)
* laikysitės principo: _Less is more_; svarbu kokybė.
* išlaikykite vienodą stilių.


=== Parengtą ataskaitą PDF formatu įkelkite į `Moodle` sistemą


<<<

[.text-left]
== Darbo eiga

Pasirenku darbo apraše minimą _SmartOS_ hipervizorių.

Tiksliau, tai konverguota hipervizorinė platforma (ir operacijų sistema, OS).

Tai distribucija ne populiarios _Linux_ OS, bet _"illumOS"_ sistemos (2010 m. kilusios iš Solaris OS), ir yra klasikinė Unix OS.
Lyginant su _Linux_, ji turi gerokai stabilesnę architektūrą.

Virtualių mašinų (toliau VMų) valdymui _SmartOS_ siūlo du skirtingus hipervizorius pasirinktinai:

* **KVM**  <<21>> psl. 5 + 14   +
  (gana senos Linux 2.6.34 versijos VMM + senos _Qemu_ 0.14.1 versijos emuliatoriaus portas, 2011 m.);  +
* **bhyve**  <<24>> psl. 6  +
  (gana naujos FreeBSD 11.1 versijos VMM portas, 2017 m.)

Tiesą sakant, jie abu nėra gryni _Type I_ hipervizoriai. <<1>>

Jie abu startuoja ne iš „pliko metalo“, bet iš jau veikiančio įprastinės OS (Linux, FreeBSD, SmartOS) branduolio.
Ir jie abu tą OS paverčia _Type I_ hipervizoriumi, specializuoja.

Tačiau kadangi ši OS yra bendros paskirties, pagal apibrėžimą tokį hipervizorių tinka laikyti ir _Type II_ hipervizoriumi.

Dėl aiškumo juos abu priskiriu hibridinei _Type 1.5_ (dar vadinamai _Type 3_) kategorijai. <<2>>

Palyginimas tarpusavyje:

* **KVM**:
 ** Gana paplitęs VM mechanizmas / interfeisas;
 ** _SmartOS_ implementacija neleidžia plėsti VM resursų (tenka VM perkurti iš naujo);
 ** palaiko iki 256 vCPU / VM;  <<25>>
 ** palaiko iki 2 TiB RAM / VM.

* **bhyve**:
 ** _bhyve_ kilo kitoje OS, _FreeBSD_, ir naujas funkcijos ten atsiranda anksčiau / greičiau;  <<8>>
 ** Palaiko šiek mažiau OS atvaizdų;
 ** Palaiko tik UEFI:
  *** palaikomi tik su UEFI suderinami _Guest OS_;  <<9>> psl. 8
  *** nepalaiko tiesioginės Legacy BIOS/Boot-ROM kelties;  <<24>> psl. 12
  *** todėl kai kurie OS privalo turėti po skirtingą atvaizdą kiekvienam hipervizoriui;
 ** Didesnis našumas (angl. _Performance_);
 ** Didesnis plečiamumas (angl. _Scalability_);
 ** Modernus kodas, mažas _Overhead_, spartus
 ** integracija su `ZFS`:
   - akimirksniniai duomenų (FSų) klonai
   - duomenų šifravimas (jei reikia)
   - ir jų deduplikacija (jei reikia)
 ** Palaiko _labai_ įvairius Storage backend-us
 ** Su _illumOS_ branduolio išeities kodu ("CDDL") suderinama licencija ("Simplified BSD License") leidžia integruoti `bhyve` kodą tiesiogiai į šį branduolį.  +
  (Priešingai nei `KVM` atveju ir `GPL` licencija)
 ** _PCI pass-through_ galimybė
 ** integruotas `net antispoofing` mechanizmas;  <<9>> psl. 11
 ** palaiko tik 16 vCPU / VM;  <<26>>



Kadangi apie KVM tikėtinai rašys kiti grupiokai (o be to, čia naudojama senoka KVM versija), toliau akcentuoju _SmartOS_ + _bhyve_ VMM kombinaciją.


Pati _SmartOS_ yra specializuota -- skirta konverguotam VMų ir konteinerių startavimui / valdymui, ir niekam kitam:

* Užima mažai vietos (kelis šimtus MiB):
 ** => sparti keltis (įkrova), ~30s
 ** => sumažintas atakų perimetras
 ** Nodų priežiūrai rekomenduojama naudoti _Chef_ (gamintojo rekomenduojamiausią), _Ansible_ ar kt. _Configuration Management_ sistemą. <<3>>
* Skirta kelčiai iš R/O atvaizdo (_Live image_) ar bent ne diskinės medijos:
 ** per PXE (tinklu)
 ** iš USB Flash Disk (UFD)
 ** iš CD-ROM
 ** _Host OS_ nenaudoja lokalių diskų
  - => padidintas atsparumas sisteminio disko gedimams
  - => supaprastėja „diegimas“, ypač turint daug mašinų (vos keli nustatymai) <<4>>
  - => spartus atnaujinimas  +
       (pakanka tinklu nusikopijuoti bendrą OS atvaizdą + _Reboot_)
    *** kaskart per PXE
    *** vieną sykį į UFD per SSH
  - => daugiau vietos diskuose lieka _Guest OS_ egzemplioriams
* _in-memory_ / _Live OS_:
 ** _root_ failų sistema (FS) laikoma RAMe
 ** FS pakeitimai arba neįmanomi (R/O), arba efemeriški (`/etc`) <<5>>  +
    (išskyrus keletą svarbių direktorijų ir failų, atvirų rašymui; gal pvz.: ?)
  - => neveikia naujų vartotojų kūrimas
  - => `/usr` failai primontuoti R/O
  - => dar labiau sumažintas atakų perimetras
* Visi serverio lokalūs diskai apjungiami į vieną grupę (_pool_):
 ** apjungimas _programinis_
 ** apjungiama pagal RAIDZ
 ** schema panaši į RAID 5/6/7
  - => padidinta diskų I/O sparta ir patikimumas
 ** tinkliniai diskai nenaudojami
* Siūlo du virtualizacijos lygius:
 ** OS lygis (konteineriai);
 ** „geležies“ lygis (virtualios mašinos, VM);
* Naudoja ir dubliuotą virtualizaciją:
 ** Guest OSą palaikantis VMM procesas (tiek `qemu-kvm`, tiek `bhyve`) veikia tik konteineryje;  +
    (_Double hulled virtualization_ patentas <<6>>)
  - => dar labiau sumažintas atakos perimetras;  <<9>> psl. 9
  - => preciziškas Guest OSų valdymas -- konteineris užtikrina QoS, resursų valdymą, I/O ribojimą (angl. _throttling_), apskaitą, kitą instrumentuotę;  <<21>> psl. 22
  - => apjungtas konteinerių bei VMų valdymas (komandos `vmadm`)
 ** Abu hipervizoriai, `KVM` ir `bhyve` geba veikti kartu -- vienu metu viename hoste;  <<24>> psl. 8
* Host OS turi po atskirą įrankį:
  - `imgadm` valdyti Guest OS atvaizdams
  - `vmadm` valdyti Guest OS egzemplioriams
  - `dladm` valdyti OS tinklo interfeisams (L2, įskaitant jų virtualizavimą)
  - `ipadm` valdyti OS potinkliams (L3)
  - `fwadm` valdyti OS ugniasienei (L2 - L4)
* Naudoja tarpplatforminį paketų valdiklį `pkgsrc` (kilusį NetBSD sistemoje).


Dalis šių savybių išplaukia iš griežtai lokalios Host nodų talpyklinės architektūros. <<23>>

Tai reiškia, kad kiekviename Host node VMai yra saugomi lokaliuose diskuose ir startuoja ne iš NAS ar SAN tinklo.

Tokia architektūra lemia ne tipinį hipervizoriaus panaudojimo scenarijų (mažiau kompleksišką nei pvz. rinkos lyderis VMware _ESXi_).

Atkrinta _Storage_ tinklo įnešamas vėlinimas, taip pat padidėja Host nodų I/O nepriklausomumas.
Ir atsiranda kai kurie apribojimai:

* HA / FT turi veikti Application lygmenyje;
* Pasunkėja Live Migration įgyvendinimas.

Daugianodžių _SmartOS_ debesų valdymui siūlomas atskiras, irgi atvirojo kodo įrankis (angl. _Cloud management platform_) **Triton DataCenter** / **Triton Compute Service**, į kurio funkcijas irgi trumpai atsižvelgsiu. <<7>>

---

Privalumai:

- _Solaris_ / _illumOS_ projektuotas didesniam saugumui (apskritai patikimumui) nei Linux, ir naudojantis tai juntama tiesiogiai

- _VirtIO_ -- vieno efektyviausių paravirtualizacijos (PV) interfeisų palaikymas

- _cloud-init_ standarto palaikymas: <<19>>, <<20>>  +
 * Įgalina debesų (egzempliorių) inicializavimą nepriklausomai nuo platformos, pvz.:
  ** OS vartotojų paskyrų sukūrimą
  ** programinių paketų sudiegimą
  ** Git repozitorijų nuklonavimą
  ** apskritai kone bet kuriuos OS administravimo veiksmus.
 * Naudoja YAML sintaksę (tenka suderinti su SmartOS `vmadm` naudojama JSON sintakse)
 * Yra palaikomas tiek visų didžiųjų viešos debesijos tiekėjų, tiek atliekant OS provizijavimą ir privačiuose debesyse, ir „plikoj geležy“ (angl. _Bare metal_).

---

Trūkumai:

- Kol kas palaiko tik _x86_ architektūrą (_no ARM_);  <<10>>

- Kol kas neveikia VM Live Migration (dar tik kuriamas);  +
  veikia tik VM Warm/Cold Migration;  <<11>>

- Guest OS VGA išvestis pasiekiama tik VNC protokolu;

- Hostas valdomas per CLI, JSON ir truputį YAML (sąlyginis trūkumas).  +
  Norint GUI, reiktų naudoti debesinį orkestratorių _Triton_ arba _Project FiFo_ (kai mažesnis ūkis ir vengiama dedikuoto HNo, _Head-node_).

- Kiek vėlokai žengė į rinką (2011-2013 m.), todėl kol kas užima mažoką jos dalį;

- Rinkodaros strategija dar tik kuriama, ji kinta;  +
  (todėl stipresnės kitų hipervizorių adminų ir jūzerių bendruomenės)

---

Ankstesnės FreeBSD prezentacijos (apie komponentus):

- <<12>> --
- <<13>>

Apie Triton DataCenter:

- Konteinerių ir VMų Combo diagramos: <<14>>
- Detalesnė Triton DC sudėtis: <<15>>

Apie SmartOS:

- Docker konteinerių startavimas be _Triton_ pagalbos; <<16>>
  (t. p. ir `fwadm` aprašymas)
- Asmeninio Docker registro naudojimas. <<17>>

SmartOS orientavimasis į _Node.js_ servisus: <<18>>  +


<<<

[bibliography]
=== Nuorodos

`2020-11-17` **[[[1]]]** `serverwatch.com`, Christine Taylor,  https://www.serverwatch.com/virtualization/hypervisor-server/#:~:text=Linux%20KVM%20and%20FreeBSD%20bhyve[What Is a Hypervisor Server?]

`2016-06-01` **[[[2]]]** `marksei.com`, Marksei, https://www.marksei.com/what-is-virtual-machine/#:~:text=called%20Type%2D3%20or%20Type%2D1.5[What is a Virtual Machine?]

`2021-12-15` **[[[3]]]** `smartos.org`, (peržiūrėta) https://wiki.smartos.org/configuration-management-on-smartos/[Configuration Management on SmartOS]

`2012-04-13` **[[[4]]]** `perkin.org.uk`, Jonathan Perkin, https://www.perkin.org.uk/posts/smartos-global-zone-tweaks.html[SmartOS global zone tweaks]

`2012-11-23` **[[[5]]]** `perkin.org.uk`, Jonathan Perkin, https://www.perkin.org.uk/posts/smartos-and-the-global-zone.html#:~:text=on%20running%20SmartOS.-,So%20what%20can%20I%20do%3F,-Firstly%2C%20let%E2%80%99s%20look[SmartOS and the global zone]

`2021-07-08` **[[[6]]]** `joyent.com`, Michael Zeller, https://www.joyent.com/blog/reintroducing-bhyve#:~:text=This%20is%20what%20we%20mean%20when%20we%20say%20double%2Dhulled%2Dvirtualization[Reintroducing Bhyve]

`2021-01-05` **[[[7]]]** `joyent.com`, (redaguota) https://docs.joyent.com/private-cloud[Triton Operator Documentation]

`2020-09-03` **[[[8]]]** `klarasystems.com`, Allan Jude, https://klarasystems.com/articles/bhyve-the-freebsd-hypervisor/[bhyve | The FreeBSD Hypervisor]

`2018-03-05` **[[[9]]]** `bhyvecon.org`, Mike Gerdts, https://bhyvecon.org/bhyvecon2018-Gwydir.pdf[bhyve zones in SmartOS]

`2021-01-27` **[[[10]]]** `youtube.com`, Yaroslav Koisa, https://www.youtube.com/watch?v=uV61mVYsFM8[FreeBSD's Bhyve Overview: Why it's better than other hypervisors. At least for our use-case.]

`2021-07-01` **[[[11]]]** `docs.google.com`, Alan Jude, https://docs.google.com/document/d/1PFUmz6XpTVAGkq5dBe8uaBFV2Y4i-uR88AuiCLIRxIQ/[bhyve Weekly Call]

`2011-05-13` **[[[12]]]** `people.freebsd.org`, Neel Natu | Peter Grehan, https://people.freebsd.org/~neel/bhyve/bhyve_bsdcan_2011.pdf[BHyVe | BSD Hypervisor]

`2014-05-07` **[[[13]]]** `papers.freebsd.org`, John Baldwin, https://papers.freebsd.org/2014/baldwin-Introduction_to_bhyve.files/slides.pdf[Introduction to bhyve]

`2021-01-05` **[[[14]]]** `joyent.com`, (redaguota) https://docs.joyent.com/public-cloud/instances[Triton End User Documentation › Containers and virtual machines ›]

`2021-07-14` **[[[15]]]** `github.com/joyent/triton`, 
https://github.com/joyent/triton/blob/master/README.md#overview[Triton DataCenter | README]

`2021-06-11` **[[[16]]]** `gaige.net`, Gaige B. Paulsen, https://www.gaige.net/docker-on-smartos.html[Docker on SmartOS]

`2018-02-11` **[[[17]]]** `cyber-tec.org`, Thomas Merkel, https://www.cyber-tec.org/2018/02/11/run-docker-images-on-smartos/[Run Docker images on SmartOS]

`2017-01-12` **[[[18]]]** `joyent.com`, Wyatt Preul, https://www.joyent.com/blog/microservices-containers-nodejs[Containers and microservices and Node.js! Oh, my!]

`2019-09-04` **[[[19]]]** `readthedocs.io`, (redaguota) https://cloudinit.readthedocs.io/en/latest/topics/datasources/smartos.html[cloud-init » Docs » Datasources » SmartOS Datasource]

`2019-01-16` **[[[20]]]** `shaner.life`, Shaner, 
https://shaner.life/using-cloud-init-with-smartos/[Using cloud-init with SmartOS]

`2011-08-15` **[[[21]]]** `slideshare.net`, Bryan Cantrill, 
https://www.slideshare.net/bcantrill/experiences-porting-kvm-to-smartos/22[Experiences porting KVM to SmartOS]

`2012-06-29` **[[[22]]]** `github.com/joyent/illumos-kvm`, (redaguota) 
https://github.com/joyent/illumos-kvm/blob/master/README.md#illumos-kvm-kvm-for-illumos[illumos-kvm: KVM for illumos]

`2014-06-06` **[[[23]]]** `wikipedia.org`, (redaguota) Trentstersla, https://en.wikipedia.org/wiki/SmartOS#:~:text=SmartOS%20follows%20a%20strict%20local%20node%20storage%20architecture[SmartOS | "SmartOS follows a strict local node storage architecture"]

`2019-05-14` **[[[24]]]** `bhyvecon.org`, Patrick Mooney, 
https://bhyvecon.org/bhyveconOttawa2019-Patrick.pdf[Porting bhyve to SmartOS]

`2011-09-21` **[[[25]]]** `lwn.net`, Koen Vervloesem, https://lwn.net/Articles/459754/[SmartOS: virtualization with ZFS and KVM]

`2019-05-14` **[[[26]]]** `bhyvecon.org`, Rod Grimes, 
https://bhyvecon.org/bhyveconOttawa2019-Rodney.pdf#page=3[bhyve VM_MAXCPU cleanup | VM_MAXCPU]

